// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course_sessions_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkScheduleConflict = `-- name: CheckScheduleConflict :many
SELECT cs1.course_id as course_id_1, cs2.course_id as course_id_2, cs1.day_of_week, cs1.slot_number
FROM course_sessions_cache cs1
JOIN course_sessions_cache cs2
  ON cs1.day_of_week = cs2.day_of_week
  AND cs1.slot_number = cs2.slot_number
WHERE cs1.course_id = ANY($1::uuid[])
  AND cs2.course_id = ANY($1::uuid[])
  AND cs1.course_id != cs2.course_id
`

type CheckScheduleConflictRow struct {
	CourseID1  pgtype.UUID   `json:"course_id_1"`
	CourseID2  pgtype.UUID   `json:"course_id_2"`
	DayOfWeek  DayOfWeekEnum `json:"day_of_week"`
	SlotNumber int32         `json:"slot_number"`
}

func (q *Queries) CheckScheduleConflict(ctx context.Context, dollar_1 []pgtype.UUID) ([]CheckScheduleConflictRow, error) {
	rows, err := q.db.Query(ctx, checkScheduleConflict, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckScheduleConflictRow{}
	for rows.Next() {
		var i CheckScheduleConflictRow
		if err := rows.Scan(
			&i.CourseID1,
			&i.CourseID2,
			&i.DayOfWeek,
			&i.SlotNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkScheduleConflictWithExisting = `-- name: CheckScheduleConflictWithExisting :many
SELECT cs1.course_id as course_id_1, cs2.course_id as course_id_2, cs1.day_of_week, cs1.slot_number
FROM course_sessions_cache cs1
JOIN course_sessions_cache cs2
  ON cs1.day_of_week = cs2.day_of_week
  AND cs1.slot_number = cs2.slot_number
JOIN enrollment_program_courses epc ON cs2.course_id = epc.course_id
JOIN enrollment_programs ep ON epc.program_id = ep.id
WHERE cs1.course_id = ANY($1::uuid[])
  AND ep.student_id = $2
  AND ep.status = 'approved'
  AND cs1.course_id != cs2.course_id
`

type CheckScheduleConflictWithExistingParams struct {
	Dollar1   []pgtype.UUID `json:"dollar_1"`
	StudentID pgtype.UUID   `json:"student_id"`
}

func (q *Queries) CheckScheduleConflictWithExisting(ctx context.Context, arg CheckScheduleConflictWithExistingParams) ([]CheckScheduleConflictRow, error) {
	rows, err := q.db.Query(ctx, checkScheduleConflictWithExisting, arg.Dollar1, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckScheduleConflictRow{}
	for rows.Next() {
		var i CheckScheduleConflictRow
		if err := rows.Scan(
			&i.CourseID1,
			&i.CourseID2,
			&i.DayOfWeek,
			&i.SlotNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCourseSessionsByCourseID = `-- name: DeleteCourseSessionsByCourseID :exec
DELETE FROM course_sessions_cache
WHERE course_id = $1
`

func (q *Queries) DeleteCourseSessionsByCourseID(ctx context.Context, courseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseSessionsByCourseID, courseID)
	return err
}

const getSessionsByCourseIDs = `-- name: GetSessionsByCourseIDs :many
SELECT id, course_id, day_of_week, slot_number, synced_at
FROM course_sessions_cache
WHERE course_id = ANY($1::uuid[])
ORDER BY course_id, day_of_week, slot_number
`

func (q *Queries) GetSessionsByCourseIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]CourseSessionsCache, error) {
	rows, err := q.db.Query(ctx, getSessionsByCourseIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CourseSessionsCache{}
	for rows.Next() {
		var i CourseSessionsCache
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.DayOfWeek,
			&i.SlotNumber,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCourseSession = `-- name: UpsertCourseSession :one
INSERT INTO course_sessions_cache (
    id, course_id, day_of_week, slot_number, synced_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
ON CONFLICT (course_id, day_of_week, slot_number) DO UPDATE SET
    synced_at = NOW()
RETURNING id, course_id, day_of_week, slot_number, synced_at
`

type UpsertCourseSessionParams struct {
	ID         pgtype.UUID   `json:"id"`
	CourseID   pgtype.UUID   `json:"course_id"`
	DayOfWeek  DayOfWeekEnum `json:"day_of_week"`
	SlotNumber int32         `json:"slot_number"`
}

func (q *Queries) UpsertCourseSession(ctx context.Context, arg UpsertCourseSessionParams) (CourseSessionsCache, error) {
	row := q.db.QueryRow(ctx, upsertCourseSession,
		arg.ID,
		arg.CourseID,
		arg.DayOfWeek,
		arg.SlotNumber,
	)
	var i CourseSessionsCache
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.DayOfWeek,
		&i.SlotNumber,
		&i.SyncedAt,
	)
	return i, err
}
