// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment_programs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollmentProgram = `-- name: CreateEnrollmentProgram :one
INSERT INTO enrollment_programs (
    student_id, semester, status, created_at
) VALUES (
    $1, $2, $3, NOW()
)
RETURNING id, student_id, semester, status, created_at
`

type CreateEnrollmentProgramParams struct {
	StudentID pgtype.UUID              `json:"student_id"`
	Semester  string                   `json:"semester"`
	Status    NullEnrollmentStatusEnum `json:"status"`
}

func (q *Queries) CreateEnrollmentProgram(ctx context.Context, arg CreateEnrollmentProgramParams) (EnrollmentProgram, error) {
	row := q.db.QueryRow(ctx, createEnrollmentProgram, arg.StudentID, arg.Semester, arg.Status)
	var i EnrollmentProgram
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Semester,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const lockPendingProgram = `-- name: LockPendingProgram :one
SELECT id, student_id, semester, status, created_at
FROM enrollment_programs
WHERE id = $1 AND status = 'pending'
FOR UPDATE
`

func (q *Queries) LockPendingProgram(ctx context.Context, id pgtype.UUID) (EnrollmentProgram, error) {
	row := q.db.QueryRow(ctx, lockPendingProgram, id)
	var i EnrollmentProgram
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Semester,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEnrollmentProgram = `-- name: DeleteEnrollmentProgram :exec
DELETE FROM enrollment_programs
WHERE id = $1
`

func (q *Queries) DeleteEnrollmentProgram(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnrollmentProgram, id)
	return err
}

const getEnrollmentProgramByID = `-- name: GetEnrollmentProgramByID :one
SELECT id, student_id, semester, status, created_at
FROM enrollment_programs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEnrollmentProgramByID(ctx context.Context, id pgtype.UUID) (EnrollmentProgram, error) {
	row := q.db.QueryRow(ctx, getEnrollmentProgramByID, id)
	var i EnrollmentProgram
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Semester,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentProgramByStudentAndSemester = `-- name: GetEnrollmentProgramByStudentAndSemester :one
SELECT id, student_id, semester, status, created_at
FROM enrollment_programs
WHERE student_id = $1 AND semester = $2
LIMIT 1
`

type GetEnrollmentProgramByStudentAndSemesterParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Semester  string      `json:"semester"`
}

func (q *Queries) GetEnrollmentProgramByStudentAndSemester(ctx context.Context, arg GetEnrollmentProgramByStudentAndSemesterParams) (EnrollmentProgram, error) {
	row := q.db.QueryRow(ctx, getEnrollmentProgramByStudentAndSemester, arg.StudentID, arg.Semester)
	var i EnrollmentProgram
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Semester,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentProgramsByStudent = `-- name: GetEnrollmentProgramsByStudent :many
SELECT id, student_id, semester, status, created_at
FROM enrollment_programs
WHERE student_id = $1
  AND ($2::VARCHAR IS NULL OR $2 = '' OR semester = $2)
  AND ($3::VARCHAR IS NULL OR $3 = '' OR status = $3::enrollment_status_enum)
ORDER BY created_at DESC
`

type GetEnrollmentProgramsByStudentParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Column2   string      `json:"column_2"`
	Column3   string      `json:"column_3"`
}

func (q *Queries) GetEnrollmentProgramsByStudent(ctx context.Context, arg GetEnrollmentProgramsByStudentParams) ([]EnrollmentProgram, error) {
	rows, err := q.db.Query(ctx, getEnrollmentProgramsByStudent, arg.StudentID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentProgram{}
	for rows.Next() {
		var i EnrollmentProgram
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Semester,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingProgramsByAdvisor = `-- name: GetPendingProgramsByAdvisor :many
SELECT 
    ep.id, 
    ep.student_id, 
    ep.semester, 
    ep.status, 
    ep.created_at,
    sc.first_name,
    sc.last_name,
    sc.student_number,
    sc.department,
    sc.class_level
FROM enrollment_programs ep
JOIN students_cache sc ON ep.student_id = sc.id
WHERE sc.advisor_id = $1 AND ep.status = 'pending'
ORDER BY ep.created_at
`

type GetPendingProgramsByAdvisorRow struct {
	ID            pgtype.UUID              `json:"id"`
	StudentID     pgtype.UUID              `json:"student_id"`
	Semester      string                   `json:"semester"`
	Status        NullEnrollmentStatusEnum `json:"status"`
	CreatedAt     pgtype.Timestamp         `json:"created_at"`
	FirstName     pgtype.Text              `json:"first_name"`
	LastName      pgtype.Text              `json:"last_name"`
	StudentNumber string                   `json:"student_number"`
	Department    pgtype.Text              `json:"department"`
	ClassLevel    pgtype.Int2              `json:"class_level"`
}

func (q *Queries) GetPendingProgramsByAdvisor(ctx context.Context, advisorID pgtype.UUID) ([]GetPendingProgramsByAdvisorRow, error) {
	rows, err := q.db.Query(ctx, getPendingProgramsByAdvisor, advisorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingProgramsByAdvisorRow{}
	for rows.Next() {
		var i GetPendingProgramsByAdvisorRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Semester,
			&i.Status,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.StudentNumber,
			&i.Department,
			&i.ClassLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgramStatus = `-- name: UpdateProgramStatus :one
UPDATE enrollment_programs
SET status = $2
WHERE id = $1
RETURNING id, student_id, semester, status, created_at
`

type UpdateProgramStatusParams struct {
	ID     pgtype.UUID              `json:"id"`
	Status NullEnrollmentStatusEnum `json:"status"`
}

func (q *Queries) UpdateProgramStatus(ctx context.Context, arg UpdateProgramStatusParams) (EnrollmentProgram, error) {
	row := q.db.QueryRow(ctx, updateProgramStatus, arg.ID, arg.Status)
	var i EnrollmentProgram
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Semester,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
