// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment_program_courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollmentProgramCourse = `-- name: CreateEnrollmentProgramCourse :one
INSERT INTO enrollment_program_courses (
    program_id, course_id, created_at
) VALUES (
    $1, $2, NOW()
)
RETURNING id, program_id, course_id, created_at
`

type CreateEnrollmentProgramCourseParams struct {
	ProgramID pgtype.UUID `json:"program_id"`
	CourseID  pgtype.UUID `json:"course_id"`
}

func (q *Queries) CreateEnrollmentProgramCourse(ctx context.Context, arg CreateEnrollmentProgramCourseParams) (EnrollmentProgramCourse, error) {
	row := q.db.QueryRow(ctx, createEnrollmentProgramCourse, arg.ProgramID, arg.CourseID)
	var i EnrollmentProgramCourse
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.CourseID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProgramCourses = `-- name: DeleteProgramCourses :exec
DELETE FROM enrollment_program_courses
WHERE program_id = $1
`

func (q *Queries) DeleteProgramCourses(ctx context.Context, programID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProgramCourses, programID)
	return err
}

const getCoursesByProgramID = `-- name: GetCoursesByProgramID :many
SELECT epc.id, epc.program_id, epc.course_id, epc.created_at,
       sc.course_code, sc.course_name, sc.credits, sc.instructor_fullname
FROM enrollment_program_courses epc
JOIN semester_courses_cache sc ON epc.course_id = sc.id
WHERE epc.program_id = $1
ORDER BY sc.course_code
`

type GetCoursesByProgramIDRow struct {
	ID                 pgtype.UUID      `json:"id"`
	ProgramID          pgtype.UUID      `json:"program_id"`
	CourseID           pgtype.UUID      `json:"course_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	CourseCode         string           `json:"course_code"`
	CourseName         pgtype.Text      `json:"course_name"`
	Credits            int16            `json:"credits"`
	InstructorFullname pgtype.Text      `json:"instructor_fullname"`
}

func (q *Queries) GetCoursesByProgramID(ctx context.Context, programID pgtype.UUID) ([]GetCoursesByProgramIDRow, error) {
	rows, err := q.db.Query(ctx, getCoursesByProgramID, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursesByProgramIDRow{}
	for rows.Next() {
		var i GetCoursesByProgramIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.CourseID,
			&i.CreatedAt,
			&i.CourseCode,
			&i.CourseName,
			&i.Credits,
			&i.InstructorFullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
