// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CourseTypeEnum string

const (
	CourseTypeEnumMandatory CourseTypeEnum = "mandatory"
	CourseTypeEnumElective  CourseTypeEnum = "elective"
)

func (e *CourseTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseTypeEnum(s)
	case string:
		*e = CourseTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseTypeEnum: %T", src)
	}
	return nil
}

type NullCourseTypeEnum struct {
	CourseTypeEnum CourseTypeEnum `json:"course_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if CourseTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CourseTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseTypeEnum), nil
}

type DayOfWeekEnum string

const (
	DayOfWeekEnumMonday    DayOfWeekEnum = "monday"
	DayOfWeekEnumTuesday   DayOfWeekEnum = "tuesday"
	DayOfWeekEnumWednesday DayOfWeekEnum = "wednesday"
	DayOfWeekEnumThursday  DayOfWeekEnum = "thursday"
	DayOfWeekEnumFriday    DayOfWeekEnum = "friday"
	DayOfWeekEnumSaturday  DayOfWeekEnum = "saturday"
	DayOfWeekEnumSunday    DayOfWeekEnum = "sunday"
)

func (e *DayOfWeekEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayOfWeekEnum(s)
	case string:
		*e = DayOfWeekEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DayOfWeekEnum: %T", src)
	}
	return nil
}

type NullDayOfWeekEnum struct {
	DayOfWeekEnum DayOfWeekEnum `json:"day_of_week_enum"`
	Valid         bool          `json:"valid"` // Valid is true if DayOfWeekEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayOfWeekEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DayOfWeekEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayOfWeekEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayOfWeekEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayOfWeekEnum), nil
}

type EnrollmentStatusEnum string

const (
	EnrollmentStatusEnumPending  EnrollmentStatusEnum = "pending"
	EnrollmentStatusEnumApproved EnrollmentStatusEnum = "approved"
)

func (e *EnrollmentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentStatusEnum(s)
	case string:
		*e = EnrollmentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentStatusEnum: %T", src)
	}
	return nil
}

type NullEnrollmentStatusEnum struct {
	EnrollmentStatusEnum EnrollmentStatusEnum `json:"enrollment_status_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if EnrollmentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnrollmentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EnrollmentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnrollmentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnrollmentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnrollmentStatusEnum), nil
}

type AcademicPeriod struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CourseSessionsCache struct {
	ID         pgtype.UUID      `json:"id"`
	CourseID   pgtype.UUID      `json:"course_id"`
	DayOfWeek  DayOfWeekEnum    `json:"day_of_week"`
	SlotNumber int32            `json:"slot_number"`
	SyncedAt   pgtype.Timestamp `json:"synced_at"`
}

type EnrollmentProgram struct {
	ID        pgtype.UUID              `json:"id"`
	StudentID pgtype.UUID              `json:"student_id"`
	Semester  string                   `json:"semester"`
	Status    NullEnrollmentStatusEnum `json:"status"`
	CreatedAt pgtype.Timestamp         `json:"created_at"`
}

type EnrollmentProgramCourse struct {
	ID        pgtype.UUID      `json:"id"`
	ProgramID pgtype.UUID      `json:"program_id"`
	CourseID  pgtype.UUID      `json:"course_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type EnrollmentRejectionLog struct {
	ID                pgtype.UUID      `json:"id"`
	OriginalProgramID pgtype.UUID      `json:"original_program_id"`
	StudentID         pgtype.UUID      `json:"student_id"`
	AdvisorID         pgtype.UUID      `json:"advisor_id"`
	AdvisorFullname   string           `json:"advisor_fullname"`
	Semester          string           `json:"semester"`
	RejectionReason   string           `json:"rejection_reason"`
	RejectedCourses   []byte           `json:"rejected_courses"`
	RejectedAt        pgtype.Timestamp `json:"rejected_at"`
}

type OutboxEvent struct {
	ID          pgtype.UUID      `json:"id"`
	EventType   string           `json:"event_type"`
	AggregateID pgtype.UUID      `json:"aggregate_id"`
	Payload     []byte           `json:"payload"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
	Status      pgtype.Text      `json:"status"`
}

type ProcessedEvent struct {
	EventID     pgtype.UUID      `json:"event_id"`
	EventType   string           `json:"event_type"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type SemesterCoursesCache struct {
	ID                 pgtype.UUID      `json:"id"`
	CourseCode         string           `json:"course_code"`
	CourseName         pgtype.Text      `json:"course_name"`
	Faculty            pgtype.Text      `json:"faculty"`
	Department         pgtype.Text      `json:"department"`
	Credits            int16            `json:"credits"`
	CourseType         CourseTypeEnum   `json:"course_type"`
	ClassLevel         pgtype.Int2      `json:"class_level"`
	Semester           string           `json:"semester"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname pgtype.Text      `json:"instructor_fullname"`
	ClassroomLocation  pgtype.Text      `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	CurrentEnrollment  pgtype.Int2      `json:"current_enrollment"`
	Prerequisites      []byte           `json:"prerequisites"`
	SyncedAt           pgtype.Timestamp `json:"synced_at"`
}

type StudentPassedPrerequisite struct {
	StudentID  pgtype.UUID      `json:"student_id"`
	CourseCode string           `json:"course_code"`
	Semester   string           `json:"semester"`
	GradePoint pgtype.Text      `json:"grade_point"`
	SyncedAt   pgtype.Timestamp `json:"synced_at"`
}

type StudentsCache struct {
	ID            pgtype.UUID      `json:"id"`
	StudentNumber string           `json:"student_number"`
	Email         string           `json:"email"`
	FirstName     pgtype.Text      `json:"first_name"`
	LastName      pgtype.Text      `json:"last_name"`
	Department    pgtype.Text      `json:"department"`
	ClassLevel    pgtype.Int2      `json:"class_level"`
	AdvisorID     pgtype.UUID      `json:"advisor_id"`
	Status        pgtype.Text      `json:"status"`
	IsActive      pgtype.Bool      `json:"is_active"`
	SyncedAt      pgtype.Timestamp `json:"synced_at"`
}
