// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (event_type, aggregate_id, payload, created_at, status)
VALUES ($1, $2, $3, NOW(), 'pending')
RETURNING id, event_type, aggregate_id, payload, created_at, processed_at, status
`

type CreateOutboxEventParams struct {
	EventType   string      `json:"event_type"`
	AggregateID pgtype.UUID `json:"aggregate_id"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.AggregateID, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateID,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.Status,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, aggregate_id, payload, created_at, processed_at, status
FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET status = 'failed'
WHERE id = $1
`

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, id)
	return err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET status = 'processed', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}
