// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: semester_courses_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementEnrollment = `-- name: DecrementEnrollment :execrows
UPDATE semester_courses_cache
SET current_enrollment = current_enrollment - 1
WHERE id = $1 AND current_enrollment > 0
`

func (q *Queries) DecrementEnrollment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, decrementEnrollment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSemesterCourse = `-- name: DeleteSemesterCourse :exec
DELETE FROM semester_courses_cache
WHERE id = $1
`

func (q *Queries) DeleteSemesterCourse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSemesterCourse, id)
	return err
}

const getAvailableCourses = `-- name: GetAvailableCourses :many
SELECT id, course_code, course_name, faculty, department, credits, course_type, class_level,
       semester, instructor_id, instructor_fullname, classroom_location,
       max_capacity, current_enrollment, prerequisites, synced_at
FROM semester_courses_cache
WHERE department = $1
  AND class_level <= $2
  AND semester = $3
ORDER BY class_level, course_code
`

type GetAvailableCoursesParams struct {
	Department pgtype.Text `json:"department"`
	ClassLevel pgtype.Int2 `json:"class_level"`
	Semester   string      `json:"semester"`
}

func (q *Queries) GetAvailableCourses(ctx context.Context, arg GetAvailableCoursesParams) ([]SemesterCoursesCache, error) {
	rows, err := q.db.Query(ctx, getAvailableCourses, arg.Department, arg.ClassLevel, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SemesterCoursesCache{}
	for rows.Next() {
		var i SemesterCoursesCache
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.CourseName,
			&i.Faculty,
			&i.Department,
			&i.Credits,
			&i.CourseType,
			&i.ClassLevel,
			&i.Semester,
			&i.InstructorID,
			&i.InstructorFullname,
			&i.ClassroomLocation,
			&i.MaxCapacity,
			&i.CurrentEnrollment,
			&i.Prerequisites,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, course_code, course_name, faculty, department, credits, course_type, class_level,
       semester, instructor_id, instructor_fullname, classroom_location,
       max_capacity, current_enrollment, prerequisites, synced_at
FROM semester_courses_cache
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (SemesterCoursesCache, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i SemesterCoursesCache
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.CourseName,
		&i.Faculty,
		&i.Department,
		&i.Credits,
		&i.CourseType,
		&i.ClassLevel,
		&i.Semester,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.ClassroomLocation,
		&i.MaxCapacity,
		&i.CurrentEnrollment,
		&i.Prerequisites,
		&i.SyncedAt,
	)
	return i, err
}

const getCoursesByIDs = `-- name: GetCoursesByIDs :many
SELECT id, course_code, course_name, faculty, department, credits, course_type, class_level,
       semester, instructor_id, instructor_fullname, classroom_location,
       max_capacity, current_enrollment, prerequisites, synced_at
FROM semester_courses_cache
WHERE id = ANY($1::uuid[])
ORDER BY id
`

func (q *Queries) GetCoursesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]SemesterCoursesCache, error) {
	rows, err := q.db.Query(ctx, getCoursesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SemesterCoursesCache{}
	for rows.Next() {
		var i SemesterCoursesCache
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.CourseName,
			&i.Faculty,
			&i.Department,
			&i.Credits,
			&i.CourseType,
			&i.ClassLevel,
			&i.Semester,
			&i.InstructorID,
			&i.InstructorFullname,
			&i.ClassroomLocation,
			&i.MaxCapacity,
			&i.CurrentEnrollment,
			&i.Prerequisites,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoursesForCapacityCheck = `-- name: GetCoursesForCapacityCheck :many
SELECT id, current_enrollment, max_capacity
FROM semester_courses_cache
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

type GetCoursesForCapacityCheckRow struct {
	ID                pgtype.UUID `json:"id"`
	CurrentEnrollment pgtype.Int2 `json:"current_enrollment"`
	MaxCapacity       int16       `json:"max_capacity"`
}

func (q *Queries) GetCoursesForCapacityCheck(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCoursesForCapacityCheckRow, error) {
	rows, err := q.db.Query(ctx, getCoursesForCapacityCheck, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursesForCapacityCheckRow{}
	for rows.Next() {
		var i GetCoursesForCapacityCheckRow
		if err := rows.Scan(&i.ID, &i.CurrentEnrollment, &i.MaxCapacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementEnrollment = `-- name: IncrementEnrollment :execrows
UPDATE semester_courses_cache
SET current_enrollment = current_enrollment + 1
WHERE id = $1 AND current_enrollment < max_capacity
`

func (q *Queries) IncrementEnrollment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementEnrollment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSemesterCourse = `-- name: UpsertSemesterCourse :one
INSERT INTO semester_courses_cache (
    id, course_code, course_name, faculty, department, credits, course_type, class_level,
    semester, instructor_id, instructor_fullname, classroom_location, max_capacity,
    current_enrollment, prerequisites, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    course_code = EXCLUDED.course_code,
    course_name = EXCLUDED.course_name,
    faculty = EXCLUDED.faculty,
    department = EXCLUDED.department,
    credits = EXCLUDED.credits,
    course_type = EXCLUDED.course_type,
    class_level = EXCLUDED.class_level,
    semester = EXCLUDED.semester,
    instructor_id = EXCLUDED.instructor_id,
    instructor_fullname = EXCLUDED.instructor_fullname,
    classroom_location = EXCLUDED.classroom_location,
    max_capacity = EXCLUDED.max_capacity,
    prerequisites = EXCLUDED.prerequisites,
    synced_at = NOW()
RETURNING id, course_code, course_name, faculty, department, credits, course_type, class_level,
          semester, instructor_id, instructor_fullname, classroom_location,
          max_capacity, current_enrollment, prerequisites, synced_at
`

type UpsertSemesterCourseParams struct {
	ID                 pgtype.UUID    `json:"id"`
	CourseCode         string         `json:"course_code"`
	CourseName         pgtype.Text    `json:"course_name"`
	Faculty            pgtype.Text    `json:"faculty"`
	Department         pgtype.Text    `json:"department"`
	Credits            int16          `json:"credits"`
	CourseType         CourseTypeEnum `json:"course_type"`
	ClassLevel         pgtype.Int2    `json:"class_level"`
	Semester           string         `json:"semester"`
	InstructorID       pgtype.UUID    `json:"instructor_id"`
	InstructorFullname pgtype.Text    `json:"instructor_fullname"`
	ClassroomLocation  pgtype.Text    `json:"classroom_location"`
	MaxCapacity        int16          `json:"max_capacity"`
	CurrentEnrollment  pgtype.Int2    `json:"current_enrollment"`
	Prerequisites      []byte         `json:"prerequisites"`
}

func (q *Queries) UpsertSemesterCourse(ctx context.Context, arg UpsertSemesterCourseParams) (SemesterCoursesCache, error) {
	row := q.db.QueryRow(ctx, upsertSemesterCourse,
		arg.ID,
		arg.CourseCode,
		arg.CourseName,
		arg.Faculty,
		arg.Department,
		arg.Credits,
		arg.CourseType,
		arg.ClassLevel,
		arg.Semester,
		arg.InstructorID,
		arg.InstructorFullname,
		arg.ClassroomLocation,
		arg.MaxCapacity,
		arg.CurrentEnrollment,
		arg.Prerequisites,
	)
	var i SemesterCoursesCache
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.CourseName,
		&i.Faculty,
		&i.Department,
		&i.Credits,
		&i.CourseType,
		&i.ClassLevel,
		&i.Semester,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.ClassroomLocation,
		&i.MaxCapacity,
		&i.CurrentEnrollment,
		&i.Prerequisites,
		&i.SyncedAt,
	)
	return i, err
}
