// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateStudent = `-- name: DeactivateStudent :exec
UPDATE students_cache
SET is_active = false, synced_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStudent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateStudent, id)
	return err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, student_number, email, first_name, last_name, department, class_level, advisor_id, status, is_active, synced_at
FROM students_cache
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (StudentsCache, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i StudentsCache
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Department,
		&i.ClassLevel,
		&i.AdvisorID,
		&i.Status,
		&i.IsActive,
		&i.SyncedAt,
	)
	return i, err
}

const getStudentsByAdvisorID = `-- name: GetStudentsByAdvisorID :many
SELECT id, student_number, email, first_name, last_name, department, class_level, advisor_id, status, is_active, synced_at
FROM students_cache
WHERE advisor_id = $1 AND is_active = true
ORDER BY student_number
`

func (q *Queries) GetStudentsByAdvisorID(ctx context.Context, advisorID pgtype.UUID) ([]StudentsCache, error) {
	rows, err := q.db.Query(ctx, getStudentsByAdvisorID, advisorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentsCache{}
	for rows.Next() {
		var i StudentsCache
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Department,
			&i.ClassLevel,
			&i.AdvisorID,
			&i.Status,
			&i.IsActive,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStudent = `-- name: UpsertStudent :one
INSERT INTO students_cache (
    id, student_number, email, first_name, last_name, department, class_level, advisor_id, status, is_active, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    student_number = EXCLUDED.student_number,
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    department = EXCLUDED.department,
    class_level = EXCLUDED.class_level,
    advisor_id = EXCLUDED.advisor_id,
    status = EXCLUDED.status,
    is_active = EXCLUDED.is_active,
    synced_at = NOW()
RETURNING id, student_number, email, first_name, last_name, department, class_level, advisor_id, status, is_active, synced_at
`

type UpsertStudentParams struct {
	ID            pgtype.UUID `json:"id"`
	StudentNumber string      `json:"student_number"`
	Email         string      `json:"email"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	Department    pgtype.Text `json:"department"`
	ClassLevel    pgtype.Int2 `json:"class_level"`
	AdvisorID     pgtype.UUID `json:"advisor_id"`
	Status        pgtype.Text `json:"status"`
	IsActive      pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpsertStudent(ctx context.Context, arg UpsertStudentParams) (StudentsCache, error) {
	row := q.db.QueryRow(ctx, upsertStudent,
		arg.ID,
		arg.StudentNumber,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Department,
		arg.ClassLevel,
		arg.AdvisorID,
		arg.Status,
		arg.IsActive,
	)
	var i StudentsCache
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Department,
		&i.ClassLevel,
		&i.AdvisorID,
		&i.Status,
		&i.IsActive,
		&i.SyncedAt,
	)
	return i, err
}
