// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student_passed_prerequisites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPrerequisitePassed = `-- name: CheckPrerequisitePassed :one
SELECT EXISTS(
    SELECT 1 FROM student_passed_prerequisites
    WHERE student_id = $1 AND course_code = $2
) as passed
`

type CheckPrerequisitePassedParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	CourseCode string      `json:"course_code"`
}

func (q *Queries) CheckPrerequisitePassed(ctx context.Context, arg CheckPrerequisitePassedParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPrerequisitePassed, arg.StudentID, arg.CourseCode)
	var passed bool
	err := row.Scan(&passed)
	return passed, err
}

const getPassedPrerequisitesByStudent = `-- name: GetPassedPrerequisitesByStudent :many
SELECT student_id, course_code, semester, grade_point, synced_at
FROM student_passed_prerequisites
WHERE student_id = $1
ORDER BY semester DESC
`

func (q *Queries) GetPassedPrerequisitesByStudent(ctx context.Context, studentID pgtype.UUID) ([]StudentPassedPrerequisite, error) {
	rows, err := q.db.Query(ctx, getPassedPrerequisitesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentPassedPrerequisite{}
	for rows.Next() {
		var i StudentPassedPrerequisite
		if err := rows.Scan(
			&i.StudentID,
			&i.CourseCode,
			&i.Semester,
			&i.GradePoint,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPassedPrerequisite = `-- name: UpsertPassedPrerequisite :one
INSERT INTO student_passed_prerequisites (
    student_id, course_code, semester, grade_point, synced_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
ON CONFLICT (student_id, course_code) DO UPDATE SET
    semester = EXCLUDED.semester,
    grade_point = EXCLUDED.grade_point,
    synced_at = NOW()
RETURNING student_id, course_code, semester, grade_point, synced_at
`

type UpsertPassedPrerequisiteParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	CourseCode string      `json:"course_code"`
	Semester   string      `json:"semester"`
	GradePoint pgtype.Text `json:"grade_point"`
}

func (q *Queries) UpsertPassedPrerequisite(ctx context.Context, arg UpsertPassedPrerequisiteParams) (StudentPassedPrerequisite, error) {
	row := q.db.QueryRow(ctx, upsertPassedPrerequisite,
		arg.StudentID,
		arg.CourseCode,
		arg.Semester,
		arg.GradePoint,
	)
	var i StudentPassedPrerequisite
	err := row.Scan(
		&i.StudentID,
		&i.CourseCode,
		&i.Semester,
		&i.GradePoint,
		&i.SyncedAt,
	)
	return i, err
}
