// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxStatusEnum string

const (
	AuthOutboxStatusEnumPending   OutboxStatusEnum = "pending"
	AuthOutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	AuthOutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"auth_outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type OutboxEvent struct {
	ID           pgtype.UUID      `json:"id"`
	EventType    string           `json:"event_type"`
	RoutingKey   string           `json:"routing_key"`
	Payload      []byte           `json:"payload"`
	Status       OutboxStatusEnum `json:"status"`
	RetryCount   int16            `json:"retry_count"`
	MaxRetries   int16            `json:"max_retries"`
	ErrorMessage *string          `json:"error_message"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ProcessedAt  pgtype.Timestamp `json:"processed_at"`
}

type ProcessedEvent struct {
	EventID     string           `json:"event_id"`
	EventType   string           `json:"event_type"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type Session struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	RefreshTokenJti string           `json:"refresh_token_jti"`
	DeviceInfo      *string          `json:"device_info"`
	IpAddress       *string          `json:"ip_address"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
	LastUsedAt      pgtype.Timestamp `json:"last_used_at"`
}

type User struct {
	ID                  pgtype.UUID      `json:"id"`
	Email               string           `json:"email"`
	PasswordHash        string           `json:"password_hash"`
	Role                string           `json:"role"`
	Department          *string          `json:"department"`
	IsActive            *bool            `json:"is_active"`
	TokenVersion        *int32           `json:"token_version"`
	ForcePasswordChange *bool            `json:"force_password_change"`
	FailedLoginAttempts *int32           `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamp `json:"locked_until"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
}
