// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM auth.sessions
WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth.sessions (user_id, refresh_token_jti, device_info, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token_jti, device_info, ip_address, created_at, expires_at, last_used_at
`

type CreateSessionParams struct {
	UserID          pgtype.UUID      `json:"user_id"`
	RefreshTokenJti string           `json:"refresh_token_jti"`
	DeviceInfo      *string          `json:"device_info"`
	IpAddress       *string          `json:"ip_address"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenJti,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenJti,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAllUserSessions = `-- name: DeleteAllUserSessions :exec
DELETE FROM auth.sessions
WHERE user_id = $1
`

func (q *Queries) DeleteAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserSessions, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM auth.sessions
WHERE refresh_token_jti = $1
`

func (q *Queries) DeleteSession(ctx context.Context, refreshTokenJti string) error {
	_, err := q.db.Exec(ctx, deleteSession, refreshTokenJti)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM auth.sessions
WHERE id = $1 AND user_id = $2
`

type DeleteSessionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSessionByID(ctx context.Context, arg DeleteSessionByIDParams) error {
	_, err := q.db.Exec(ctx, deleteSessionByID, arg.ID, arg.UserID)
	return err
}

const getSessionByJTI = `-- name: GetSessionByJTI :one
SELECT id, user_id, refresh_token_jti, device_info, ip_address, created_at, expires_at, last_used_at
FROM auth.sessions
WHERE refresh_token_jti = $1
LIMIT 1
`

func (q *Queries) GetSessionByJTI(ctx context.Context, refreshTokenJti string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByJTI, refreshTokenJti)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenJti,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, user_id, refresh_token_jti, device_info, ip_address, created_at, expires_at, last_used_at
FROM auth.sessions
WHERE user_id = $1
ORDER BY last_used_at DESC
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenJti,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE auth.sessions
SET last_used_at = NOW()
WHERE refresh_token_jti = $1
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, refreshTokenJti string) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, refreshTokenJti)
	return err
}
