// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminExists = `-- name: AdminExists :one
SELECT EXISTS(SELECT 1 FROM auth.users WHERE role = 'admin' AND is_active = true) AS exists
`

func (q *Queries) AdminExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, adminExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEmailVersionSync = `-- name: CheckEmailVersionSync :one
UPDATE auth.users
SET token_version = token_version + 1,
    updated_at = NOW()
WHERE id = $1 AND email != $2
RETURNING token_version
`

type CheckEmailVersionSyncParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) CheckEmailVersionSync(ctx context.Context, arg CheckEmailVersionSyncParams) (*int32, error) {
	row := q.db.QueryRow(ctx, checkEmailVersionSync, arg.ID, arg.Email)
	var token_version *int32
	err := row.Scan(&token_version)
	return token_version, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (id, email, password_hash, role, department, is_active, token_version, force_password_change)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
RETURNING id, email, role, department, is_active, force_password_change, created_at, updated_at
`

type CreateUserParams struct {
	ID                  pgtype.UUID `json:"id"`
	Email               string      `json:"email"`
	PasswordHash        string      `json:"password_hash"`
	Role                string      `json:"role"`
	Department          *string     `json:"department"`
	IsActive            *bool       `json:"is_active"`
	TokenVersion        *int32      `json:"token_version"`
	ForcePasswordChange *bool       `json:"force_password_change"`
}

type CreateUserRow struct {
	ID                  pgtype.UUID      `json:"id"`
	Email               string           `json:"email"`
	Role                string           `json:"role"`
	Department          *string          `json:"department"`
	IsActive            *bool            `json:"is_active"`
	ForcePasswordChange *bool            `json:"force_password_change"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Department,
		arg.IsActive,
		arg.TokenVersion,
		arg.ForcePasswordChange,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Department,
		&i.IsActive,
		&i.ForcePasswordChange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE auth.users
SET is_active = false,
    deleted_at = NOW(),
    token_version = token_version + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, department, is_active, token_version,
       force_password_change, failed_login_attempts, locked_until,
       created_at, updated_at, deleted_at
FROM auth.users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Department,
		&i.IsActive,
		&i.TokenVersion,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, department, is_active, token_version,
       force_password_change, failed_login_attempts, locked_until,
       created_at, updated_at, deleted_at
FROM auth.users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Department,
		&i.IsActive,
		&i.TokenVersion,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :exec
UPDATE auth.users
SET failed_login_attempts = failed_login_attempts + 1,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementFailedLoginAttempts, id)
	return err
}

const incrementTokenVersion = `-- name: IncrementTokenVersion :one
UPDATE auth.users
SET token_version = token_version + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING token_version
`

func (q *Queries) IncrementTokenVersion(ctx context.Context, id pgtype.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, incrementTokenVersion, id)
	var token_version *int32
	err := row.Scan(&token_version)
	return token_version, err
}

const lockAccount = `-- name: LockAccount :exec
UPDATE auth.users
SET locked_until = $2,
    updated_at = NOW()
WHERE id = $1
`

type LockAccountParams struct {
	ID          pgtype.UUID      `json:"id"`
	LockedUntil pgtype.Timestamp `json:"locked_until"`
}

func (q *Queries) LockAccount(ctx context.Context, arg LockAccountParams) error {
	_, err := q.db.Exec(ctx, lockAccount, arg.ID, arg.LockedUntil)
	return err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE auth.users
SET failed_login_attempts = 0,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLoginAttempts, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE auth.users
SET password_hash = $2,
    force_password_change = $3,
    token_version = token_version + 1,
    updated_at = NOW()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID                  pgtype.UUID `json:"id"`
	PasswordHash        string      `json:"password_hash"`
	ForcePasswordChange *bool       `json:"force_password_change"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash, arg.ForcePasswordChange)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE auth.users
SET email = COALESCE($1, email),
    department = COALESCE($2, department),
    updated_at = NOW()
WHERE id = $3
`

type UpdateUserParams struct {
	Email      *string     `json:"email"`
	Department *string     `json:"department"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.Email, arg.Department, arg.ID)
	return err
}
