// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkAssignAdvisor = `-- name: BulkAssignAdvisor :exec
UPDATE students
SET advisor_id = $2, advisor_name = $3, updated_at = NOW()
WHERE id = ANY($1::UUID[]) AND is_active = true
`

type BulkAssignAdvisorParams struct {
	Column1     []pgtype.UUID `json:"column_1"`
	AdvisorID   pgtype.UUID   `json:"advisor_id"`
	AdvisorName pgtype.Text   `json:"advisor_name"`
}

func (q *Queries) BulkAssignAdvisor(ctx context.Context, arg BulkAssignAdvisorParams) error {
	_, err := q.db.Exec(ctx, bulkAssignAdvisor, arg.Column1, arg.AdvisorID, arg.AdvisorName)
	return err
}

const countOrphanedStudents = `-- name: CountOrphanedStudents :one
SELECT COUNT(*) FROM students WHERE (advisor_id IS NULL OR advisor_id = '00000000-0000-0000-0000-000000000000') AND is_active = true
`

func (q *Queries) CountOrphanedStudents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrphanedStudents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudents = `-- name: CountStudents :one
SELECT COUNT(*) FROM students WHERE is_active = true
`

func (q *Queries) CountStudents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStudents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (
    student_number, first_name, last_name, email, faculty, department,
    enrollment_year, class_level, advisor_id, advisor_name
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, student_number, first_name, last_name, email, faculty, department,
          enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
          created_at, updated_at
`

type CreateStudentParams struct {
	StudentNumber  string      `json:"student_number"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Email          string      `json:"email"`
	Faculty        string      `json:"faculty"`
	Department     string      `json:"department"`
	EnrollmentYear int32       `json:"enrollment_year"`
	ClassLevel     int16       `json:"class_level"`
	AdvisorID      pgtype.UUID `json:"advisor_id"`
	AdvisorName    pgtype.Text `json:"advisor_name"`
}

type CreateStudentRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (CreateStudentRow, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.StudentNumber,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Faculty,
		arg.Department,
		arg.EnrollmentYear,
		arg.ClassLevel,
		arg.AdvisorID,
		arg.AdvisorName,
	)
	var i CreateStudentRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Faculty,
		&i.Department,
		&i.EnrollmentYear,
		&i.ClassLevel,
		&i.AdvisorID,
		&i.AdvisorName,
		&i.Status,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByEmail = `-- name: GetStudentByEmail :one
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE email = $1 AND is_active = true
LIMIT 1
`

type GetStudentByEmailRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetStudentByEmail(ctx context.Context, email string) (GetStudentByEmailRow, error) {
	row := q.db.QueryRow(ctx, getStudentByEmail, email)
	var i GetStudentByEmailRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Faculty,
		&i.Department,
		&i.EnrollmentYear,
		&i.ClassLevel,
		&i.AdvisorID,
		&i.AdvisorName,
		&i.Status,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE id = $1 AND is_active = true
LIMIT 1
`

type GetStudentByIDRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (GetStudentByIDRow, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i GetStudentByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Faculty,
		&i.Department,
		&i.EnrollmentYear,
		&i.ClassLevel,
		&i.AdvisorID,
		&i.AdvisorName,
		&i.Status,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentByNumber = `-- name: GetStudentByNumber :one
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE student_number = $1 AND is_active = true
LIMIT 1
`

type GetStudentByNumberRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetStudentByNumber(ctx context.Context, studentNumber string) (GetStudentByNumberRow, error) {
	row := q.db.QueryRow(ctx, getStudentByNumber, studentNumber)
	var i GetStudentByNumberRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Faculty,
		&i.Department,
		&i.EnrollmentYear,
		&i.ClassLevel,
		&i.AdvisorID,
		&i.AdvisorName,
		&i.Status,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrphanedStudents = `-- name: ListOrphanedStudents :many
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE (advisor_id IS NULL OR advisor_id = '00000000-0000-0000-0000-000000000000') AND is_active = true
ORDER BY department ASC, class_level ASC, last_name ASC
LIMIT $1 OFFSET $2
`

type ListOrphanedStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListOrphanedStudentsRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListOrphanedStudents(ctx context.Context, arg ListOrphanedStudentsParams) ([]ListOrphanedStudentsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanedStudentsRow{}
	for rows.Next() {
		var i ListOrphanedStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Faculty,
			&i.Department,
			&i.EnrollmentYear,
			&i.ClassLevel,
			&i.AdvisorID,
			&i.AdvisorName,
			&i.Status,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE is_active = true
  AND ($1::TEXT IS NULL OR department = $1)
  AND ($2::SMALLINT IS NULL OR class_level = $2)
  AND ($3::TEXT IS NULL OR status = $3)
  AND ($4::UUID IS NULL OR advisor_id = $4)
ORDER BY
  CASE WHEN $5 = 'student_number' AND $6 = 'asc' THEN student_number END ASC,
  CASE WHEN $5 = 'student_number' AND $6 = 'desc' THEN student_number END DESC,
  CASE WHEN $5 = 'last_name' AND $6 = 'asc' THEN last_name END ASC,
  CASE WHEN $5 = 'last_name' AND $6 = 'desc' THEN last_name END DESC,
  CASE WHEN $5 = 'enrollment_year' AND $6 = 'asc' THEN enrollment_year END ASC,
  CASE WHEN $5 = 'enrollment_year' AND $6 = 'desc' THEN enrollment_year END DESC,
  CASE WHEN $5 = 'class_level' AND $6 = 'asc' THEN class_level END ASC,
  CASE WHEN $5 = 'class_level' AND $6 = 'desc' THEN class_level END DESC,
  CASE WHEN $5 = 'created_at' AND $6 = 'asc' THEN created_at END ASC,
  CASE WHEN $5 = 'created_at' AND $6 = 'desc' THEN created_at END DESC,
  created_at DESC
LIMIT $8 OFFSET $7
`

type ListStudentsParams struct {
	Department pgtype.Text `json:"department"`
	ClassLevel pgtype.Int2 `json:"class_level"`
	Status     pgtype.Text `json:"status"`
	AdvisorID  pgtype.UUID `json:"advisor_id"`
	SortBy     interface{} `json:"sort_by"`
	SortOrder  interface{} `json:"sort_order"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type ListStudentsRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListStudents(ctx context.Context, arg ListStudentsParams) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents,
		arg.Department,
		arg.ClassLevel,
		arg.Status,
		arg.AdvisorID,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsRow{}
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Faculty,
			&i.Department,
			&i.EnrollmentYear,
			&i.ClassLevel,
			&i.AdvisorID,
			&i.AdvisorName,
			&i.Status,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByAdvisor = `-- name: ListStudentsByAdvisor :many
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE advisor_id = $1 AND is_active = true AND status = 'active'
ORDER BY class_level ASC, last_name ASC
`

type ListStudentsByAdvisorRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListStudentsByAdvisor(ctx context.Context, advisorID pgtype.UUID) ([]ListStudentsByAdvisorRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByAdvisor, advisorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsByAdvisorRow{}
	for rows.Next() {
		var i ListStudentsByAdvisorRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Faculty,
			&i.Department,
			&i.EnrollmentYear,
			&i.ClassLevel,
			&i.AdvisorID,
			&i.AdvisorName,
			&i.Status,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByDepartment = `-- name: ListStudentsByDepartment :many
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE department = $1 AND is_active = true
ORDER BY class_level ASC, last_name ASC
`

type ListStudentsByDepartmentRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListStudentsByDepartment(ctx context.Context, department string) ([]ListStudentsByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByDepartment, department)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsByDepartmentRow{}
	for rows.Next() {
		var i ListStudentsByDepartmentRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Faculty,
			&i.Department,
			&i.EnrollmentYear,
			&i.ClassLevel,
			&i.AdvisorID,
			&i.AdvisorName,
			&i.Status,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchStudents = `-- name: SearchStudents :many
SELECT id, student_number, first_name, last_name, email, faculty, department,
       enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
       created_at, updated_at
FROM students
WHERE is_active = true
  AND ($1::TEXT IS NULL OR to_tsvector('english', first_name || ' ' || last_name || ' ' || student_number) @@ plainto_tsquery('english', $1))
  AND ($2::TEXT IS NULL OR department = $2)
  AND ($3::SMALLINT IS NULL OR class_level = $3)
  AND ($4::TEXT IS NULL OR status = $4)
  AND ($5::UUID IS NULL OR advisor_id = $5)
ORDER BY last_name ASC
LIMIT $7 OFFSET $6
`

type SearchStudentsParams struct {
	Query      pgtype.Text `json:"query"`
	Department pgtype.Text `json:"department"`
	ClassLevel pgtype.Int2 `json:"class_level"`
	Status     pgtype.Text `json:"status"`
	AdvisorID  pgtype.UUID `json:"advisor_id"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type SearchStudentsRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) SearchStudents(ctx context.Context, arg SearchStudentsParams) ([]SearchStudentsRow, error) {
	rows, err := q.db.Query(ctx, searchStudents,
		arg.Query,
		arg.Department,
		arg.ClassLevel,
		arg.Status,
		arg.AdvisorID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStudentsRow{}
	for rows.Next() {
		var i SearchStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Faculty,
			&i.Department,
			&i.EnrollmentYear,
			&i.ClassLevel,
			&i.AdvisorID,
			&i.AdvisorName,
			&i.Status,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStudent = `-- name: SoftDeleteStudent :exec
UPDATE students
SET is_active = false, deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteStudent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStudent, id)
	return err
}

const unassignAdvisorByStaffID = `-- name: UnassignAdvisorByStaffID :exec
UPDATE students
SET advisor_id = NULL, advisor_name = NULL, updated_at = NOW()
WHERE advisor_id = $1
`

func (q *Queries) UnassignAdvisorByStaffID(ctx context.Context, advisorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unassignAdvisorByStaffID, advisorID)
	return err
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    email = COALESCE($4, email),
    class_level = COALESCE($5, class_level),
    advisor_id = COALESCE($6, advisor_id),
    advisor_name = COALESCE($7, advisor_name),
    status = COALESCE($8, status),
    updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, student_number, first_name, last_name, email, faculty, department,
          enrollment_year, class_level, advisor_id, advisor_name, status, is_active, deleted_at,
          created_at, updated_at
`

type UpdateStudentParams struct {
	ID          pgtype.UUID `json:"id"`
	FirstName   pgtype.Text `json:"first_name"`
	LastName    pgtype.Text `json:"last_name"`
	Email       pgtype.Text `json:"email"`
	ClassLevel  int16       `json:"class_level"`
	AdvisorID   pgtype.UUID `json:"advisor_id"`
	AdvisorName pgtype.Text `json:"advisor_name"`
	Status      pgtype.Text `json:"status"`
}

type UpdateStudentRow struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	AdvisorName    pgtype.Text      `json:"advisor_name"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (UpdateStudentRow, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ClassLevel,
		arg.AdvisorID,
		arg.AdvisorName,
		arg.Status,
	)
	var i UpdateStudentRow
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Faculty,
		&i.Department,
		&i.EnrollmentYear,
		&i.ClassLevel,
		&i.AdvisorID,
		&i.AdvisorName,
		&i.Status,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
