// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldProcessedEvents = `-- name: CleanupOldProcessedEvents :exec
DELETE FROM processed_events
WHERE processed_at < NOW() - $1::interval
`

func (q *Queries) CleanupOldProcessedEvents(ctx context.Context, dollar_1 pgtype.Interval) error {
	_, err := q.db.Exec(ctx, cleanupOldProcessedEvents, dollar_1)
	return err
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(SELECT 1 FROM processed_events WHERE event_id = $1) AS exists
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO processed_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type MarkEventProcessedParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.EventID, arg.EventType)
	return err
}
