// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryLog struct {
	ID        pgtype.UUID        `json:"id"`
	EventID   string             `json:"event_id"`
	EventType string             `json:"event_type"`
	Channel   string             `json:"channel"`
	Recipient string             `json:"recipient"`
	Template  string             `json:"template"`
	Status    string             `json:"status"`
	Error     pgtype.Text        `json:"error"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProcessedEvent struct {
	EventID     string             `json:"event_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}
