// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryLog = `-- name: CreateDeliveryLog :one
INSERT INTO delivery_log (
    event_id, event_type, channel, recipient, template, status, error, sent_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, event_id, event_type, channel, recipient, template, status, error, sent_at, created_at
`

type CreateDeliveryLogParams struct {
	EventID   string             `json:"event_id"`
	EventType string             `json:"event_type"`
	Channel   string             `json:"channel"`
	Recipient string             `json:"recipient"`
	Template  string             `json:"template"`
	Status    string             `json:"status"`
	Error     pgtype.Text        `json:"error"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) CreateDeliveryLog(ctx context.Context, arg CreateDeliveryLogParams) (DeliveryLog, error) {
	row := q.db.QueryRow(ctx, createDeliveryLog,
		arg.EventID,
		arg.EventType,
		arg.Channel,
		arg.Recipient,
		arg.Template,
		arg.Status,
		arg.Error,
		arg.SentAt,
	)
	var i DeliveryLog
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.Channel,
		&i.Recipient,
		&i.Template,
		&i.Status,
		&i.Error,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryLogByEventID = `-- name: GetDeliveryLogByEventID :many
SELECT id, event_id, event_type, channel, recipient, template, status, error, sent_at, created_at FROM delivery_log
WHERE event_id = $1
`

func (q *Queries) GetDeliveryLogByEventID(ctx context.Context, eventID string) ([]DeliveryLog, error) {
	rows, err := q.db.Query(ctx, getDeliveryLogByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryLog
	for rows.Next() {
		var i DeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.Channel,
			&i.Recipient,
			&i.Template,
			&i.Status,
			&i.Error,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS (
    SELECT 1 FROM processed_events
    WHERE event_id = $1
)
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO processed_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type MarkEventProcessedParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.EventID, arg.EventType)
	return err
}

const updateDeliveryLogStatus = `-- name: UpdateDeliveryLogStatus :exec
UPDATE delivery_log
SET status = $2, error = $3, sent_at = $4
WHERE id = $1
`

type UpdateDeliveryLogStatusParams struct {
	ID     pgtype.UUID        `json:"id"`
	Status string             `json:"status"`
	Error  pgtype.Text        `json:"error"`
	SentAt pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) UpdateDeliveryLogStatus(ctx context.Context, arg UpdateDeliveryLogStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryLogStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.SentAt,
	)
	return err
}
