// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*)
FROM course_catalog
WHERE ($1::text IS NULL OR faculty = $1)
  AND ($2::text IS NULL OR department = $2)
  AND ($3::course_type_enum IS NULL OR course_type = $3)
  AND ($4::course_category_enum IS NULL OR course_category = $4)
  AND ($5::education_level_enum IS NULL OR education_level = $5)
  AND ($6::course_catalog_status_enum IS NULL OR status = $6)
  AND ($7::SMALLINT IS NULL OR class_level = $7)
  AND ($8::SMALLINT IS NULL OR semester = $8)
  AND ($9::text IS NULL OR language = $9)
  AND ($10::text IS NULL OR name ILIKE '%' || $10 || '%' OR course_code ILIKE '%' || $10 || '%')
`

type CountCoursesParams struct {
	Faculty        pgtype.Text                 `json:"faculty"`
	Department     pgtype.Text                 `json:"department"`
	CourseType     NullCourseTypeEnum          `json:"course_type"`
	CourseCategory NullCourseCategoryEnum      `json:"course_category"`
	EducationLevel NullEducationLevelEnum      `json:"education_level"`
	Status         NullCourseCatalogStatusEnum `json:"status"`
	ClassLevel     pgtype.Int2                 `json:"class_level"`
	Semester       pgtype.Int2                 `json:"semester"`
	Language       pgtype.Text                 `json:"language"`
	Search         pgtype.Text                 `json:"search"`
}

func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses,
		arg.Faculty,
		arg.Department,
		arg.CourseType,
		arg.CourseCategory,
		arg.EducationLevel,
		arg.Status,
		arg.ClassLevel,
		arg.Semester,
		arg.Language,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO course_catalog (
    course_code, name, faculty, department, offering_unit,
    class_level, semester, credits, ects, theoretical_hours, lab_hours,
    course_type, course_category, education_level, teaching_type, language,
    prerequisites, coordinator, purpose, description, learning_outcomes,
    learning_outcomes_list, weekly_topics, recommended_sources, syllabus, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)
RETURNING id, course_code, name, faculty, department, offering_unit,
          class_level, semester, credits, ects, theoretical_hours, lab_hours,
          course_type, course_category, education_level, teaching_type, language,
          prerequisites, coordinator, purpose, description, learning_outcomes,
          learning_outcomes_list, weekly_topics, recommended_sources, syllabus,
          status, created_at, updated_at
`

type CreateCourseParams struct {
	CourseCode           string                  `json:"course_code"`
	Name                 string                  `json:"name"`
	Faculty              string                  `json:"faculty"`
	Department           string                  `json:"department"`
	OfferingUnit         pgtype.Text             `json:"offering_unit"`
	ClassLevel           int16                   `json:"class_level"`
	Semester             pgtype.Int2             `json:"semester"`
	Credits              int16                   `json:"credits"`
	Ects                 pgtype.Int2             `json:"ects"`
	TheoreticalHours     int16                   `json:"theoretical_hours"`
	LabHours             int16                   `json:"lab_hours"`
	CourseType           CourseTypeEnum          `json:"course_type"`
	CourseCategory       CourseCategoryEnum      `json:"course_category"`
	EducationLevel       EducationLevelEnum      `json:"education_level"`
	TeachingType         TeachingTypeEnum        `json:"teaching_type"`
	Language             string                  `json:"language"`
	Prerequisites        []byte                  `json:"prerequisites"`
	Coordinator          []byte                  `json:"coordinator"`
	Purpose              pgtype.Text             `json:"purpose"`
	Description          pgtype.Text             `json:"description"`
	LearningOutcomes     pgtype.Text             `json:"learning_outcomes"`
	LearningOutcomesList []byte                  `json:"learning_outcomes_list"`
	WeeklyTopics         []byte                  `json:"weekly_topics"`
	RecommendedSources   []byte                  `json:"recommended_sources"`
	Syllabus             pgtype.Text             `json:"syllabus"`
	Status               CourseCatalogStatusEnum `json:"status"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.CourseCode,
		arg.Name,
		arg.Faculty,
		arg.Department,
		arg.OfferingUnit,
		arg.ClassLevel,
		arg.Semester,
		arg.Credits,
		arg.Ects,
		arg.TheoreticalHours,
		arg.LabHours,
		arg.CourseType,
		arg.CourseCategory,
		arg.EducationLevel,
		arg.TeachingType,
		arg.Language,
		arg.Prerequisites,
		arg.Coordinator,
		arg.Purpose,
		arg.Description,
		arg.LearningOutcomes,
		arg.LearningOutcomesList,
		arg.WeeklyTopics,
		arg.RecommendedSources,
		arg.Syllabus,
		arg.Status,
	)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.OfferingUnit,
		&i.ClassLevel,
		&i.Semester,
		&i.Credits,
		&i.Ects,
		&i.TheoreticalHours,
		&i.LabHours,
		&i.CourseType,
		&i.CourseCategory,
		&i.EducationLevel,
		&i.TeachingType,
		&i.Language,
		&i.Prerequisites,
		&i.Coordinator,
		&i.Purpose,
		&i.Description,
		&i.LearningOutcomes,
		&i.LearningOutcomesList,
		&i.WeeklyTopics,
		&i.RecommendedSources,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByCourseCode = `-- name: GetCourseByCourseCode :one
SELECT id, course_code, name, faculty, department, offering_unit,
       class_level, semester, credits, ects, theoretical_hours, lab_hours,
       course_type, course_category, education_level, teaching_type, language,
       prerequisites, coordinator, purpose, description, learning_outcomes,
       learning_outcomes_list, weekly_topics, recommended_sources, syllabus,
       status, created_at, updated_at
FROM course_catalog
WHERE course_code = $1
LIMIT 1
`

func (q *Queries) GetCourseByCourseCode(ctx context.Context, courseCode string) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, getCourseByCourseCode, courseCode)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.OfferingUnit,
		&i.ClassLevel,
		&i.Semester,
		&i.Credits,
		&i.Ects,
		&i.TheoreticalHours,
		&i.LabHours,
		&i.CourseType,
		&i.CourseCategory,
		&i.EducationLevel,
		&i.TeachingType,
		&i.Language,
		&i.Prerequisites,
		&i.Coordinator,
		&i.Purpose,
		&i.Description,
		&i.LearningOutcomes,
		&i.LearningOutcomesList,
		&i.WeeklyTopics,
		&i.RecommendedSources,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, course_code, name, faculty, department, offering_unit,
       class_level, semester, credits, ects, theoretical_hours, lab_hours,
       course_type, course_category, education_level, teaching_type, language,
       prerequisites, coordinator, purpose, description, learning_outcomes,
       learning_outcomes_list, weekly_topics, recommended_sources, syllabus,
       status, created_at, updated_at
FROM course_catalog
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.OfferingUnit,
		&i.ClassLevel,
		&i.Semester,
		&i.Credits,
		&i.Ects,
		&i.TheoreticalHours,
		&i.LabHours,
		&i.CourseType,
		&i.CourseCategory,
		&i.EducationLevel,
		&i.TeachingType,
		&i.Language,
		&i.Prerequisites,
		&i.Coordinator,
		&i.Purpose,
		&i.Description,
		&i.LearningOutcomes,
		&i.LearningOutcomesList,
		&i.WeeklyTopics,
		&i.RecommendedSources,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCoursesByIDs = `-- name: GetCoursesByIDs :many
SELECT id, course_code, name, class_level
FROM course_catalog
WHERE id = ANY($1::uuid[])
`

type GetCoursesByIDsRow struct {
	ID         pgtype.UUID `json:"id"`
	CourseCode string      `json:"course_code"`
	Name       string      `json:"name"`
	ClassLevel int16       `json:"class_level"`
}

func (q *Queries) GetCoursesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetCoursesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCoursesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursesByIDsRow{}
	for rows.Next() {
		var i GetCoursesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.Name,
			&i.ClassLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, course_code, name, faculty, department, offering_unit,
       class_level, semester, credits, ects, theoretical_hours, lab_hours,
       course_type, course_category, education_level, teaching_type, language,
       prerequisites, status
FROM course_catalog
WHERE ($1::text IS NULL OR faculty = $1)
  AND ($2::text IS NULL OR department = $2)
  AND ($3::course_type_enum IS NULL OR course_type = $3)
  AND ($4::course_category_enum IS NULL OR course_category = $4)
  AND ($5::education_level_enum IS NULL OR education_level = $5)
  AND ($6::course_catalog_status_enum IS NULL OR status = $6)
  AND ($7::SMALLINT IS NULL OR class_level = $7)
  AND ($8::SMALLINT IS NULL OR semester = $8)
  AND ($9::text IS NULL OR language = $9)
  AND ($10::text IS NULL OR name ILIKE '%' || $10 || '%' OR course_code ILIKE '%' || $10 || '%')
ORDER BY course_code
LIMIT $12 OFFSET $11
`

type ListCoursesParams struct {
	Faculty        pgtype.Text                 `json:"faculty"`
	Department     pgtype.Text                 `json:"department"`
	CourseType     NullCourseTypeEnum          `json:"course_type"`
	CourseCategory NullCourseCategoryEnum      `json:"course_category"`
	EducationLevel NullEducationLevelEnum      `json:"education_level"`
	Status         NullCourseCatalogStatusEnum `json:"status"`
	ClassLevel     pgtype.Int2                 `json:"class_level"`
	Semester       pgtype.Int2                 `json:"semester"`
	Language       pgtype.Text                 `json:"language"`
	Search         pgtype.Text                 `json:"search"`
	Offset         int32                       `json:"offset"`
	Limit          int32                       `json:"limit"`
}

type ListCoursesRow struct {
	ID               pgtype.UUID             `json:"id"`
	CourseCode       string                  `json:"course_code"`
	Name             string                  `json:"name"`
	Faculty          string                  `json:"faculty"`
	Department       string                  `json:"department"`
	OfferingUnit     pgtype.Text             `json:"offering_unit"`
	ClassLevel       int16                   `json:"class_level"`
	Semester         pgtype.Int2             `json:"semester"`
	Credits          int16                   `json:"credits"`
	Ects             pgtype.Int2             `json:"ects"`
	TheoreticalHours int16                   `json:"theoretical_hours"`
	LabHours         int16                   `json:"lab_hours"`
	CourseType       CourseTypeEnum          `json:"course_type"`
	CourseCategory   CourseCategoryEnum      `json:"course_category"`
	EducationLevel   EducationLevelEnum      `json:"education_level"`
	TeachingType     TeachingTypeEnum        `json:"teaching_type"`
	Language         string                  `json:"language"`
	Prerequisites    []byte                  `json:"prerequisites"`
	Status           CourseCatalogStatusEnum `json:"status"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]ListCoursesRow, error) {
	rows, err := q.db.Query(ctx, listCourses,
		arg.Faculty,
		arg.Department,
		arg.CourseType,
		arg.CourseCategory,
		arg.EducationLevel,
		arg.Status,
		arg.ClassLevel,
		arg.Semester,
		arg.Language,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesRow{}
	for rows.Next() {
		var i ListCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseCode,
			&i.Name,
			&i.Faculty,
			&i.Department,
			&i.OfferingUnit,
			&i.ClassLevel,
			&i.Semester,
			&i.Credits,
			&i.Ects,
			&i.TheoreticalHours,
			&i.LabHours,
			&i.CourseType,
			&i.CourseCategory,
			&i.EducationLevel,
			&i.TeachingType,
			&i.Language,
			&i.Prerequisites,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE course_catalog
SET name = COALESCE($2, name),
    faculty = COALESCE($3, faculty),
    department = COALESCE($4, department),
    offering_unit = COALESCE($5, offering_unit),
    class_level = COALESCE($6, class_level),
    semester = COALESCE($7, semester),
    credits = COALESCE($8, credits),
    ects = COALESCE($9, ects),
    theoretical_hours = COALESCE($10, theoretical_hours),
    lab_hours = COALESCE($11, lab_hours),
    course_type = COALESCE($12, course_type),
    course_category = COALESCE($13, course_category),
    education_level = COALESCE($14, education_level),
    teaching_type = COALESCE($15, teaching_type),
    language = COALESCE($16, language),
    prerequisites = COALESCE($17, prerequisites),
    coordinator = COALESCE($18, coordinator),
    purpose = COALESCE($19, purpose),
    description = COALESCE($20, description),
    learning_outcomes = COALESCE($21, learning_outcomes),
    learning_outcomes_list = COALESCE($22, learning_outcomes_list),
    weekly_topics = COALESCE($23, weekly_topics),
    recommended_sources = COALESCE($24, recommended_sources),
    syllabus = COALESCE($25, syllabus),
    status = COALESCE($26, status),
    updated_at = NOW()
WHERE course_code = $1
RETURNING id, course_code, name, faculty, department, offering_unit,
          class_level, semester, credits, ects, theoretical_hours, lab_hours,
          course_type, course_category, education_level, teaching_type, language,
          prerequisites, coordinator, purpose, description, learning_outcomes,
          learning_outcomes_list, weekly_topics, recommended_sources, syllabus,
          status, created_at, updated_at
`

type UpdateCourseParams struct {
	CourseCode           string                      `json:"course_code"`
	Name                 pgtype.Text                 `json:"name"`
	Faculty              pgtype.Text                 `json:"faculty"`
	Department           pgtype.Text                 `json:"department"`
	OfferingUnit         pgtype.Text                 `json:"offering_unit"`
	ClassLevel           pgtype.Int2                 `json:"class_level"`
	Semester             pgtype.Int2                 `json:"semester"`
	Credits              pgtype.Int2                 `json:"credits"`
	Ects                 pgtype.Int2                 `json:"ects"`
	TheoreticalHours     pgtype.Int2                 `json:"theoretical_hours"`
	LabHours             pgtype.Int2                 `json:"lab_hours"`
	CourseType           NullCourseTypeEnum          `json:"course_type"`
	CourseCategory       NullCourseCategoryEnum      `json:"course_category"`
	EducationLevel       NullEducationLevelEnum      `json:"education_level"`
	TeachingType         NullTeachingTypeEnum        `json:"teaching_type"`
	Language             pgtype.Text                 `json:"language"`
	Prerequisites        []byte                      `json:"prerequisites"`
	Coordinator          []byte                      `json:"coordinator"`
	Purpose              pgtype.Text                 `json:"purpose"`
	Description          pgtype.Text                 `json:"description"`
	LearningOutcomes     pgtype.Text                 `json:"learning_outcomes"`
	LearningOutcomesList []byte                      `json:"learning_outcomes_list"`
	WeeklyTopics         []byte                      `json:"weekly_topics"`
	RecommendedSources   []byte                      `json:"recommended_sources"`
	Syllabus             pgtype.Text                 `json:"syllabus"`
	Status               NullCourseCatalogStatusEnum `json:"status"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (CourseCatalog, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.CourseCode,
		arg.Name,
		arg.Faculty,
		arg.Department,
		arg.OfferingUnit,
		arg.ClassLevel,
		arg.Semester,
		arg.Credits,
		arg.Ects,
		arg.TheoreticalHours,
		arg.LabHours,
		arg.CourseType,
		arg.CourseCategory,
		arg.EducationLevel,
		arg.TeachingType,
		arg.Language,
		arg.Prerequisites,
		arg.Coordinator,
		arg.Purpose,
		arg.Description,
		arg.LearningOutcomes,
		arg.LearningOutcomesList,
		arg.WeeklyTopics,
		arg.RecommendedSources,
		arg.Syllabus,
		arg.Status,
	)
	var i CourseCatalog
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.OfferingUnit,
		&i.ClassLevel,
		&i.Semester,
		&i.Credits,
		&i.Ects,
		&i.TheoreticalHours,
		&i.LabHours,
		&i.CourseType,
		&i.CourseCategory,
		&i.EducationLevel,
		&i.TeachingType,
		&i.Language,
		&i.Prerequisites,
		&i.Coordinator,
		&i.Purpose,
		&i.Description,
		&i.LearningOutcomes,
		&i.LearningOutcomesList,
		&i.WeeklyTopics,
		&i.RecommendedSources,
		&i.Syllabus,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
