// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CourseCatalogStatusEnum string

const (
	CourseCatalogStatusEnumActive          CourseCatalogStatusEnum = "active"
	CourseCatalogStatusEnumDraft           CourseCatalogStatusEnum = "draft"
	CourseCatalogStatusEnumPendingApproval CourseCatalogStatusEnum = "pending_approval"
	CourseCatalogStatusEnumUnderRevision   CourseCatalogStatusEnum = "under_revision"
	CourseCatalogStatusEnumArchived        CourseCatalogStatusEnum = "archived"
	CourseCatalogStatusEnumSuspended       CourseCatalogStatusEnum = "suspended"
)

func (e *CourseCatalogStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseCatalogStatusEnum(s)
	case string:
		*e = CourseCatalogStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseCatalogStatusEnum: %T", src)
	}
	return nil
}

type NullCourseCatalogStatusEnum struct {
	CourseCatalogStatusEnum CourseCatalogStatusEnum `json:"course_catalog_status_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if CourseCatalogStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseCatalogStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CourseCatalogStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseCatalogStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseCatalogStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseCatalogStatusEnum), nil
}

type CourseCategoryEnum string

const (
	CourseCategoryEnumTheoretical CourseCategoryEnum = "theoretical"
	CourseCategoryEnumPractical   CourseCategoryEnum = "practical"
	CourseCategoryEnumInternship  CourseCategoryEnum = "internship"
	CourseCategoryEnumProject     CourseCategoryEnum = "project"
	CourseCategoryEnumSeminar     CourseCategoryEnum = "seminar"
)

func (e *CourseCategoryEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseCategoryEnum(s)
	case string:
		*e = CourseCategoryEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseCategoryEnum: %T", src)
	}
	return nil
}

type NullCourseCategoryEnum struct {
	CourseCategoryEnum CourseCategoryEnum `json:"course_category_enum"`
	Valid              bool               `json:"valid"` // Valid is true if CourseCategoryEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseCategoryEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CourseCategoryEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseCategoryEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseCategoryEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseCategoryEnum), nil
}

type CourseTypeEnum string

const (
	CourseTypeEnumMandatory CourseTypeEnum = "mandatory"
	CourseTypeEnumElective  CourseTypeEnum = "elective"
)

func (e *CourseTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseTypeEnum(s)
	case string:
		*e = CourseTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseTypeEnum: %T", src)
	}
	return nil
}

type NullCourseTypeEnum struct {
	CourseTypeEnum CourseTypeEnum `json:"course_type_enum"`
	Valid          bool           `json:"valid"` // Valid is true if CourseTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.CourseTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseTypeEnum), nil
}

type DayOfWeekEnum string

const (
	DayOfWeekEnumMonday    DayOfWeekEnum = "monday"
	DayOfWeekEnumTuesday   DayOfWeekEnum = "tuesday"
	DayOfWeekEnumWednesday DayOfWeekEnum = "wednesday"
	DayOfWeekEnumThursday  DayOfWeekEnum = "thursday"
	DayOfWeekEnumFriday    DayOfWeekEnum = "friday"
	DayOfWeekEnumSaturday  DayOfWeekEnum = "saturday"
	DayOfWeekEnumSunday    DayOfWeekEnum = "sunday"
)

func (e *DayOfWeekEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DayOfWeekEnum(s)
	case string:
		*e = DayOfWeekEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DayOfWeekEnum: %T", src)
	}
	return nil
}

type NullDayOfWeekEnum struct {
	DayOfWeekEnum DayOfWeekEnum `json:"day_of_week_enum"`
	Valid         bool          `json:"valid"` // Valid is true if DayOfWeekEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDayOfWeekEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DayOfWeekEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DayOfWeekEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDayOfWeekEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DayOfWeekEnum), nil
}

type EducationLevelEnum string

const (
	EducationLevelEnumUndergraduate EducationLevelEnum = "undergraduate"
	EducationLevelEnumGraduate      EducationLevelEnum = "graduate"
	EducationLevelEnumDoctorate     EducationLevelEnum = "doctorate"
)

func (e *EducationLevelEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EducationLevelEnum(s)
	case string:
		*e = EducationLevelEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EducationLevelEnum: %T", src)
	}
	return nil
}

type NullEducationLevelEnum struct {
	EducationLevelEnum EducationLevelEnum `json:"education_level_enum"`
	Valid              bool               `json:"valid"` // Valid is true if EducationLevelEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEducationLevelEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EducationLevelEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EducationLevelEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEducationLevelEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EducationLevelEnum), nil
}

type OutboxStatusEnum string

const (
	OutboxStatusEnumPending   OutboxStatusEnum = "pending"
	OutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	OutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type ScheduleSessionTypeEnum string

const (
	ScheduleSessionTypeEnumTheory ScheduleSessionTypeEnum = "theory"
	ScheduleSessionTypeEnumLab    ScheduleSessionTypeEnum = "lab"
)

func (e *ScheduleSessionTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleSessionTypeEnum(s)
	case string:
		*e = ScheduleSessionTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleSessionTypeEnum: %T", src)
	}
	return nil
}

type NullScheduleSessionTypeEnum struct {
	ScheduleSessionTypeEnum ScheduleSessionTypeEnum `json:"schedule_session_type_enum"`
	Valid                   bool                    `json:"valid"` // Valid is true if ScheduleSessionTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleSessionTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleSessionTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleSessionTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleSessionTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleSessionTypeEnum), nil
}

type SemesterStatus string

const (
	SemesterStatusPlanned   SemesterStatus = "planned"
	SemesterStatusActive    SemesterStatus = "active"
	SemesterStatusCompleted SemesterStatus = "completed"
)

func (e *SemesterStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SemesterStatus(s)
	case string:
		*e = SemesterStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SemesterStatus: %T", src)
	}
	return nil
}

type NullSemesterStatus struct {
	SemesterStatus SemesterStatus `json:"semester_status"`
	Valid          bool           `json:"valid"` // Valid is true if SemesterStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSemesterStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SemesterStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SemesterStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSemesterStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SemesterStatus), nil
}

type TeachingTypeEnum string

const (
	TeachingTypeEnumOnCampus TeachingTypeEnum = "on_campus"
	TeachingTypeEnumOnline   TeachingTypeEnum = "online"
	TeachingTypeEnumHybrid   TeachingTypeEnum = "hybrid"
)

func (e *TeachingTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeachingTypeEnum(s)
	case string:
		*e = TeachingTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TeachingTypeEnum: %T", src)
	}
	return nil
}

type NullTeachingTypeEnum struct {
	TeachingTypeEnum TeachingTypeEnum `json:"teaching_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if TeachingTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeachingTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TeachingTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeachingTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeachingTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeachingTypeEnum), nil
}

type AcademicPeriod struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	Service      string             `json:"service"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorRole    string             `json:"actor_role"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Details      []byte             `json:"details"`
}

type CourseCatalog struct {
	ID                   pgtype.UUID             `json:"id"`
	CourseCode           string                  `json:"course_code"`
	Name                 string                  `json:"name"`
	Faculty              string                  `json:"faculty"`
	Department           string                  `json:"department"`
	OfferingUnit         pgtype.Text             `json:"offering_unit"`
	ClassLevel           int16                   `json:"class_level"`
	Semester             pgtype.Int2             `json:"semester"`
	Credits              int16                   `json:"credits"`
	Ects                 pgtype.Int2             `json:"ects"`
	TheoreticalHours     int16                   `json:"theoretical_hours"`
	LabHours             int16                   `json:"lab_hours"`
	CourseType           CourseTypeEnum          `json:"course_type"`
	CourseCategory       CourseCategoryEnum      `json:"course_category"`
	EducationLevel       EducationLevelEnum      `json:"education_level"`
	TeachingType         TeachingTypeEnum        `json:"teaching_type"`
	Language             string                  `json:"language"`
	Prerequisites        []byte                  `json:"prerequisites"`
	Coordinator          []byte                  `json:"coordinator"`
	Purpose              pgtype.Text             `json:"purpose"`
	Description          pgtype.Text             `json:"description"`
	LearningOutcomes     pgtype.Text             `json:"learning_outcomes"`
	LearningOutcomesList []byte                  `json:"learning_outcomes_list"`
	WeeklyTopics         []byte                  `json:"weekly_topics"`
	RecommendedSources   []byte                  `json:"recommended_sources"`
	Syllabus             pgtype.Text             `json:"syllabus"`
	Status               CourseCatalogStatusEnum `json:"status"`
	CreatedAt            pgtype.Timestamp        `json:"created_at"`
	UpdatedAt            pgtype.Timestamp        `json:"updated_at"`
}

type CourseScheduleSession struct {
	ID               pgtype.UUID             `json:"id"`
	SemesterCourseID pgtype.UUID             `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum           `json:"day_of_week"`
	SlotNumber       int16                   `json:"slot_number"`
	CreatedAt        pgtype.Timestamp        `json:"created_at"`
	SessionType      ScheduleSessionTypeEnum `json:"session_type"`
}

type OutboxEvent struct {
	ID           pgtype.UUID          `json:"id"`
	EventType    string               `json:"event_type"`
	RoutingKey   string               `json:"routing_key"`
	Payload      []byte               `json:"payload"`
	Status       NullOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2          `json:"retry_count"`
	MaxRetries   pgtype.Int2          `json:"max_retries"`
	CreatedAt    pgtype.Timestamp     `json:"created_at"`
	ProcessedAt  pgtype.Timestamp     `json:"processed_at"`
	ErrorMessage pgtype.Text          `json:"error_message"`
}

type Semester struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Status       SemesterStatus     `json:"status"`
	HardDeadline pgtype.Timestamptz `json:"hard_deadline"`
	ActivatedAt  pgtype.Timestamptz `json:"activated_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SemesterCourse struct {
	ID                 pgtype.UUID      `json:"id"`
	Semester           string           `json:"semester"`
	CourseCode         string           `json:"course_code"`
	Credits            int16            `json:"credits"`
	ClassLevel         int16            `json:"class_level"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname string           `json:"instructor_fullname"`
	ClassroomLocation  string           `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	Prerequisites      []byte           `json:"prerequisites"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Department         string           `json:"department"`
}
