// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkInstructorScheduleConflict = `-- name: CheckInstructorScheduleConflict :many
SELECT sc.course_code, sc.id, cc.department, css.day_of_week, css.slot_number
FROM course_schedule_sessions css
JOIN semester_courses sc ON css.semester_course_id = sc.id
JOIN course_catalog cc ON cc.course_code = sc.course_code
WHERE (css.day_of_week, css.slot_number) IN (
    SELECT unnest($1::day_of_week_enum[]), unnest($2::SMALLINT[])
)
  AND sc.semester = $3
  AND sc.instructor_id = $4
  AND sc.id != $5
ORDER BY css.day_of_week, css.slot_number
`

type CheckInstructorScheduleConflictParams struct {
	Days            []DayOfWeekEnum `json:"days"`
	Slots           []int16         `json:"slots"`
	Semester        string          `json:"semester"`
	InstructorID    pgtype.UUID     `json:"instructor_id"`
	ExcludeCourseID pgtype.UUID     `json:"exclude_course_id"`
}

type CheckInstructorScheduleConflictRow struct {
	CourseCode string        `json:"course_code"`
	ID         pgtype.UUID   `json:"id"`
	Department string        `json:"department"`
	DayOfWeek  DayOfWeekEnum `json:"day_of_week"`
	SlotNumber int16         `json:"slot_number"`
}

func (q *Queries) CheckInstructorScheduleConflict(ctx context.Context, arg CheckInstructorScheduleConflictParams) ([]CheckInstructorScheduleConflictRow, error) {
	rows, err := q.db.Query(ctx, checkInstructorScheduleConflict,
		arg.Days,
		arg.Slots,
		arg.Semester,
		arg.InstructorID,
		arg.ExcludeCourseID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckInstructorScheduleConflictRow{}
	for rows.Next() {
		var i CheckInstructorScheduleConflictRow
		if err := rows.Scan(
			&i.CourseCode,
			&i.ID,
			&i.Department,
			&i.DayOfWeek,
			&i.SlotNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createScheduleSession = `-- name: CreateScheduleSession :one
INSERT INTO course_schedule_sessions (semester_course_id, day_of_week, slot_number, session_type)
VALUES ($1, $2, $3, $4)
RETURNING id, semester_course_id, day_of_week, slot_number, session_type, created_at
`

type CreateScheduleSessionParams struct {
	SemesterCourseID pgtype.UUID             `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum           `json:"day_of_week"`
	SlotNumber       int16                   `json:"slot_number"`
	SessionType      ScheduleSessionTypeEnum `json:"session_type"`
}

type CreateScheduleSessionRow struct {
	ID               pgtype.UUID             `json:"id"`
	SemesterCourseID pgtype.UUID             `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum           `json:"day_of_week"`
	SlotNumber       int16                   `json:"slot_number"`
	SessionType      ScheduleSessionTypeEnum `json:"session_type"`
	CreatedAt        pgtype.Timestamp        `json:"created_at"`
}

func (q *Queries) CreateScheduleSession(ctx context.Context, arg CreateScheduleSessionParams) (CreateScheduleSessionRow, error) {
	row := q.db.QueryRow(ctx, createScheduleSession,
		arg.SemesterCourseID,
		arg.DayOfWeek,
		arg.SlotNumber,
		arg.SessionType,
	)
	var i CreateScheduleSessionRow
	err := row.Scan(
		&i.ID,
		&i.SemesterCourseID,
		&i.DayOfWeek,
		&i.SlotNumber,
		&i.SessionType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteScheduleSessionsByCourseID = `-- name: DeleteScheduleSessionsByCourseID :exec
DELETE FROM course_schedule_sessions
WHERE semester_course_id = $1
`

func (q *Queries) DeleteScheduleSessionsByCourseID(ctx context.Context, semesterCourseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleSessionsByCourseID, semesterCourseID)
	return err
}

const getScheduleSessionsByCourseID = `-- name: GetScheduleSessionsByCourseID :many
SELECT id, semester_course_id, day_of_week, slot_number, session_type, created_at
FROM course_schedule_sessions
WHERE semester_course_id = $1
ORDER BY session_type, day_of_week, slot_number
`

type GetScheduleSessionsByCourseIDRow struct {
	ID               pgtype.UUID             `json:"id"`
	SemesterCourseID pgtype.UUID             `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum           `json:"day_of_week"`
	SlotNumber       int16                   `json:"slot_number"`
	SessionType      ScheduleSessionTypeEnum `json:"session_type"`
	CreatedAt        pgtype.Timestamp        `json:"created_at"`
}

func (q *Queries) GetScheduleSessionsByCourseID(ctx context.Context, semesterCourseID pgtype.UUID) ([]GetScheduleSessionsByCourseIDRow, error) {
	rows, err := q.db.Query(ctx, getScheduleSessionsByCourseID, semesterCourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScheduleSessionsByCourseIDRow{}
	for rows.Next() {
		var i GetScheduleSessionsByCourseIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SemesterCourseID,
			&i.DayOfWeek,
			&i.SlotNumber,
			&i.SessionType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduleSessionsByMultipleCourseIDs = `-- name: GetScheduleSessionsByMultipleCourseIDs :many
SELECT id, semester_course_id, day_of_week, slot_number, session_type, created_at
FROM course_schedule_sessions
WHERE semester_course_id = ANY($1::UUID[])
ORDER BY semester_course_id, session_type, day_of_week, slot_number
`

type GetScheduleSessionsByMultipleCourseIDsRow struct {
	ID               pgtype.UUID             `json:"id"`
	SemesterCourseID pgtype.UUID             `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum           `json:"day_of_week"`
	SlotNumber       int16                   `json:"slot_number"`
	SessionType      ScheduleSessionTypeEnum `json:"session_type"`
	CreatedAt        pgtype.Timestamp        `json:"created_at"`
}

func (q *Queries) GetScheduleSessionsByMultipleCourseIDs(ctx context.Context, courseIds []pgtype.UUID) ([]GetScheduleSessionsByMultipleCourseIDsRow, error) {
	rows, err := q.db.Query(ctx, getScheduleSessionsByMultipleCourseIDs, courseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScheduleSessionsByMultipleCourseIDsRow{}
	for rows.Next() {
		var i GetScheduleSessionsByMultipleCourseIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.SemesterCourseID,
			&i.DayOfWeek,
			&i.SlotNumber,
			&i.SessionType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
