// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: semesters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSemester = `-- name: ActivateSemester :one
UPDATE semesters SET status = 'active' WHERE id = $1 AND status = 'planned'
RETURNING id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at
`

func (q *Queries) ActivateSemester(ctx context.Context, id pgtype.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, activateSemester, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.HardDeadline,
		&i.ActivatedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const autoCompleteSemester = `-- name: AutoCompleteSemester :exec
UPDATE semesters SET status = 'completed'
WHERE name = $1 AND status = 'active' AND hard_deadline < NOW()
`

func (q *Queries) AutoCompleteSemester(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, autoCompleteSemester, name)
	return err
}

const completeSemester = `-- name: CompleteSemester :one
UPDATE semesters SET status = 'completed' WHERE id = $1 AND status = 'active'
RETURNING id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at
`

func (q *Queries) CompleteSemester(ctx context.Context, id pgtype.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, completeSemester, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.HardDeadline,
		&i.ActivatedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSemester = `-- name: CreateSemester :one
INSERT INTO semesters (name, hard_deadline)
VALUES ($1, $2)
RETURNING id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at
`

type CreateSemesterParams struct {
	Name         string             `json:"name"`
	HardDeadline pgtype.Timestamptz `json:"hard_deadline"`
}

func (q *Queries) CreateSemester(ctx context.Context, arg CreateSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, createSemester, arg.Name, arg.HardDeadline)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.HardDeadline,
		&i.ActivatedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlannedSemester = `-- name: DeletePlannedSemester :exec
DELETE FROM semesters WHERE id = $1 AND status = 'planned'
`

func (q *Queries) DeletePlannedSemester(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlannedSemester, id)
	return err
}

const deleteSemesterCoursesBySemester = `-- name: DeleteSemesterCoursesBySemester :exec
DELETE FROM semester_courses WHERE semester = $1
`

func (q *Queries) DeleteSemesterCoursesBySemester(ctx context.Context, semester string) error {
	_, err := q.db.Exec(ctx, deleteSemesterCoursesBySemester, semester)
	return err
}

const getActiveSemester = `-- name: GetActiveSemester :one
SELECT id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at FROM semesters WHERE status = 'active' LIMIT 1
`

func (q *Queries) GetActiveSemester(ctx context.Context) (Semester, error) {
	row := q.db.QueryRow(ctx, getActiveSemester)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.HardDeadline,
		&i.ActivatedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSemesterByID = `-- name: GetSemesterByID :one
SELECT id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at FROM semesters WHERE id = $1
`

func (q *Queries) GetSemesterByID(ctx context.Context, id pgtype.UUID) (Semester, error) {
	row := q.db.QueryRow(ctx, getSemesterByID, id)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.HardDeadline,
		&i.ActivatedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSemesterByName = `-- name: GetSemesterByName :one
SELECT id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at FROM semesters WHERE name = $1
`

func (q *Queries) GetSemesterByName(ctx context.Context, name string) (Semester, error) {
	row := q.db.QueryRow(ctx, getSemesterByName, name)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.HardDeadline,
		&i.ActivatedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveSemester = `-- name: HasActiveSemester :one
SELECT EXISTS(SELECT 1 FROM semesters WHERE status = 'active') AS has_active
`

// INVARIANT: Only one semester can be active at any given time.
// Used before activation to give a clear error message at the application layer.
// The database also enforces this via idx_semesters_single_active partial unique index.
func (q *Queries) HasActiveSemester(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSemester)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const listSemesters = `-- name: ListSemesters :many
SELECT id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at FROM semesters ORDER BY created_at DESC
`

func (q *Queries) ListSemesters(ctx context.Context) ([]Semester, error) {
	rows, err := q.db.Query(ctx, listSemesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Semester{}
	for rows.Next() {
		var i Semester
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.HardDeadline,
			&i.ActivatedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlannedSemester = `-- name: UpdatePlannedSemester :one
UPDATE semesters
SET hard_deadline = $2, updated_at = NOW()
WHERE id = $1 AND status = 'planned'
RETURNING id, name, status, hard_deadline, activated_at, completed_at, created_at, updated_at
`

type UpdatePlannedSemesterParams struct {
	ID           pgtype.UUID        `json:"id"`
	HardDeadline pgtype.Timestamptz `json:"hard_deadline"`
}

func (q *Queries) UpdatePlannedSemester(ctx context.Context, arg UpdatePlannedSemesterParams) (Semester, error) {
	row := q.db.QueryRow(ctx, updatePlannedSemester, arg.ID, arg.HardDeadline)
	var i Semester
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.HardDeadline,
		&i.ActivatedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
