// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ImportJobStatus string

const (
	ImportJobStatusPending    ImportJobStatus = "pending"
	ImportJobStatusProcessing ImportJobStatus = "processing"
	ImportJobStatusCompleted  ImportJobStatus = "completed"
	ImportJobStatusFailed     ImportJobStatus = "failed"
)

func (e *ImportJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportJobStatus(s)
	case string:
		*e = ImportJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportJobStatus: %T", src)
	}
	return nil
}

type NullImportJobStatus struct {
	ImportJobStatus ImportJobStatus `json:"import_job_status"`
	Valid           bool            `json:"valid"` // Valid is true if ImportJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportJobStatus), nil
}

type OutboxStatusEnum string

const (
	OutboxStatusEnumPending   OutboxStatusEnum = "pending"
	OutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	OutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type ImportJob struct {
	ID                pgtype.UUID         `json:"id"`
	FileName          string              `json:"file_name"`
	TotalRecords      int32               `json:"total_records"`
	ProcessedRecords  int32               `json:"processed_records"`
	SuccessfulRecords int32               `json:"successful_records"`
	FailedRecords     int32               `json:"failed_records"`
	Status            NullImportJobStatus `json:"status"`
	Errors            []byte              `json:"errors"`
	CreatedBy         pgtype.UUID         `json:"created_by"`
	StartedAt         pgtype.Timestamp    `json:"started_at"`
	CompletedAt       pgtype.Timestamp    `json:"completed_at"`
	CreatedAt         pgtype.Timestamp    `json:"created_at"`
}

type OutboxEvent struct {
	ID           pgtype.UUID          `json:"id"`
	EventType    string               `json:"event_type"`
	RoutingKey   string               `json:"routing_key"`
	Payload      []byte               `json:"payload"`
	Status       NullOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2          `json:"retry_count"`
	MaxRetries   pgtype.Int2          `json:"max_retries"`
	CreatedAt    pgtype.Timestamp     `json:"created_at"`
	ProcessedAt  pgtype.Timestamp     `json:"processed_at"`
	ErrorMessage pgtype.Text          `json:"error_message"`
}

type ProcessedEvent struct {
	EventID     string           `json:"event_id"`
	EventType   string           `json:"event_type"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type Student struct {
	ID             pgtype.UUID      `json:"id"`
	StudentNumber  string           `json:"student_number"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Faculty        string           `json:"faculty"`
	Department     string           `json:"department"`
	EnrollmentYear int32            `json:"enrollment_year"`
	ClassLevel     int16            `json:"class_level"`
	AdvisorID      pgtype.UUID      `json:"advisor_id"`
	Status         pgtype.Text      `json:"status"`
	IsActive       pgtype.Bool      `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
