// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package db

import (
	"context"
)

const createProcessedEvent = `-- name: CreateProcessedEvent :exec
INSERT INTO processed_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type CreateProcessedEventParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) error {
	_, err := q.db.Exec(ctx, createProcessedEvent, arg.EventID, arg.EventType)
	return err
}

const deleteOldProcessedEvents = `-- name: DeleteOldProcessedEvents :exec
DELETE FROM processed_events WHERE processed_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldProcessedEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldProcessedEvents)
	return err
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(SELECT 1 FROM processed_events WHERE event_id = $1)
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
