// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*) FROM course_catalog.audit_log
WHERE
    ($1::VARCHAR IS NULL OR service = $1) AND
    ($2::VARCHAR IS NULL OR action = $2) AND
    ($3::UUID IS NULL OR actor_id = $3)
`

type CountAuditLogParams struct {
	Service pgtype.Text `json:"service"`
	Action  pgtype.Text `json:"action"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) CountAuditLog(ctx context.Context, arg CountAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLog, arg.Service, arg.Action, arg.ActorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO course_catalog.audit_log (service, actor_id, actor_role, action, resource_type, resource_id, details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, timestamp, service, actor_id, actor_role, action, resource_type, resource_id, details
`

type InsertAuditLogParams struct {
	Service      string      `json:"service"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ActorRole    string      `json:"actor_role"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Details      []byte      `json:"details"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.Service,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.Service,
		&i.ActorID,
		&i.ActorRole,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, timestamp, service, actor_id, actor_role, action, resource_type, resource_id, details FROM course_catalog.audit_log
WHERE
    ($3::VARCHAR IS NULL OR service = $3) AND
    ($4::VARCHAR IS NULL OR action = $4) AND
    ($5::UUID IS NULL OR actor_id = $5)
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Service pgtype.Text `json:"service"`
	Action  pgtype.Text `json:"action"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Limit,
		arg.Offset,
		arg.Service,
		arg.Action,
		arg.ActorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Service,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
