// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchCreateScheduleSessions = `-- name: BatchCreateScheduleSessions :batchexec
INSERT INTO course_catalog.course_schedule_sessions (semester_course_id, day_of_week, slot_number, session_type)
VALUES ($1, $2, $3, $4)
`

type BatchCreateScheduleSessionsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchCreateScheduleSessionsParams struct {
	SemesterCourseID pgtype.UUID             `json:"semester_course_id"`
	DayOfWeek        DayOfWeekEnum           `json:"day_of_week"`
	SlotNumber       int16                   `json:"slot_number"`
	SessionType      ScheduleSessionTypeEnum `json:"session_type"`
}

func (q *Queries) BatchCreateScheduleSessions(ctx context.Context, arg []BatchCreateScheduleSessionsParams) *BatchCreateScheduleSessionsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.SemesterCourseID,
			a.DayOfWeek,
			a.SlotNumber,
			a.SessionType,
		}
		batch.Queue(batchCreateScheduleSessions, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchCreateScheduleSessionsBatchResults{br, len(arg), false}
}

func (b *BatchCreateScheduleSessionsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchCreateScheduleSessionsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
