// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: semester.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSemesterCourses = `-- name: CountSemesterCourses :one
SELECT COUNT(*)
FROM course_catalog.semester_courses sc
JOIN course_catalog.course_catalog cc ON sc.course_code = cc.course_code
WHERE sc.semester = $1
  AND ($2::text IS NULL OR cc.faculty = $2)
  AND ($3::text IS NULL OR cc.department = $3)
  AND ($4::uuid IS NULL OR sc.instructor_id = $4)
  AND ($5::course_catalog.course_type_enum IS NULL OR cc.course_type = $5)
  AND ($6::SMALLINT IS NULL OR sc.class_level = $6)
`

type CountSemesterCoursesParams struct {
	Semester     string             `json:"semester"`
	Faculty      pgtype.Text        `json:"faculty"`
	Department   pgtype.Text        `json:"department"`
	InstructorID pgtype.UUID        `json:"instructor_id"`
	CourseType   NullCourseTypeEnum `json:"course_type"`
	ClassLevel   pgtype.Int2        `json:"class_level"`
}

func (q *Queries) CountSemesterCourses(ctx context.Context, arg CountSemesterCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSemesterCourses,
		arg.Semester,
		arg.Faculty,
		arg.Department,
		arg.InstructorID,
		arg.CourseType,
		arg.ClassLevel,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSemesterCourse = `-- name: CreateSemesterCourse :one
INSERT INTO course_catalog.semester_courses (
    semester, course_code, department, credits, class_level, instructor_id,
    instructor_fullname, classroom_location, max_capacity, assessment_schema, prerequisites
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, semester, course_code, department, credits, class_level, instructor_id,
          instructor_fullname, classroom_location, max_capacity, assessment_schema, prerequisites,
          created_at, updated_at
`

type CreateSemesterCourseParams struct {
	Semester           string      `json:"semester"`
	CourseCode         string      `json:"course_code"`
	Department         string      `json:"department"`
	Credits            int16       `json:"credits"`
	ClassLevel         int16       `json:"class_level"`
	InstructorID       pgtype.UUID `json:"instructor_id"`
	InstructorFullname string      `json:"instructor_fullname"`
	ClassroomLocation  string      `json:"classroom_location"`
	MaxCapacity        int16       `json:"max_capacity"`
	AssessmentSchema   []byte      `json:"assessment_schema"`
	Prerequisites      []byte      `json:"prerequisites"`
}

type CreateSemesterCourseRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Semester           string           `json:"semester"`
	CourseCode         string           `json:"course_code"`
	Department         string           `json:"department"`
	Credits            int16            `json:"credits"`
	ClassLevel         int16            `json:"class_level"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname string           `json:"instructor_fullname"`
	ClassroomLocation  string           `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	Prerequisites      []byte           `json:"prerequisites"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateSemesterCourse(ctx context.Context, arg CreateSemesterCourseParams) (CreateSemesterCourseRow, error) {
	row := q.db.QueryRow(ctx, createSemesterCourse,
		arg.Semester,
		arg.CourseCode,
		arg.Department,
		arg.Credits,
		arg.ClassLevel,
		arg.InstructorID,
		arg.InstructorFullname,
		arg.ClassroomLocation,
		arg.MaxCapacity,
		arg.AssessmentSchema,
		arg.Prerequisites,
	)
	var i CreateSemesterCourseRow
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseCode,
		&i.Department,
		&i.Credits,
		&i.ClassLevel,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.ClassroomLocation,
		&i.MaxCapacity,
		&i.AssessmentSchema,
		&i.Prerequisites,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSemesterCourse = `-- name: DeleteSemesterCourse :exec
DELETE FROM course_catalog.semester_courses
WHERE id = $1
`

func (q *Queries) DeleteSemesterCourse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSemesterCourse, id)
	return err
}

const getSemesterCourseByID = `-- name: GetSemesterCourseByID :one
SELECT id, semester, course_code, department, credits, class_level, instructor_id,
       instructor_fullname, classroom_location, max_capacity, assessment_schema, prerequisites,
       created_at, updated_at
FROM course_catalog.semester_courses
WHERE id = $1 AND semester = $2
LIMIT 1
`

type GetSemesterCourseByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	Semester string      `json:"semester"`
}

type GetSemesterCourseByIDRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Semester           string           `json:"semester"`
	CourseCode         string           `json:"course_code"`
	Department         string           `json:"department"`
	Credits            int16            `json:"credits"`
	ClassLevel         int16            `json:"class_level"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname string           `json:"instructor_fullname"`
	ClassroomLocation  string           `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	Prerequisites      []byte           `json:"prerequisites"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetSemesterCourseByID(ctx context.Context, arg GetSemesterCourseByIDParams) (GetSemesterCourseByIDRow, error) {
	row := q.db.QueryRow(ctx, getSemesterCourseByID, arg.ID, arg.Semester)
	var i GetSemesterCourseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseCode,
		&i.Department,
		&i.Credits,
		&i.ClassLevel,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.ClassroomLocation,
		&i.MaxCapacity,
		&i.AssessmentSchema,
		&i.Prerequisites,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSemesterCourseBySemesterAndCode = `-- name: GetSemesterCourseBySemesterAndCode :one
SELECT id, semester, course_code, department, credits, class_level, instructor_id,
       instructor_fullname, classroom_location, max_capacity, assessment_schema, prerequisites,
       created_at, updated_at
FROM course_catalog.semester_courses
WHERE semester = $1 AND course_code = $2
LIMIT 1
`

type GetSemesterCourseBySemesterAndCodeParams struct {
	Semester   string `json:"semester"`
	CourseCode string `json:"course_code"`
}

type GetSemesterCourseBySemesterAndCodeRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Semester           string           `json:"semester"`
	CourseCode         string           `json:"course_code"`
	Department         string           `json:"department"`
	Credits            int16            `json:"credits"`
	ClassLevel         int16            `json:"class_level"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname string           `json:"instructor_fullname"`
	ClassroomLocation  string           `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	Prerequisites      []byte           `json:"prerequisites"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetSemesterCourseBySemesterAndCode(ctx context.Context, arg GetSemesterCourseBySemesterAndCodeParams) (GetSemesterCourseBySemesterAndCodeRow, error) {
	row := q.db.QueryRow(ctx, getSemesterCourseBySemesterAndCode, arg.Semester, arg.CourseCode)
	var i GetSemesterCourseBySemesterAndCodeRow
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseCode,
		&i.Department,
		&i.Credits,
		&i.ClassLevel,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.ClassroomLocation,
		&i.MaxCapacity,
		&i.AssessmentSchema,
		&i.Prerequisites,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacherCourses = `-- name: GetTeacherCourses :many
SELECT
    sc.id,
    sc.semester,
    sc.course_code,
    cc.name as course_name,
    cc.faculty,
    cc.department,
    sc.credits,
    sc.class_level,
    sc.instructor_id,
    sc.instructor_fullname,
    sc.classroom_location,
    sc.max_capacity,
    cc.theoretical_hours,
    cc.lab_hours,
    sc.created_at
FROM course_catalog.semester_courses sc
JOIN course_catalog.course_catalog cc ON sc.course_code = cc.course_code
WHERE sc.instructor_id = $1
  AND ($2::text IS NULL OR sc.semester = $2)
ORDER BY sc.semester DESC, sc.course_code ASC
`

type GetTeacherCoursesParams struct {
	InstructorID pgtype.UUID `json:"instructor_id"`
	Semester     pgtype.Text `json:"semester"`
}

type GetTeacherCoursesRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Semester           string           `json:"semester"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	Faculty            string           `json:"faculty"`
	Department         string           `json:"department"`
	Credits            int16            `json:"credits"`
	ClassLevel         int16            `json:"class_level"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname string           `json:"instructor_fullname"`
	ClassroomLocation  string           `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	TheoreticalHours   int16            `json:"theoretical_hours"`
	LabHours           int16            `json:"lab_hours"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetTeacherCourses(ctx context.Context, arg GetTeacherCoursesParams) ([]GetTeacherCoursesRow, error) {
	rows, err := q.db.Query(ctx, getTeacherCourses, arg.InstructorID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTeacherCoursesRow{}
	for rows.Next() {
		var i GetTeacherCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Semester,
			&i.CourseCode,
			&i.CourseName,
			&i.Faculty,
			&i.Department,
			&i.Credits,
			&i.ClassLevel,
			&i.InstructorID,
			&i.InstructorFullname,
			&i.ClassroomLocation,
			&i.MaxCapacity,
			&i.TheoreticalHours,
			&i.LabHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemesterCourses = `-- name: ListSemesterCourses :many
SELECT sc.id, sc.semester, sc.course_code, sc.department, cc.name as course_name, sc.credits, sc.class_level,
       sc.instructor_id, sc.instructor_fullname, sc.classroom_location, sc.max_capacity,
       sc.assessment_schema
FROM course_catalog.semester_courses sc
JOIN course_catalog.course_catalog cc ON sc.course_code = cc.course_code
WHERE sc.semester = $1
  AND ($2::text IS NULL OR cc.faculty = $2)
  AND ($3::text IS NULL OR cc.department = $3)
  AND ($4::uuid IS NULL OR sc.instructor_id = $4)
  AND ($5::course_catalog.course_type_enum IS NULL OR cc.course_type = $5)
  AND ($6::SMALLINT IS NULL OR sc.class_level = $6)
ORDER BY sc.course_code
LIMIT $8 OFFSET $7
`

type ListSemesterCoursesParams struct {
	Semester     string             `json:"semester"`
	Faculty      pgtype.Text        `json:"faculty"`
	Department   pgtype.Text        `json:"department"`
	InstructorID pgtype.UUID        `json:"instructor_id"`
	CourseType   NullCourseTypeEnum `json:"course_type"`
	ClassLevel   pgtype.Int2        `json:"class_level"`
	Offset       int32              `json:"offset"`
	Limit        int32              `json:"limit"`
}

type ListSemesterCoursesRow struct {
	ID                 pgtype.UUID `json:"id"`
	Semester           string      `json:"semester"`
	CourseCode         string      `json:"course_code"`
	Department         string      `json:"department"`
	CourseName         string      `json:"course_name"`
	Credits            int16       `json:"credits"`
	ClassLevel         int16       `json:"class_level"`
	InstructorID       pgtype.UUID `json:"instructor_id"`
	InstructorFullname string      `json:"instructor_fullname"`
	ClassroomLocation  string      `json:"classroom_location"`
	MaxCapacity        int16       `json:"max_capacity"`
	AssessmentSchema   []byte      `json:"assessment_schema"`
}

func (q *Queries) ListSemesterCourses(ctx context.Context, arg ListSemesterCoursesParams) ([]ListSemesterCoursesRow, error) {
	rows, err := q.db.Query(ctx, listSemesterCourses,
		arg.Semester,
		arg.Faculty,
		arg.Department,
		arg.InstructorID,
		arg.CourseType,
		arg.ClassLevel,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSemesterCoursesRow{}
	for rows.Next() {
		var i ListSemesterCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Semester,
			&i.CourseCode,
			&i.Department,
			&i.CourseName,
			&i.Credits,
			&i.ClassLevel,
			&i.InstructorID,
			&i.InstructorFullname,
			&i.ClassroomLocation,
			&i.MaxCapacity,
			&i.AssessmentSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemesterCoursesForActivation = `-- name: ListSemesterCoursesForActivation :many
SELECT
    sc.id, sc.semester, sc.course_code, sc.credits, sc.class_level, sc.instructor_id, sc.instructor_fullname, sc.classroom_location, sc.max_capacity, sc.prerequisites, sc.assessment_schema, sc.created_at, sc.updated_at, sc.department,
    cc.name AS course_name,
    cc.faculty,
    cc.course_type,
    json_agg(json_build_object(
        'day_of_week', css.day_of_week,
        'slot_number', css.slot_number,
        'session_type', css.session_type
    )) AS schedule_sessions
FROM course_catalog.semester_courses sc
JOIN course_catalog.course_catalog cc ON cc.course_code = sc.course_code
LEFT JOIN course_catalog.course_schedule_sessions css ON css.semester_course_id = sc.id
WHERE sc.semester = $1
GROUP BY sc.id, cc.name, cc.faculty, cc.course_type
`

type ListSemesterCoursesForActivationRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Semester           string           `json:"semester"`
	CourseCode         string           `json:"course_code"`
	Credits            int16            `json:"credits"`
	ClassLevel         int16            `json:"class_level"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname string           `json:"instructor_fullname"`
	ClassroomLocation  string           `json:"classroom_location"`
	MaxCapacity        int16            `json:"max_capacity"`
	Prerequisites      []byte           `json:"prerequisites"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Department         string           `json:"department"`
	CourseName         string           `json:"course_name"`
	Faculty            string           `json:"faculty"`
	CourseType         CourseTypeEnum   `json:"course_type"`
	ScheduleSessions   []byte           `json:"schedule_sessions"`
}

func (q *Queries) ListSemesterCoursesForActivation(ctx context.Context, semester string) ([]ListSemesterCoursesForActivationRow, error) {
	rows, err := q.db.Query(ctx, listSemesterCoursesForActivation, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSemesterCoursesForActivationRow{}
	for rows.Next() {
		var i ListSemesterCoursesForActivationRow
		if err := rows.Scan(
			&i.ID,
			&i.Semester,
			&i.CourseCode,
			&i.Credits,
			&i.ClassLevel,
			&i.InstructorID,
			&i.InstructorFullname,
			&i.ClassroomLocation,
			&i.MaxCapacity,
			&i.Prerequisites,
			&i.AssessmentSchema,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Department,
			&i.CourseName,
			&i.Faculty,
			&i.CourseType,
			&i.ScheduleSessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
