# RabbitMQ Configuration
#
# Documentation: https://www.rabbitmq.com/docs/configure
#
# This configuration file is mounted to /etc/rabbitmq/rabbitmq.conf

# Networking
listeners.tcp.default = 5672

# Management Plugin
management.tcp.port = 15672
# management.load_definitions = /etc/rabbitmq/definitions.json

# Memory
vm_memory_high_watermark.relative = 0.6

# Disk Space
disk_free_limit.absolute = 2GB

# Message TTL (optional)
# Default message time-to-live for queues (24 hours)
# default_vhost.default_queue_type = quorum

# Heartbeat
heartbeat = 60

# Logging
log.file.level = info
log.console = true
log.console.level = info
