// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkSessionExists = `-- name: CheckSessionExists :one
SELECT COUNT(*) as count
FROM attendance.attendance_sessions
WHERE course_id = $1 AND week_number = $2 AND session_type = $3
`

type CheckSessionExistsParams struct {
	CourseID    pgtype.UUID               `json:"course_id"`
	WeekNumber  int16                     `json:"week_number"`
	SessionType AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) CheckSessionExists(ctx context.Context, arg CheckSessionExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkSessionExists, arg.CourseID, arg.WeekNumber, arg.SessionType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttendanceSession = `-- name: CreateAttendanceSession :one
INSERT INTO attendance.attendance_sessions (
    course_id, instructor_id, semester, week_number, session_date,
    qr_secret, qr_rotation_interval, started_at, expires_at, is_active, session_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, TRUE, $10
) RETURNING id, course_id, instructor_id, semester, week_number, session_date, session_type, qr_secret, qr_rotation_interval, started_at, expires_at, is_active, created_at
`

type CreateAttendanceSessionParams struct {
	CourseID           pgtype.UUID               `json:"course_id"`
	InstructorID       pgtype.UUID               `json:"instructor_id"`
	Semester           string                    `json:"semester"`
	WeekNumber         int16                     `json:"week_number"`
	SessionDate        pgtype.Date               `json:"session_date"`
	QrSecret           string                    `json:"qr_secret"`
	QrRotationInterval pgtype.Int2               `json:"qr_rotation_interval"`
	StartedAt          pgtype.Timestamp          `json:"started_at"`
	ExpiresAt          pgtype.Timestamp          `json:"expires_at"`
	SessionType        AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) CreateAttendanceSession(ctx context.Context, arg CreateAttendanceSessionParams) (AttendanceAttendanceSession, error) {
	row := q.db.QueryRow(ctx, createAttendanceSession,
		arg.CourseID,
		arg.InstructorID,
		arg.Semester,
		arg.WeekNumber,
		arg.SessionDate,
		arg.QrSecret,
		arg.QrRotationInterval,
		arg.StartedAt,
		arg.ExpiresAt,
		arg.SessionType,
	)
	var i AttendanceAttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Semester,
		&i.WeekNumber,
		&i.SessionDate,
		&i.SessionType,
		&i.QrSecret,
		&i.QrRotationInterval,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateSession = `-- name: DeactivateSession :exec
UPDATE attendance.attendance_sessions
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateSession, id)
	return err
}

const getActiveSessionByID = `-- name: GetActiveSessionByID :one
SELECT id, course_id, instructor_id, semester, week_number, session_date, session_type, qr_secret, qr_rotation_interval, started_at, expires_at, is_active, created_at FROM attendance.attendance_sessions
WHERE id = $1 AND is_active = TRUE AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveSessionByID(ctx context.Context, id pgtype.UUID) (AttendanceAttendanceSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByID, id)
	var i AttendanceAttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Semester,
		&i.WeekNumber,
		&i.SessionDate,
		&i.SessionType,
		&i.QrSecret,
		&i.QrRotationInterval,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getExpiredSessions = `-- name: GetExpiredSessions :many
SELECT id, course_id, instructor_id, semester, week_number, session_date, session_type, qr_secret, qr_rotation_interval, started_at, expires_at, is_active, created_at FROM attendance.attendance_sessions
WHERE is_active = TRUE AND expires_at < NOW()
`

func (q *Queries) GetExpiredSessions(ctx context.Context) ([]AttendanceAttendanceSession, error) {
	rows, err := q.db.Query(ctx, getExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceAttendanceSession{}
	for rows.Next() {
		var i AttendanceAttendanceSession
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.InstructorID,
			&i.Semester,
			&i.WeekNumber,
			&i.SessionDate,
			&i.SessionType,
			&i.QrSecret,
			&i.QrRotationInterval,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, course_id, instructor_id, semester, week_number, session_date, session_type, qr_secret, qr_rotation_interval, started_at, expires_at, is_active, created_at FROM attendance.attendance_sessions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (AttendanceAttendanceSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i AttendanceAttendanceSession
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.InstructorID,
		&i.Semester,
		&i.WeekNumber,
		&i.SessionDate,
		&i.SessionType,
		&i.QrSecret,
		&i.QrRotationInterval,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionsByCourse = `-- name: GetSessionsByCourse :many
SELECT
    id,
    week_number,
    session_date,
    is_active,
    started_at,
    expires_at,
    session_type
FROM attendance.attendance_sessions
WHERE course_id = $1 AND semester = $2
ORDER BY week_number ASC, session_type ASC
`

type GetSessionsByCourseParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Semester string      `json:"semester"`
}

type GetSessionsByCourseRow struct {
	ID          pgtype.UUID               `json:"id"`
	WeekNumber  int16                     `json:"week_number"`
	SessionDate pgtype.Date               `json:"session_date"`
	IsActive    pgtype.Bool               `json:"is_active"`
	StartedAt   pgtype.Timestamp          `json:"started_at"`
	ExpiresAt   pgtype.Timestamp          `json:"expires_at"`
	SessionType AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) GetSessionsByCourse(ctx context.Context, arg GetSessionsByCourseParams) ([]GetSessionsByCourseRow, error) {
	rows, err := q.db.Query(ctx, getSessionsByCourse, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionsByCourseRow{}
	for rows.Next() {
		var i GetSessionsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.WeekNumber,
			&i.SessionDate,
			&i.IsActive,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.SessionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsByDateRange = `-- name: GetSessionsByDateRange :many
SELECT
    s.id,
    s.course_id,
    s.instructor_id,
    s.semester,
    s.week_number,
    s.session_date,
    s.session_type,
    s.is_active,
    s.started_at,
    s.expires_at,
    c.course_code,
    c.course_name,
    (SELECT COUNT(*) FROM attendance.attendance_records ar WHERE ar.session_id = s.id) as present_count,
    (SELECT COUNT(*) FROM attendance.enrollments_view ec WHERE ec.course_id = s.course_id AND ec.semester = s.semester) as enrolled_count
FROM attendance.attendance_sessions s
JOIN attendance.courses_view c ON s.course_id = c.id
WHERE s.session_date >= $1 AND s.session_date <= $2
ORDER BY s.session_date ASC, s.started_at ASC
`

type GetSessionsByDateRangeParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetSessionsByDateRangeRow struct {
	ID            pgtype.UUID               `json:"id"`
	CourseID      pgtype.UUID               `json:"course_id"`
	InstructorID  pgtype.UUID               `json:"instructor_id"`
	Semester      string                    `json:"semester"`
	WeekNumber    int16                     `json:"week_number"`
	SessionDate   pgtype.Date               `json:"session_date"`
	SessionType   AttendanceSessionTypeEnum `json:"session_type"`
	IsActive      pgtype.Bool               `json:"is_active"`
	StartedAt     pgtype.Timestamp          `json:"started_at"`
	ExpiresAt     pgtype.Timestamp          `json:"expires_at"`
	CourseCode    string                    `json:"course_code"`
	CourseName    string                    `json:"course_name"`
	PresentCount  int64                     `json:"present_count"`
	EnrolledCount int64                     `json:"enrolled_count"`
}

func (q *Queries) GetSessionsByDateRange(ctx context.Context, arg GetSessionsByDateRangeParams) ([]GetSessionsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getSessionsByDateRange, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionsByDateRangeRow{}
	for rows.Next() {
		var i GetSessionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.InstructorID,
			&i.Semester,
			&i.WeekNumber,
			&i.SessionDate,
			&i.SessionType,
			&i.IsActive,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CourseCode,
			&i.CourseName,
			&i.PresentCount,
			&i.EnrolledCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
