// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateAttendanceRecordsQR = `-- name: BatchCreateAttendanceRecordsQR :exec
INSERT INTO attendance.attendance_records (
    session_id, student_id, course_id, semester, week_number,
    marked_via, scanned_at, qr_timestamp, session_type
)
SELECT
    session_id, student_id, course_id, semester, week_number,
    'qr_scan', scanned_at, qr_timestamp, session_type
FROM (
    SELECT
        unnest($1::uuid[])            AS session_id,
        unnest($2::uuid[])            AS student_id,
        unnest($3::uuid[])             AS course_id,
        unnest($4::text[])              AS semester,
        unnest($5::smallint[])       AS week_number,
        unnest($6::timestamp[])       AS scanned_at,
        unnest($7::bigint[])        AS qr_timestamp,
        unnest($8::session_type_enum[]) AS session_type
) AS input
ON CONFLICT (session_id, student_id) DO NOTHING
`

type BatchCreateAttendanceRecordsQRParams struct {
	SessionIds   []pgtype.UUID      `json:"session_ids"`
	StudentIds   []pgtype.UUID      `json:"student_ids"`
	CourseIds    []pgtype.UUID      `json:"course_ids"`
	Semesters    []string           `json:"semesters"`
	WeekNumbers  []int16            `json:"week_numbers"`
	ScannedAts   []pgtype.Timestamp `json:"scanned_ats"`
	QrTimestamps []int64            `json:"qr_timestamps"`
	SessionTypes []interface{}      `json:"session_types"`
}

func (q *Queries) BatchCreateAttendanceRecordsQR(ctx context.Context, arg BatchCreateAttendanceRecordsQRParams) error {
	_, err := q.db.Exec(ctx, batchCreateAttendanceRecordsQR,
		arg.SessionIds,
		arg.StudentIds,
		arg.CourseIds,
		arg.Semesters,
		arg.WeekNumbers,
		arg.ScannedAts,
		arg.QrTimestamps,
		arg.SessionTypes,
	)
	return err
}

const createAttendanceRecordManual = `-- name: CreateAttendanceRecordManual :one
INSERT INTO attendance.attendance_records (
    session_id, student_id, course_id, semester, week_number,
    marked_via, manually_marked_by, manually_marked_at, manual_note, session_type
) VALUES (
    $1, $2, $3, $4, $5, 'manual', $6, NOW(), $7, $8
) ON CONFLICT (session_id, student_id)
DO UPDATE SET
    marked_via = EXCLUDED.marked_via,
    manually_marked_by = EXCLUDED.manually_marked_by,
    manually_marked_at = NOW(),
    manual_note = EXCLUDED.manual_note
RETURNING id, session_id, student_id, course_id, semester, week_number, session_type, marked_via, scanned_at, qr_timestamp, manually_marked_by, manually_marked_at, manual_note, created_at
`

type CreateAttendanceRecordManualParams struct {
	SessionID        pgtype.UUID               `json:"session_id"`
	StudentID        pgtype.UUID               `json:"student_id"`
	CourseID         pgtype.UUID               `json:"course_id"`
	Semester         string                    `json:"semester"`
	WeekNumber       int16                     `json:"week_number"`
	ManuallyMarkedBy pgtype.UUID               `json:"manually_marked_by"`
	ManualNote       pgtype.Text               `json:"manual_note"`
	SessionType      AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) CreateAttendanceRecordManual(ctx context.Context, arg CreateAttendanceRecordManualParams) (AttendanceAttendanceRecord, error) {
	row := q.db.QueryRow(ctx, createAttendanceRecordManual,
		arg.SessionID,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
		arg.WeekNumber,
		arg.ManuallyMarkedBy,
		arg.ManualNote,
		arg.SessionType,
	)
	var i AttendanceAttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StudentID,
		&i.CourseID,
		&i.Semester,
		&i.WeekNumber,
		&i.SessionType,
		&i.MarkedVia,
		&i.ScannedAt,
		&i.QrTimestamp,
		&i.ManuallyMarkedBy,
		&i.ManuallyMarkedAt,
		&i.ManualNote,
		&i.CreatedAt,
	)
	return i, err
}

const createAttendanceRecordQR = `-- name: CreateAttendanceRecordQR :exec
INSERT INTO attendance.attendance_records (
    session_id, student_id, course_id, semester, week_number,
    marked_via, scanned_at, qr_timestamp, session_type
) VALUES (
    $1, $2, $3, $4, $5, 'qr_scan', $6, $7, $8
) ON CONFLICT (session_id, student_id) DO NOTHING
`

type CreateAttendanceRecordQRParams struct {
	SessionID   pgtype.UUID               `json:"session_id"`
	StudentID   pgtype.UUID               `json:"student_id"`
	CourseID    pgtype.UUID               `json:"course_id"`
	Semester    string                    `json:"semester"`
	WeekNumber  int16                     `json:"week_number"`
	ScannedAt   pgtype.Timestamp          `json:"scanned_at"`
	QrTimestamp pgtype.Int8               `json:"qr_timestamp"`
	SessionType AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) CreateAttendanceRecordQR(ctx context.Context, arg CreateAttendanceRecordQRParams) error {
	_, err := q.db.Exec(ctx, createAttendanceRecordQR,
		arg.SessionID,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
		arg.WeekNumber,
		arg.ScannedAt,
		arg.QrTimestamp,
		arg.SessionType,
	)
	return err
}

const getAttendanceRecordsBySession = `-- name: GetAttendanceRecordsBySession :many
SELECT
    ar.id,
    ar.session_id,
    ar.student_id,
    ar.course_id,
    ar.semester,
    ar.week_number,
    ar.marked_via,
    ar.scanned_at,
    ar.qr_timestamp,
    ar.manually_marked_by,
    ar.manually_marked_at as marked_at,
    ar.manual_note,
    ar.created_at,
    ar.session_type
FROM attendance.attendance_records ar
WHERE ar.session_id = $1
ORDER BY ar.created_at DESC
`

type GetAttendanceRecordsBySessionRow struct {
	ID               pgtype.UUID               `json:"id"`
	SessionID        pgtype.UUID               `json:"session_id"`
	StudentID        pgtype.UUID               `json:"student_id"`
	CourseID         pgtype.UUID               `json:"course_id"`
	Semester         string                    `json:"semester"`
	WeekNumber       int16                     `json:"week_number"`
	MarkedVia        string                    `json:"marked_via"`
	ScannedAt        pgtype.Timestamp          `json:"scanned_at"`
	QrTimestamp      pgtype.Int8               `json:"qr_timestamp"`
	ManuallyMarkedBy pgtype.UUID               `json:"manually_marked_by"`
	MarkedAt         pgtype.Timestamp          `json:"marked_at"`
	ManualNote       pgtype.Text               `json:"manual_note"`
	CreatedAt        pgtype.Timestamp          `json:"created_at"`
	SessionType      AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) GetAttendanceRecordsBySession(ctx context.Context, sessionID pgtype.UUID) ([]GetAttendanceRecordsBySessionRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceRecordsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttendanceRecordsBySessionRow{}
	for rows.Next() {
		var i GetAttendanceRecordsBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StudentID,
			&i.CourseID,
			&i.Semester,
			&i.WeekNumber,
			&i.MarkedVia,
			&i.ScannedAt,
			&i.QrTimestamp,
			&i.ManuallyMarkedBy,
			&i.MarkedAt,
			&i.ManualNote,
			&i.CreatedAt,
			&i.SessionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseAttendanceStats = `-- name: GetCourseAttendanceStats :many
SELECT
    s.id as student_id,
    s.student_number,
    s.first_name,
    s.last_name,
    COUNT(ar.id) as present_count
FROM attendance.enrollments_view e
JOIN attendance.students_view s ON e.student_id = s.id
LEFT JOIN attendance.attendance_records ar ON ar.student_id = s.id AND ar.course_id = e.course_id AND ar.semester = e.semester
WHERE e.course_id = $1 AND e.semester = $2
GROUP BY s.id, s.student_number, s.first_name, s.last_name
ORDER BY s.student_number
`

type GetCourseAttendanceStatsParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Semester string      `json:"semester"`
}

type GetCourseAttendanceStatsRow struct {
	StudentID     pgtype.UUID `json:"student_id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	PresentCount  int64       `json:"present_count"`
}

func (q *Queries) GetCourseAttendanceStats(ctx context.Context, arg GetCourseAttendanceStatsParams) ([]GetCourseAttendanceStatsRow, error) {
	rows, err := q.db.Query(ctx, getCourseAttendanceStats, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCourseAttendanceStatsRow{}
	for rows.Next() {
		var i GetCourseAttendanceStatsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.PresentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseAttendanceStatsByType = `-- name: GetCourseAttendanceStatsByType :many
SELECT
    s.id as student_id,
    s.student_number,
    s.first_name,
    s.last_name,
    COUNT(ar.id) as present_count
FROM attendance.enrollments_view e
JOIN attendance.students_view s ON e.student_id = s.id
LEFT JOIN attendance.attendance_records ar ON ar.student_id = s.id AND ar.course_id = e.course_id AND ar.semester = e.semester AND ar.session_type = $3
WHERE e.course_id = $1 AND e.semester = $2
GROUP BY s.id, s.student_number, s.first_name, s.last_name
ORDER BY s.student_number
`

type GetCourseAttendanceStatsByTypeParams struct {
	CourseID    pgtype.UUID               `json:"course_id"`
	Semester    string                    `json:"semester"`
	SessionType AttendanceSessionTypeEnum `json:"session_type"`
}

type GetCourseAttendanceStatsByTypeRow struct {
	StudentID     pgtype.UUID `json:"student_id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	PresentCount  int64       `json:"present_count"`
}

func (q *Queries) GetCourseAttendanceStatsByType(ctx context.Context, arg GetCourseAttendanceStatsByTypeParams) ([]GetCourseAttendanceStatsByTypeRow, error) {
	rows, err := q.db.Query(ctx, getCourseAttendanceStatsByType, arg.CourseID, arg.Semester, arg.SessionType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCourseAttendanceStatsByTypeRow{}
	for rows.Next() {
		var i GetCourseAttendanceStatsByTypeRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.PresentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailingStudentsByCourse = `-- name: GetFailingStudentsByCourse :many
SELECT
    s.id as student_id,
    s.student_number,
    s.first_name,
    s.last_name,
    s.email,
    COUNT(ar.id) as present_count,
    ($3::bigint - COUNT(ar.id))::bigint as absent_count
FROM attendance.enrollments_view e
JOIN attendance.students_view s ON e.student_id = s.id
LEFT JOIN attendance.attendance_records ar ON ar.student_id = s.id AND ar.course_id = e.course_id AND ar.semester = e.semester
WHERE e.course_id = $1 AND e.semester = $2
GROUP BY s.id, s.student_number, s.first_name, s.last_name, s.email
HAVING ($3::bigint - COUNT(ar.id)) > $4::bigint
`

type GetFailingStudentsByCourseParams struct {
	CourseID           pgtype.UUID `json:"course_id"`
	Semester           string      `json:"semester"`
	TotalSessions      int64       `json:"total_sessions"`
	MaxAllowedAbsences int64       `json:"max_allowed_absences"`
}

type GetFailingStudentsByCourseRow struct {
	StudentID     pgtype.UUID `json:"student_id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	Email         pgtype.Text `json:"email"`
	PresentCount  int64       `json:"present_count"`
	AbsentCount   int64       `json:"absent_count"`
}

func (q *Queries) GetFailingStudentsByCourse(ctx context.Context, arg GetFailingStudentsByCourseParams) ([]GetFailingStudentsByCourseRow, error) {
	rows, err := q.db.Query(ctx, getFailingStudentsByCourse,
		arg.CourseID,
		arg.Semester,
		arg.TotalSessions,
		arg.MaxAllowedAbsences,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFailingStudentsByCourseRow{}
	for rows.Next() {
		var i GetFailingStudentsByCourseRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PresentCount,
			&i.AbsentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFailingStudentsByCourseByType = `-- name: GetFailingStudentsByCourseByType :many
SELECT
    s.id as student_id,
    s.student_number,
    s.first_name,
    s.last_name,
    s.email,
    COUNT(ar.id) as present_count,
    ($4::bigint - COUNT(ar.id))::bigint as absent_count
FROM attendance.enrollments_view e
JOIN attendance.students_view s ON e.student_id = s.id
LEFT JOIN attendance.attendance_records ar ON ar.student_id = s.id AND ar.course_id = e.course_id AND ar.semester = e.semester AND ar.session_type = $3
WHERE e.course_id = $1 AND e.semester = $2
GROUP BY s.id, s.student_number, s.first_name, s.last_name, s.email
HAVING COUNT(ar.id) < $5::bigint
`

type GetFailingStudentsByCourseByTypeParams struct {
	CourseID              pgtype.UUID               `json:"course_id"`
	Semester              string                    `json:"semester"`
	SessionType           AttendanceSessionTypeEnum `json:"session_type"`
	TotalSessions         int64                     `json:"total_sessions"`
	MinRequiredAttendance int64                     `json:"min_required_attendance"`
}

type GetFailingStudentsByCourseByTypeRow struct {
	StudentID     pgtype.UUID `json:"student_id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	Email         pgtype.Text `json:"email"`
	PresentCount  int64       `json:"present_count"`
	AbsentCount   int64       `json:"absent_count"`
}

func (q *Queries) GetFailingStudentsByCourseByType(ctx context.Context, arg GetFailingStudentsByCourseByTypeParams) ([]GetFailingStudentsByCourseByTypeRow, error) {
	rows, err := q.db.Query(ctx, getFailingStudentsByCourseByType,
		arg.CourseID,
		arg.Semester,
		arg.SessionType,
		arg.TotalSessions,
		arg.MinRequiredAttendance,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFailingStudentsByCourseByTypeRow{}
	for rows.Next() {
		var i GetFailingStudentsByCourseByTypeRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PresentCount,
			&i.AbsentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMarkedStudentsBySession = `-- name: GetMarkedStudentsBySession :many
SELECT student_id
FROM attendance.attendance_records
WHERE session_id = $1
`

func (q *Queries) GetMarkedStudentsBySession(ctx context.Context, sessionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getMarkedStudentsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var student_id pgtype.UUID
		if err := rows.Scan(&student_id); err != nil {
			return nil, err
		}
		items = append(items, student_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionAttendanceCount = `-- name: GetSessionAttendanceCount :one
SELECT COUNT(*) as present_count
FROM attendance.attendance_records
WHERE session_id = $1
`

func (q *Queries) GetSessionAttendanceCount(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionAttendanceCount, sessionID)
	var present_count int64
	err := row.Scan(&present_count)
	return present_count, err
}

const getStudentAttendanceByCourse = `-- name: GetStudentAttendanceByCourse :many
SELECT
    ar.week_number,
    ats.session_date,
    ar.marked_via,
    ar.manual_note,
    ar.scanned_at,
    ar.manually_marked_at,
    ar.session_type
FROM attendance.attendance_records ar
JOIN attendance.attendance_sessions ats ON ar.session_id = ats.id
WHERE ar.student_id = $1 AND ar.course_id = $2 AND ar.semester = $3
ORDER BY ar.week_number ASC, ar.session_type ASC
`

type GetStudentAttendanceByCourseParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	Semester  string      `json:"semester"`
}

type GetStudentAttendanceByCourseRow struct {
	WeekNumber       int16                     `json:"week_number"`
	SessionDate      pgtype.Date               `json:"session_date"`
	MarkedVia        string                    `json:"marked_via"`
	ManualNote       pgtype.Text               `json:"manual_note"`
	ScannedAt        pgtype.Timestamp          `json:"scanned_at"`
	ManuallyMarkedAt pgtype.Timestamp          `json:"manually_marked_at"`
	SessionType      AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) GetStudentAttendanceByCourse(ctx context.Context, arg GetStudentAttendanceByCourseParams) ([]GetStudentAttendanceByCourseRow, error) {
	rows, err := q.db.Query(ctx, getStudentAttendanceByCourse, arg.StudentID, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentAttendanceByCourseRow{}
	for rows.Next() {
		var i GetStudentAttendanceByCourseRow
		if err := rows.Scan(
			&i.WeekNumber,
			&i.SessionDate,
			&i.MarkedVia,
			&i.ManualNote,
			&i.ScannedAt,
			&i.ManuallyMarkedAt,
			&i.SessionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentPresentCountByType = `-- name: GetStudentPresentCountByType :one
SELECT COUNT(*) as present_count
FROM attendance.attendance_records
WHERE student_id = $1 AND course_id = $2 AND semester = $3 AND session_type = $4
`

type GetStudentPresentCountByTypeParams struct {
	StudentID   pgtype.UUID               `json:"student_id"`
	CourseID    pgtype.UUID               `json:"course_id"`
	Semester    string                    `json:"semester"`
	SessionType AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) GetStudentPresentCountByType(ctx context.Context, arg GetStudentPresentCountByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getStudentPresentCountByType,
		arg.StudentID,
		arg.CourseID,
		arg.Semester,
		arg.SessionType,
	)
	var present_count int64
	err := row.Scan(&present_count)
	return present_count, err
}

const getTotalSessionsByCourse = `-- name: GetTotalSessionsByCourse :one
SELECT COUNT(*) as total_sessions
FROM attendance.attendance_sessions
WHERE course_id = $1 AND semester = $2
`

type GetTotalSessionsByCourseParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Semester string      `json:"semester"`
}

func (q *Queries) GetTotalSessionsByCourse(ctx context.Context, arg GetTotalSessionsByCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalSessionsByCourse, arg.CourseID, arg.Semester)
	var total_sessions int64
	err := row.Scan(&total_sessions)
	return total_sessions, err
}

const getTotalSessionsByCourseAndType = `-- name: GetTotalSessionsByCourseAndType :one
SELECT COUNT(*) as total_sessions
FROM attendance.attendance_sessions
WHERE course_id = $1 AND semester = $2 AND session_type = $3
`

type GetTotalSessionsByCourseAndTypeParams struct {
	CourseID    pgtype.UUID               `json:"course_id"`
	Semester    string                    `json:"semester"`
	SessionType AttendanceSessionTypeEnum `json:"session_type"`
}

func (q *Queries) GetTotalSessionsByCourseAndType(ctx context.Context, arg GetTotalSessionsByCourseAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalSessionsByCourseAndType, arg.CourseID, arg.Semester, arg.SessionType)
	var total_sessions int64
	err := row.Scan(&total_sessions)
	return total_sessions, err
}
