// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCourseCacheByID = `-- name: GetCourseCacheByID :one
SELECT id, course_code, course_name, credits, semester, department,
       instructor_id, instructor_fullname, total_weeks, has_lab, synced_at
FROM attendance.courses_view
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCourseCacheByID(ctx context.Context, id pgtype.UUID) (AttendanceCoursesView, error) {
	row := q.db.QueryRow(ctx, getCourseCacheByID, id)
	var i AttendanceCoursesView
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.CourseName,
		&i.Credits,
		&i.Semester,
		&i.Department,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.TotalWeeks,
		&i.HasLab,
		&i.SyncedAt,
	)
	return i, err
}

const upsertCourseCache = `-- name: UpsertCourseCache :exec
INSERT INTO attendance.courses_view (
    id, course_code, course_name, credits, semester, department,
    instructor_id, instructor_fullname, total_weeks, has_lab, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
) ON CONFLICT (id) DO UPDATE SET
    course_code = EXCLUDED.course_code,
    course_name = EXCLUDED.course_name,
    credits = EXCLUDED.credits,
    semester = EXCLUDED.semester,
    department = EXCLUDED.department,
    instructor_id = EXCLUDED.instructor_id,
    instructor_fullname = EXCLUDED.instructor_fullname,
    total_weeks = EXCLUDED.total_weeks,
    has_lab = EXCLUDED.has_lab,
    synced_at = NOW()
`

type UpsertCourseCacheParams struct {
	ID                 pgtype.UUID `json:"id"`
	CourseCode         string      `json:"course_code"`
	CourseName         string      `json:"course_name"`
	Credits            int16       `json:"credits"`
	Semester           string      `json:"semester"`
	Department         pgtype.Text `json:"department"`
	InstructorID       pgtype.UUID `json:"instructor_id"`
	InstructorFullname pgtype.Text `json:"instructor_fullname"`
	TotalWeeks         pgtype.Int2 `json:"total_weeks"`
	HasLab             bool        `json:"has_lab"`
}

func (q *Queries) UpsertCourseCache(ctx context.Context, arg UpsertCourseCacheParams) error {
	_, err := q.db.Exec(ctx, upsertCourseCache,
		arg.ID,
		arg.CourseCode,
		arg.CourseName,
		arg.Credits,
		arg.Semester,
		arg.Department,
		arg.InstructorID,
		arg.InstructorFullname,
		arg.TotalWeeks,
		arg.HasLab,
	)
	return err
}
