// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceOutboxStatusEnum string

const (
	AttendanceOutboxStatusEnumPending   AttendanceOutboxStatusEnum = "pending"
	AttendanceOutboxStatusEnumProcessed AttendanceOutboxStatusEnum = "processed"
	AttendanceOutboxStatusEnumFailed    AttendanceOutboxStatusEnum = "failed"
)

func (e *AttendanceOutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceOutboxStatusEnum(s)
	case string:
		*e = AttendanceOutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceOutboxStatusEnum: %T", src)
	}
	return nil
}

type NullAttendanceOutboxStatusEnum struct {
	AttendanceOutboxStatusEnum AttendanceOutboxStatusEnum `json:"attendance_outbox_status_enum"`
	Valid                      bool                       `json:"valid"` // Valid is true if AttendanceOutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceOutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceOutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceOutboxStatusEnum), nil
}

type AttendanceSessionTypeEnum string

const (
	AttendanceSessionTypeEnumTheory AttendanceSessionTypeEnum = "theory"
	AttendanceSessionTypeEnumLab    AttendanceSessionTypeEnum = "lab"
)

func (e *AttendanceSessionTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceSessionTypeEnum(s)
	case string:
		*e = AttendanceSessionTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceSessionTypeEnum: %T", src)
	}
	return nil
}

type NullAttendanceSessionTypeEnum struct {
	AttendanceSessionTypeEnum AttendanceSessionTypeEnum `json:"attendance_session_type_enum"`
	Valid                     bool                      `json:"valid"` // Valid is true if AttendanceSessionTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceSessionTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceSessionTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceSessionTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceSessionTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceSessionTypeEnum), nil
}

type AttendanceAcademicPeriod struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceAttendanceRecord struct {
	ID               pgtype.UUID               `json:"id"`
	SessionID        pgtype.UUID               `json:"session_id"`
	StudentID        pgtype.UUID               `json:"student_id"`
	CourseID         pgtype.UUID               `json:"course_id"`
	Semester         string                    `json:"semester"`
	WeekNumber       int16                     `json:"week_number"`
	SessionType      AttendanceSessionTypeEnum `json:"session_type"`
	MarkedVia        string                    `json:"marked_via"`
	ScannedAt        pgtype.Timestamp          `json:"scanned_at"`
	QrTimestamp      pgtype.Int8               `json:"qr_timestamp"`
	ManuallyMarkedBy pgtype.UUID               `json:"manually_marked_by"`
	ManuallyMarkedAt pgtype.Timestamp          `json:"manually_marked_at"`
	ManualNote       pgtype.Text               `json:"manual_note"`
	CreatedAt        pgtype.Timestamp          `json:"created_at"`
}

type AttendanceAttendanceSession struct {
	ID                 pgtype.UUID               `json:"id"`
	CourseID           pgtype.UUID               `json:"course_id"`
	InstructorID       pgtype.UUID               `json:"instructor_id"`
	Semester           string                    `json:"semester"`
	WeekNumber         int16                     `json:"week_number"`
	SessionDate        pgtype.Date               `json:"session_date"`
	SessionType        AttendanceSessionTypeEnum `json:"session_type"`
	QrSecret           string                    `json:"qr_secret"`
	QrRotationInterval pgtype.Int2               `json:"qr_rotation_interval"`
	StartedAt          pgtype.Timestamp          `json:"started_at"`
	ExpiresAt          pgtype.Timestamp          `json:"expires_at"`
	IsActive           pgtype.Bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamp          `json:"created_at"`
}

type AttendanceCoursesView struct {
	ID                 pgtype.UUID      `json:"id"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	Credits            int16            `json:"credits"`
	Semester           string           `json:"semester"`
	Department         pgtype.Text      `json:"department"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname pgtype.Text      `json:"instructor_fullname"`
	TotalWeeks         pgtype.Int2      `json:"total_weeks"`
	HasLab             bool             `json:"has_lab"`
	SyncedAt           pgtype.Timestamp `json:"synced_at"`
}

type AttendanceEnrollmentsView struct {
	ID        pgtype.UUID      `json:"id"`
	StudentID pgtype.UUID      `json:"student_id"`
	CourseID  pgtype.UUID      `json:"course_id"`
	Semester  string           `json:"semester"`
	SyncedAt  pgtype.Timestamp `json:"synced_at"`
}

type AttendanceOutboxEvent struct {
	ID           pgtype.UUID                    `json:"id"`
	EventType    string                         `json:"event_type"`
	RoutingKey   string                         `json:"routing_key"`
	Payload      []byte                         `json:"payload"`
	Status       NullAttendanceOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2                    `json:"retry_count"`
	MaxRetries   pgtype.Int2                    `json:"max_retries"`
	CreatedAt    pgtype.Timestamp               `json:"created_at"`
	ProcessedAt  pgtype.Timestamp               `json:"processed_at"`
	ErrorMessage pgtype.Text                    `json:"error_message"`
}

type AttendanceProcessedEvent struct {
	EventID     pgtype.UUID      `json:"event_id"`
	EventType   string           `json:"event_type"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type AttendanceStudentsView struct {
	ID            pgtype.UUID      `json:"id"`
	StudentNumber string           `json:"student_number"`
	FirstName     pgtype.Text      `json:"first_name"`
	LastName      pgtype.Text      `json:"last_name"`
	Email         pgtype.Text      `json:"email"`
	Department    pgtype.Text      `json:"department"`
	IsActive      pgtype.Bool      `json:"is_active"`
	SyncedAt      pgtype.Timestamp `json:"synced_at"`
}
