// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO attendance.outbox_events (event_type, routing_key, payload)
VALUES ($1, $2, $3)
`

type CreateOutboxEventParams struct {
	EventType  string `json:"event_type"`
	RoutingKey string `json:"routing_key"`
	Payload    []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent, arg.EventType, arg.RoutingKey, arg.Payload)
	return err
}

const getFailedOutboxEvents = `-- name: GetFailedOutboxEvents :many
SELECT id, event_type, routing_key, payload, retry_count, max_retries
FROM attendance.outbox_events
WHERE status = 'failed'
ORDER BY created_at ASC
LIMIT $1
`

type GetFailedOutboxEventsRow struct {
	ID         pgtype.UUID `json:"id"`
	EventType  string      `json:"event_type"`
	RoutingKey string      `json:"routing_key"`
	Payload    []byte      `json:"payload"`
	RetryCount pgtype.Int2 `json:"retry_count"`
	MaxRetries pgtype.Int2 `json:"max_retries"`
}

func (q *Queries) GetFailedOutboxEvents(ctx context.Context, limit int32) ([]GetFailedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getFailedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFailedOutboxEventsRow{}
	for rows.Next() {
		var i GetFailedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RoutingKey,
			&i.Payload,
			&i.RetryCount,
			&i.MaxRetries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, routing_key, payload, retry_count, max_retries
FROM attendance.outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingOutboxEventsRow struct {
	ID         pgtype.UUID `json:"id"`
	EventType  string      `json:"event_type"`
	RoutingKey string      `json:"routing_key"`
	Payload    []byte      `json:"payload"`
	RetryCount pgtype.Int2 `json:"retry_count"`
	MaxRetries pgtype.Int2 `json:"max_retries"`
}

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]GetPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingOutboxEventsRow{}
	for rows.Next() {
		var i GetPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RoutingKey,
			&i.Payload,
			&i.RetryCount,
			&i.MaxRetries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE attendance.outbox_events
SET retry_count = retry_count + 1,
    status = CASE
        WHEN retry_count + 1 >= max_retries THEN 'failed'::outbox_status_enum
        ELSE 'pending'::outbox_status_enum
    END,
    error_message = $2
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE attendance.outbox_events
SET status = 'processed', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}

const resetFailedOutboxEvent = `-- name: ResetFailedOutboxEvent :exec
UPDATE attendance.outbox_events
SET status = 'pending',
    retry_count = 0,
    error_message = NULL
WHERE id = $1 AND status = 'failed'
`

func (q *Queries) ResetFailedOutboxEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedOutboxEvent, id)
	return err
}
