// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: completed_courses.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateStudentGPA = `-- name: CalculateStudentGPA :one
SELECT
    COALESCE(
        ROUND(
            SUM(grade_point::text::decimal * credits) / NULLIF(SUM(credits), 0),
            2
        ), 0
    ) as gpa,
    COALESCE(SUM(credits), 0) as total_credits
FROM student_completed_courses
WHERE student_id = $1
`

type CalculateStudentGPARow struct {
	Gpa          interface{} `json:"gpa"`
	TotalCredits interface{} `json:"total_credits"`
}

func (q *Queries) CalculateStudentGPA(ctx context.Context, studentID uuid.UUID) (CalculateStudentGPARow, error) {
	row := q.db.QueryRow(ctx, calculateStudentGPA, studentID)
	var i CalculateStudentGPARow
	err := row.Scan(&i.Gpa, &i.TotalCredits)
	return i, err
}

const createCompletedCourse = `-- name: CreateCompletedCourse :one
INSERT INTO student_completed_courses (
    student_id, student_number, student_first_name, student_last_name, student_department,
    course_id, course_code, course_name, credits, semester,
    instructor_id, instructor_name,
    assessment_scores, weighted_average, grade_point,
    grading_type, grading_config, class_statistics,
    is_attendance_failed, finalized_at, finalized_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19, $20, $21
)
RETURNING id, student_id, student_number, student_first_name, student_last_name, student_department, course_id, course_code, course_name, credits, semester, instructor_id, instructor_name, assessment_scores, weighted_average, grade_point, grading_type, grading_config, class_statistics, is_attendance_failed, finalized_at, finalized_by
`

type CreateCompletedCourseParams struct {
	StudentID          uuid.UUID        `json:"student_id"`
	StudentNumber      string           `json:"student_number"`
	StudentFirstName   string           `json:"student_first_name"`
	StudentLastName    string           `json:"student_last_name"`
	StudentDepartment  pgtype.Text      `json:"student_department"`
	CourseID           uuid.UUID        `json:"course_id"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	Credits            int16            `json:"credits"`
	Semester           string           `json:"semester"`
	InstructorID       uuid.UUID        `json:"instructor_id"`
	InstructorName     string           `json:"instructor_name"`
	AssessmentScores   []byte           `json:"assessment_scores"`
	WeightedAverage    pgtype.Numeric   `json:"weighted_average"`
	GradePoint         GradePointEnum   `json:"grade_point"`
	GradingType        GradingTypeEnum  `json:"grading_type"`
	GradingConfig      []byte           `json:"grading_config"`
	ClassStatistics    []byte           `json:"class_statistics"`
	IsAttendanceFailed pgtype.Bool      `json:"is_attendance_failed"`
	FinalizedAt        pgtype.Timestamp `json:"finalized_at"`
	FinalizedBy        uuid.UUID        `json:"finalized_by"`
}

func (q *Queries) CreateCompletedCourse(ctx context.Context, arg CreateCompletedCourseParams) (StudentCompletedCourse, error) {
	row := q.db.QueryRow(ctx, createCompletedCourse,
		arg.StudentID,
		arg.StudentNumber,
		arg.StudentFirstName,
		arg.StudentLastName,
		arg.StudentDepartment,
		arg.CourseID,
		arg.CourseCode,
		arg.CourseName,
		arg.Credits,
		arg.Semester,
		arg.InstructorID,
		arg.InstructorName,
		arg.AssessmentScores,
		arg.WeightedAverage,
		arg.GradePoint,
		arg.GradingType,
		arg.GradingConfig,
		arg.ClassStatistics,
		arg.IsAttendanceFailed,
		arg.FinalizedAt,
		arg.FinalizedBy,
	)
	var i StudentCompletedCourse
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.StudentNumber,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.StudentDepartment,
		&i.CourseID,
		&i.CourseCode,
		&i.CourseName,
		&i.Credits,
		&i.Semester,
		&i.InstructorID,
		&i.InstructorName,
		&i.AssessmentScores,
		&i.WeightedAverage,
		&i.GradePoint,
		&i.GradingType,
		&i.GradingConfig,
		&i.ClassStatistics,
		&i.IsAttendanceFailed,
		&i.FinalizedAt,
		&i.FinalizedBy,
	)
	return i, err
}

const deleteCompletedCourse = `-- name: DeleteCompletedCourse :exec
DELETE FROM student_completed_courses
WHERE student_id = $1 AND course_code = $2
`

type DeleteCompletedCourseParams struct {
	StudentID  uuid.UUID `json:"student_id"`
	CourseCode string    `json:"course_code"`
}

func (q *Queries) DeleteCompletedCourse(ctx context.Context, arg DeleteCompletedCourseParams) error {
	_, err := q.db.Exec(ctx, deleteCompletedCourse, arg.StudentID, arg.CourseCode)
	return err
}

const getCompletedCourseByStudentAndCourse = `-- name: GetCompletedCourseByStudentAndCourse :one
SELECT id, student_id, student_number, student_first_name, student_last_name, student_department, course_id, course_code, course_name, credits, semester, instructor_id, instructor_name, assessment_scores, weighted_average, grade_point, grading_type, grading_config, class_statistics, is_attendance_failed, finalized_at, finalized_by FROM student_completed_courses
WHERE student_id = $1 AND course_id = $2
`

type GetCompletedCourseByStudentAndCourseParams struct {
	StudentID uuid.UUID `json:"student_id"`
	CourseID  uuid.UUID `json:"course_id"`
}

func (q *Queries) GetCompletedCourseByStudentAndCourse(ctx context.Context, arg GetCompletedCourseByStudentAndCourseParams) (StudentCompletedCourse, error) {
	row := q.db.QueryRow(ctx, getCompletedCourseByStudentAndCourse, arg.StudentID, arg.CourseID)
	var i StudentCompletedCourse
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.StudentNumber,
		&i.StudentFirstName,
		&i.StudentLastName,
		&i.StudentDepartment,
		&i.CourseID,
		&i.CourseCode,
		&i.CourseName,
		&i.Credits,
		&i.Semester,
		&i.InstructorID,
		&i.InstructorName,
		&i.AssessmentScores,
		&i.WeightedAverage,
		&i.GradePoint,
		&i.GradingType,
		&i.GradingConfig,
		&i.ClassStatistics,
		&i.IsAttendanceFailed,
		&i.FinalizedAt,
		&i.FinalizedBy,
	)
	return i, err
}

const getCompletedCoursesByCourse = `-- name: GetCompletedCoursesByCourse :many
SELECT id, student_id, student_number, student_first_name, student_last_name, student_department, course_id, course_code, course_name, credits, semester, instructor_id, instructor_name, assessment_scores, weighted_average, grade_point, grading_type, grading_config, class_statistics, is_attendance_failed, finalized_at, finalized_by FROM student_completed_courses
WHERE course_id = $1
ORDER BY student_number
`

func (q *Queries) GetCompletedCoursesByCourse(ctx context.Context, courseID uuid.UUID) ([]StudentCompletedCourse, error) {
	rows, err := q.db.Query(ctx, getCompletedCoursesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentCompletedCourse{}
	for rows.Next() {
		var i StudentCompletedCourse
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.StudentNumber,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.StudentDepartment,
			&i.CourseID,
			&i.CourseCode,
			&i.CourseName,
			&i.Credits,
			&i.Semester,
			&i.InstructorID,
			&i.InstructorName,
			&i.AssessmentScores,
			&i.WeightedAverage,
			&i.GradePoint,
			&i.GradingType,
			&i.GradingConfig,
			&i.ClassStatistics,
			&i.IsAttendanceFailed,
			&i.FinalizedAt,
			&i.FinalizedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedCoursesByStudent = `-- name: GetCompletedCoursesByStudent :many
SELECT id, student_id, student_number, student_first_name, student_last_name, student_department, course_id, course_code, course_name, credits, semester, instructor_id, instructor_name, assessment_scores, weighted_average, grade_point, grading_type, grading_config, class_statistics, is_attendance_failed, finalized_at, finalized_by FROM student_completed_courses
WHERE student_id = $1
ORDER BY finalized_at DESC
`

func (q *Queries) GetCompletedCoursesByStudent(ctx context.Context, studentID uuid.UUID) ([]StudentCompletedCourse, error) {
	rows, err := q.db.Query(ctx, getCompletedCoursesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentCompletedCourse{}
	for rows.Next() {
		var i StudentCompletedCourse
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.StudentNumber,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.StudentDepartment,
			&i.CourseID,
			&i.CourseCode,
			&i.CourseName,
			&i.Credits,
			&i.Semester,
			&i.InstructorID,
			&i.InstructorName,
			&i.AssessmentScores,
			&i.WeightedAverage,
			&i.GradePoint,
			&i.GradingType,
			&i.GradingConfig,
			&i.ClassStatistics,
			&i.IsAttendanceFailed,
			&i.FinalizedAt,
			&i.FinalizedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranscriptData = `-- name: GetTranscriptData :many
SELECT
    semester,
    course_code,
    course_name,
    credits,
    grade_point,
    finalized_at
FROM student_completed_courses
WHERE student_id = $1
ORDER BY finalized_at
`

type GetTranscriptDataRow struct {
	Semester    string           `json:"semester"`
	CourseCode  string           `json:"course_code"`
	CourseName  string           `json:"course_name"`
	Credits     int16            `json:"credits"`
	GradePoint  GradePointEnum   `json:"grade_point"`
	FinalizedAt pgtype.Timestamp `json:"finalized_at"`
}

func (q *Queries) GetTranscriptData(ctx context.Context, studentID uuid.UUID) ([]GetTranscriptDataRow, error) {
	rows, err := q.db.Query(ctx, getTranscriptData, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTranscriptDataRow{}
	for rows.Next() {
		var i GetTranscriptDataRow
		if err := rows.Scan(
			&i.Semester,
			&i.CourseCode,
			&i.CourseName,
			&i.Credits,
			&i.GradePoint,
			&i.FinalizedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompletedCourseAfterAppeal = `-- name: UpdateCompletedCourseAfterAppeal :exec
UPDATE student_completed_courses
SET
    assessment_scores = $3,
    weighted_average = $4,
    grade_point = $5,
    grading_config = $6,
    finalized_at = NOW()
WHERE student_id = $1 AND course_id = $2
`

type UpdateCompletedCourseAfterAppealParams struct {
	StudentID        uuid.UUID      `json:"student_id"`
	CourseID         uuid.UUID      `json:"course_id"`
	AssessmentScores []byte         `json:"assessment_scores"`
	WeightedAverage  pgtype.Numeric `json:"weighted_average"`
	GradePoint       GradePointEnum `json:"grade_point"`
	GradingConfig    []byte         `json:"grading_config"`
}

func (q *Queries) UpdateCompletedCourseAfterAppeal(ctx context.Context, arg UpdateCompletedCourseAfterAppealParams) error {
	_, err := q.db.Exec(ctx, updateCompletedCourseAfterAppeal,
		arg.StudentID,
		arg.CourseID,
		arg.AssessmentScores,
		arg.WeightedAverage,
		arg.GradePoint,
		arg.GradingConfig,
	)
	return err
}
