// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses_cache.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCourseCacheByID = `-- name: GetCourseCacheByID :one
SELECT id, course_code, course_name, credits, semester, department, instructor_id, instructor_fullname, assessment_schema, synced_at FROM courses_cache
WHERE id = $1
`

func (q *Queries) GetCourseCacheByID(ctx context.Context, id uuid.UUID) (CoursesCache, error) {
	row := q.db.QueryRow(ctx, getCourseCacheByID, id)
	var i CoursesCache
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.CourseName,
		&i.Credits,
		&i.Semester,
		&i.Department,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.AssessmentSchema,
		&i.SyncedAt,
	)
	return i, err
}

const upsertCourseCache = `-- name: UpsertCourseCache :one
INSERT INTO courses_cache (
    id, course_code, course_name, credits, semester, department,
    instructor_id, instructor_fullname, assessment_schema, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
)
ON CONFLICT (id) DO UPDATE SET
    course_code = EXCLUDED.course_code,
    course_name = EXCLUDED.course_name,
    credits = EXCLUDED.credits,
    semester = EXCLUDED.semester,
    department = EXCLUDED.department,
    instructor_id = EXCLUDED.instructor_id,
    instructor_fullname = EXCLUDED.instructor_fullname,
    assessment_schema = EXCLUDED.assessment_schema,
    synced_at = NOW()
RETURNING id, course_code, course_name, credits, semester, department, instructor_id, instructor_fullname, assessment_schema, synced_at
`

type UpsertCourseCacheParams struct {
	ID                 uuid.UUID   `json:"id"`
	CourseCode         string      `json:"course_code"`
	CourseName         string      `json:"course_name"`
	Credits            int16       `json:"credits"`
	Semester           string      `json:"semester"`
	Department         pgtype.Text `json:"department"`
	InstructorID       uuid.UUID   `json:"instructor_id"`
	InstructorFullname pgtype.Text `json:"instructor_fullname"`
	AssessmentSchema   []byte      `json:"assessment_schema"`
}

func (q *Queries) UpsertCourseCache(ctx context.Context, arg UpsertCourseCacheParams) (CoursesCache, error) {
	row := q.db.QueryRow(ctx, upsertCourseCache,
		arg.ID,
		arg.CourseCode,
		arg.CourseName,
		arg.Credits,
		arg.Semester,
		arg.Department,
		arg.InstructorID,
		arg.InstructorFullname,
		arg.AssessmentSchema,
	)
	var i CoursesCache
	err := row.Scan(
		&i.ID,
		&i.CourseCode,
		&i.CourseName,
		&i.Credits,
		&i.Semester,
		&i.Department,
		&i.InstructorID,
		&i.InstructorFullname,
		&i.AssessmentSchema,
		&i.SyncedAt,
	)
	return i, err
}
