// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GradePointEnum string

const (
	GradePointEnum400 GradePointEnum = "4.00"
	GradePointEnum375 GradePointEnum = "3.75"
	GradePointEnum350 GradePointEnum = "3.50"
	GradePointEnum325 GradePointEnum = "3.25"
	GradePointEnum300 GradePointEnum = "3.00"
	GradePointEnum275 GradePointEnum = "2.75"
	GradePointEnum250 GradePointEnum = "2.50"
	GradePointEnum225 GradePointEnum = "2.25"
	GradePointEnum200 GradePointEnum = "2.00"
	GradePointEnum175 GradePointEnum = "1.75"
	GradePointEnum150 GradePointEnum = "1.50"
	GradePointEnum125 GradePointEnum = "1.25"
	GradePointEnum100 GradePointEnum = "1.00"
	GradePointEnum050 GradePointEnum = "0.50"
	GradePointEnum000 GradePointEnum = "0.00"
)

func (e *GradePointEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GradePointEnum(s)
	case string:
		*e = GradePointEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GradePointEnum: %T", src)
	}
	return nil
}

type NullGradePointEnum struct {
	GradePointEnum GradePointEnum `json:"grade_point_enum"`
	Valid          bool           `json:"valid"` // Valid is true if GradePointEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGradePointEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GradePointEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GradePointEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGradePointEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GradePointEnum), nil
}

type GradingTypeEnum string

const (
	GradingTypeEnumAbsolute GradingTypeEnum = "absolute"
	GradingTypeEnumRelative GradingTypeEnum = "relative"
)

func (e *GradingTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GradingTypeEnum(s)
	case string:
		*e = GradingTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GradingTypeEnum: %T", src)
	}
	return nil
}

type NullGradingTypeEnum struct {
	GradingTypeEnum GradingTypeEnum `json:"grading_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if GradingTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGradingTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GradingTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GradingTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGradingTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GradingTypeEnum), nil
}

type OutboxStatusEnum string

const (
	OutboxStatusEnumPending   OutboxStatusEnum = "pending"
	OutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	OutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type AcademicPeriod struct {
	ID          uuid.UUID          `json:"id"`
	Semester    string             `json:"semester"`
	CourseID    pgtype.UUID        `json:"course_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CoursesCache struct {
	ID                 uuid.UUID        `json:"id"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	Credits            int16            `json:"credits"`
	Semester           string           `json:"semester"`
	Department         pgtype.Text      `json:"department"`
	InstructorID       uuid.UUID        `json:"instructor_id"`
	InstructorFullname pgtype.Text      `json:"instructor_fullname"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	SyncedAt           pgtype.Timestamp `json:"synced_at"`
}

type OutboxEvent struct {
	ID           uuid.UUID            `json:"id"`
	EventType    string               `json:"event_type"`
	RoutingKey   string               `json:"routing_key"`
	Payload      []byte               `json:"payload"`
	Status       NullOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2          `json:"retry_count"`
	MaxRetries   pgtype.Int2          `json:"max_retries"`
	CreatedAt    pgtype.Timestamp     `json:"created_at"`
	ProcessedAt  pgtype.Timestamp     `json:"processed_at"`
	ErrorMessage pgtype.Text          `json:"error_message"`
}

type PrerequisiteCoursesCache struct {
	CourseCode string           `json:"course_code"`
	CourseID   uuid.UUID        `json:"course_id"`
	SyncedAt   pgtype.Timestamp `json:"synced_at"`
}

type StudentAssessmentScore struct {
	ID             uuid.UUID        `json:"id"`
	RegistrationID uuid.UUID        `json:"registration_id"`
	Slug           string           `json:"slug"`
	Score          pgtype.Numeric   `json:"score"`
	IsAbsent       pgtype.Bool      `json:"is_absent"`
	GradedBy       uuid.UUID        `json:"graded_by"`
	GradedAt       pgtype.Timestamp `json:"graded_at"`
	IsLocked       pgtype.Bool      `json:"is_locked"`
}

type StudentCompletedCourse struct {
	ID                 uuid.UUID        `json:"id"`
	StudentID          uuid.UUID        `json:"student_id"`
	StudentNumber      string           `json:"student_number"`
	StudentFirstName   string           `json:"student_first_name"`
	StudentLastName    string           `json:"student_last_name"`
	StudentDepartment  pgtype.Text      `json:"student_department"`
	CourseID           uuid.UUID        `json:"course_id"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	Credits            int16            `json:"credits"`
	Semester           string           `json:"semester"`
	InstructorID       uuid.UUID        `json:"instructor_id"`
	InstructorName     string           `json:"instructor_name"`
	AssessmentScores   []byte           `json:"assessment_scores"`
	WeightedAverage    pgtype.Numeric   `json:"weighted_average"`
	GradePoint         GradePointEnum   `json:"grade_point"`
	GradingType        GradingTypeEnum  `json:"grading_type"`
	GradingConfig      []byte           `json:"grading_config"`
	ClassStatistics    []byte           `json:"class_statistics"`
	IsAttendanceFailed pgtype.Bool      `json:"is_attendance_failed"`
	FinalizedAt        pgtype.Timestamp `json:"finalized_at"`
	FinalizedBy        uuid.UUID        `json:"finalized_by"`
}

type StudentCourseRegistration struct {
	ID                 uuid.UUID        `json:"id"`
	StudentID          uuid.UUID        `json:"student_id"`
	CourseID           uuid.UUID        `json:"course_id"`
	Semester           string           `json:"semester"`
	IsAttendanceFailed pgtype.Bool      `json:"is_attendance_failed"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type StudentsCache struct {
	ID            uuid.UUID        `json:"id"`
	StudentNumber string           `json:"student_number"`
	FirstName     pgtype.Text      `json:"first_name"`
	LastName      pgtype.Text      `json:"last_name"`
	Email         pgtype.Text      `json:"email"`
	Department    pgtype.Text      `json:"department"`
	ClassLevel    pgtype.Int2      `json:"class_level"`
	IsActive      pgtype.Bool      `json:"is_active"`
	SyncedAt      pgtype.Timestamp `json:"synced_at"`
}
