// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    event_type, routing_key, payload, status, retry_count, max_retries
) VALUES (
    $1, $2, $3, 'pending', 0, 3
)
RETURNING id, event_type, routing_key, payload, status, retry_count, max_retries, created_at, processed_at, error_message
`

type CreateOutboxEventParams struct {
	EventType  string `json:"event_type"`
	RoutingKey string `json:"routing_key"`
	Payload    []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.RoutingKey, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RoutingKey,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, routing_key, payload, status, retry_count, max_retries, created_at, processed_at, error_message FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RoutingKey,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET status = 'failed',
    retry_count = retry_count + 1,
    error_message = $2,
    processed_at = NOW()
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET status = 'processed', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}

const retryFailedOutboxEvent = `-- name: RetryFailedOutboxEvent :exec
UPDATE outbox_events
SET status = 'pending',
    retry_count = retry_count + 1
WHERE id = $1 AND retry_count < max_retries
`

func (q *Queries) RetryFailedOutboxEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, retryFailedOutboxEvent, id)
	return err
}
