// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: periods.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO academic_periods (semester, course_id, period_start, period_end, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, semester, course_id, period_start, period_end, is_active, created_at, updated_at
`

type CreatePeriodParams struct {
	Semester    string             `json:"semester"`
	CourseID    pgtype.UUID        `json:"course_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    pgtype.Bool        `json:"is_active"`
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, createPeriod,
		arg.Semester,
		arg.CourseID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IsActive,
	)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePeriod = `-- name: DeletePeriod :exec
DELETE FROM academic_periods WHERE id = $1
`

func (q *Queries) DeletePeriod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePeriod, id)
	return err
}

const getCourseSpecificPeriod = `-- name: GetCourseSpecificPeriod :one
SELECT id, semester, course_id, period_start, period_end, is_active, created_at, updated_at
FROM academic_periods
WHERE semester = $1 AND course_id = $2 AND is_active = true
LIMIT 1
`

type GetCourseSpecificPeriodParams struct {
	Semester string      `json:"semester"`
	CourseID pgtype.UUID `json:"course_id"`
}

func (q *Queries) GetCourseSpecificPeriod(ctx context.Context, arg GetCourseSpecificPeriodParams) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, getCourseSpecificPeriod, arg.Semester, arg.CourseID)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGlobalPeriod = `-- name: GetGlobalPeriod :one
SELECT id, semester, course_id, period_start, period_end, is_active, created_at, updated_at
FROM academic_periods
WHERE semester = $1 AND course_id IS NULL AND is_active = true
LIMIT 1
`

func (q *Queries) GetGlobalPeriod(ctx context.Context, semester string) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, getGlobalPeriod, semester)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeriodByID = `-- name: GetPeriodByID :one
SELECT id, semester, course_id, period_start, period_end, is_active, created_at, updated_at
FROM academic_periods
WHERE id = $1
`

func (q *Queries) GetPeriodByID(ctx context.Context, id uuid.UUID) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, getPeriodByID, id)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPeriods = `-- name: ListAllPeriods :many
SELECT id, semester, course_id, period_start, period_end, is_active, created_at, updated_at
FROM academic_periods
ORDER BY semester DESC, created_at DESC
`

func (q *Queries) ListAllPeriods(ctx context.Context) ([]AcademicPeriod, error) {
	rows, err := q.db.Query(ctx, listAllPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicPeriod{}
	for rows.Next() {
		var i AcademicPeriod
		if err := rows.Scan(
			&i.ID,
			&i.Semester,
			&i.CourseID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodsBySemester = `-- name: ListPeriodsBySemester :many
SELECT id, semester, course_id, period_start, period_end, is_active, created_at, updated_at
FROM academic_periods
WHERE semester = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPeriodsBySemester(ctx context.Context, semester string) ([]AcademicPeriod, error) {
	rows, err := q.db.Query(ctx, listPeriodsBySemester, semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicPeriod{}
	for rows.Next() {
		var i AcademicPeriod
		if err := rows.Scan(
			&i.ID,
			&i.Semester,
			&i.CourseID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeriod = `-- name: UpdatePeriod :one
UPDATE academic_periods
SET period_end = COALESCE($1, period_end),
    is_active  = COALESCE($2, is_active),
    updated_at = NOW()
WHERE id = $3
RETURNING id, semester, course_id, period_start, period_end, is_active, created_at, updated_at
`

type UpdatePeriodParams struct {
	PeriodEnd pgtype.Timestamptz `json:"period_end"`
	IsActive  pgtype.Bool        `json:"is_active"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) UpdatePeriod(ctx context.Context, arg UpdatePeriodParams) (AcademicPeriod, error) {
	row := q.db.QueryRow(ctx, updatePeriod, arg.PeriodEnd, arg.IsActive, arg.ID)
	var i AcademicPeriod
	err := row.Scan(
		&i.ID,
		&i.Semester,
		&i.CourseID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
