// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prerequisite_courses_cache.sql

package db

import (
	"context"
)

const isPrerequisiteCourse = `-- name: IsPrerequisiteCourse :one
SELECT EXISTS(
    SELECT 1 FROM prerequisite_courses_cache
    WHERE course_code = $1
) as is_prerequisite
`

func (q *Queries) IsPrerequisiteCourse(ctx context.Context, courseCode string) (bool, error) {
	row := q.db.QueryRow(ctx, isPrerequisiteCourse, courseCode)
	var is_prerequisite bool
	err := row.Scan(&is_prerequisite)
	return is_prerequisite, err
}
