// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cafeterias.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCafeteria = `-- name: CreateCafeteria :one
INSERT INTO meal.cafeterias (name, location, has_vegan_menu, serves_dinner, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, location, has_vegan_menu, serves_dinner, is_active, created_at, updated_at
`

type CreateCafeteriaParams struct {
	Name         string `json:"name"`
	Location     string `json:"location"`
	HasVeganMenu bool   `json:"has_vegan_menu"`
	ServesDinner bool   `json:"serves_dinner"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) CreateCafeteria(ctx context.Context, arg CreateCafeteriaParams) (Cafeteria, error) {
	row := q.db.QueryRow(ctx, createCafeteria,
		arg.Name,
		arg.Location,
		arg.HasVeganMenu,
		arg.ServesDinner,
		arg.IsActive,
	)
	var i Cafeteria
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.HasVeganMenu,
		&i.ServesDinner,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCafeteria = `-- name: DeactivateCafeteria :one
UPDATE meal.cafeterias
SET is_active = false, updated_at = NOW()
WHERE id = $1
RETURNING id
`

func (q *Queries) DeactivateCafeteria(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deactivateCafeteria, id)
	err := row.Scan(&id)
	return id, err
}

const getActiveCafeterias = `-- name: GetActiveCafeterias :many
SELECT id, name, location, has_vegan_menu, serves_dinner, is_active, created_at, updated_at
FROM meal.cafeterias
WHERE is_active = true
ORDER BY name ASC
`

func (q *Queries) GetActiveCafeterias(ctx context.Context) ([]Cafeteria, error) {
	rows, err := q.db.Query(ctx, getActiveCafeterias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cafeteria{}
	for rows.Next() {
		var i Cafeteria
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.HasVeganMenu,
			&i.ServesDinner,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCafeterias = `-- name: GetAllCafeterias :many
SELECT id, name, location, has_vegan_menu, serves_dinner, is_active, created_at, updated_at
FROM meal.cafeterias
ORDER BY name ASC
`

func (q *Queries) GetAllCafeterias(ctx context.Context) ([]Cafeteria, error) {
	rows, err := q.db.Query(ctx, getAllCafeterias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cafeteria{}
	for rows.Next() {
		var i Cafeteria
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.HasVeganMenu,
			&i.ServesDinner,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCafeteriaByID = `-- name: GetCafeteriaByID :one
SELECT id, name, location, has_vegan_menu, serves_dinner, is_active, created_at, updated_at
FROM meal.cafeterias
WHERE id = $1
`

func (q *Queries) GetCafeteriaByID(ctx context.Context, id pgtype.UUID) (Cafeteria, error) {
	row := q.db.QueryRow(ctx, getCafeteriaByID, id)
	var i Cafeteria
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.HasVeganMenu,
		&i.ServesDinner,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCafeteria = `-- name: UpdateCafeteria :one
UPDATE meal.cafeterias
SET name = $2, location = $3, has_vegan_menu = $4, serves_dinner = $5, is_active = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, location, has_vegan_menu, serves_dinner, is_active, created_at, updated_at
`

type UpdateCafeteriaParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Location     string      `json:"location"`
	HasVeganMenu bool        `json:"has_vegan_menu"`
	ServesDinner bool        `json:"serves_dinner"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpdateCafeteria(ctx context.Context, arg UpdateCafeteriaParams) (Cafeteria, error) {
	row := q.db.QueryRow(ctx, updateCafeteria,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.HasVeganMenu,
		arg.ServesDinner,
		arg.IsActive,
	)
	var i Cafeteria
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.HasVeganMenu,
		&i.ServesDinner,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
