// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monthly_menus.sql

package db

import (
	"context"
)

const getMonthlyMenu = `-- name: GetMonthlyMenu :one
SELECT id, year, month, menu_data, created_at, updated_at
FROM meal.monthly_menus
WHERE year = $1 AND month = $2
`

type GetMonthlyMenuParams struct {
	Year  int16 `json:"year"`
	Month int16 `json:"month"`
}

func (q *Queries) GetMonthlyMenu(ctx context.Context, arg GetMonthlyMenuParams) (MonthlyMenu, error) {
	row := q.db.QueryRow(ctx, getMonthlyMenu, arg.Year, arg.Month)
	var i MonthlyMenu
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.MenuData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMonthlyMenu = `-- name: UpsertMonthlyMenu :one
INSERT INTO meal.monthly_menus (year, month, menu_data)
VALUES ($1, $2, $3)
ON CONFLICT (year, month) DO UPDATE
SET menu_data = EXCLUDED.menu_data, updated_at = NOW()
RETURNING id, year, month, menu_data, created_at, updated_at
`

type UpsertMonthlyMenuParams struct {
	Year     int16  `json:"year"`
	Month    int16  `json:"month"`
	MenuData []byte `json:"menu_data"`
}

func (q *Queries) UpsertMonthlyMenu(ctx context.Context, arg UpsertMonthlyMenuParams) (MonthlyMenu, error) {
	row := q.db.QueryRow(ctx, upsertMonthlyMenu, arg.Year, arg.Month, arg.MenuData)
	var i MonthlyMenu
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.Month,
		&i.MenuData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
