// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO meal.outbox_events (aggregate_id, aggregate_type, event_type, payload, max_retries)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, aggregate_id, aggregate_type, event_type, payload, status, retry_count, max_retries, next_retry_at, last_error, created_at, published_at
`

type CreateOutboxEventParams struct {
	AggregateID   pgtype.UUID `json:"aggregate_id"`
	AggregateType string      `json:"aggregate_type"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
	MaxRetries    int16       `json:"max_retries"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.MaxRetries,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getFailedOutboxEvents = `-- name: GetFailedOutboxEvents :many
SELECT id, aggregate_id, aggregate_type, event_type, payload, status, retry_count, max_retries, next_retry_at, last_error, created_at, published_at
FROM meal.outbox_events
WHERE status = 'failed'
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) GetFailedOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getFailedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, aggregate_id, aggregate_type, event_type, payload, status, retry_count, max_retries, next_retry_at, last_error, created_at, published_at
FROM meal.outbox_events
WHERE status = 'pending'
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE meal.outbox_events
SET status = 'failed', last_error = $2, retry_count = retry_count + 1
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.LastError)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE meal.outbox_events
SET status = 'published', published_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const retryFailedOutboxEvent = `-- name: RetryFailedOutboxEvent :exec
UPDATE meal.outbox_events
SET status = 'pending', next_retry_at = NOW(), retry_count = 0
WHERE id = $1
`

func (q *Queries) RetryFailedOutboxEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, retryFailedOutboxEvent, id)
	return err
}

const updateOutboxEventRetry = `-- name: UpdateOutboxEventRetry :exec
UPDATE meal.outbox_events
SET retry_count = retry_count + 1, next_retry_at = $2, last_error = $3
WHERE id = $1
`

type UpdateOutboxEventRetryParams struct {
	ID          pgtype.UUID        `json:"id"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	LastError   pgtype.Text        `json:"last_error"`
}

func (q *Queries) UpdateOutboxEventRetry(ctx context.Context, arg UpdateOutboxEventRetryParams) error {
	_, err := q.db.Exec(ctx, updateOutboxEventRetry, arg.ID, arg.NextRetryAt, arg.LastError)
	return err
}
