// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldProcessedEvents = `-- name: CleanupOldProcessedEvents :exec
DELETE FROM meal.processed_events
WHERE processed_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) CleanupOldProcessedEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldProcessedEvents)
	return err
}

const createProcessedEvent = `-- name: CreateProcessedEvent :exec
INSERT INTO meal.processed_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type CreateProcessedEventParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	EventType string      `json:"event_type"`
}

func (q *Queries) CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) error {
	_, err := q.db.Exec(ctx, createProcessedEvent, arg.EventID, arg.EventType)
	return err
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS(SELECT 1 FROM meal.processed_events WHERE event_id = $1)
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
