// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReservation = `-- name: CancelReservation :one
UPDATE meal.reservations
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1
RETURNING id, batch_id, student_id, cafeteria_id, reservation_date, meal_time, menu_type, status, is_used, used_at, expires_at, created_at, updated_at
`

func (q *Queries) CancelReservation(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, cancelReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StudentID,
		&i.CafeteriaID,
		&i.ReservationDate,
		&i.MealTime,
		&i.MenuType,
		&i.Status,
		&i.IsUsed,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkActiveReservation = `-- name: CheckActiveReservation :one
SELECT id, status
FROM meal.reservations
WHERE student_id = $1 AND reservation_date = $2 AND meal_time = $3
  AND status IN ('pending', 'confirmed')
LIMIT 1
`

type CheckActiveReservationParams struct {
	StudentID       pgtype.UUID  `json:"student_id"`
	ReservationDate pgtype.Date  `json:"reservation_date"`
	MealTime        MealTimeEnum `json:"meal_time"`
}

type CheckActiveReservationRow struct {
	ID     pgtype.UUID           `json:"id"`
	Status ReservationStatusEnum `json:"status"`
}

func (q *Queries) CheckActiveReservation(ctx context.Context, arg CheckActiveReservationParams) (CheckActiveReservationRow, error) {
	row := q.db.QueryRow(ctx, checkActiveReservation, arg.StudentID, arg.ReservationDate, arg.MealTime)
	var i CheckActiveReservationRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const checkActiveReservationsForSlots = `-- name: CheckActiveReservationsForSlots :many
SELECT r.id, r.reservation_date, r.meal_time, r.status, c.name AS cafeteria_name
FROM meal.reservations r
JOIN meal.cafeterias c ON r.cafeteria_id = c.id
WHERE r.student_id = $1
  AND r.status IN ('pending', 'confirmed')
  AND (r.reservation_date, r.meal_time::text) IN (
    SELECT unnest($2::date[]), unnest($3::text[])
  )
`

type CheckActiveReservationsForSlotsParams struct {
	StudentID pgtype.UUID   `json:"student_id"`
	Dates     []pgtype.Date `json:"dates"`
	MealTimes []string      `json:"meal_times"`
}

type CheckActiveReservationsForSlotsRow struct {
	ID              pgtype.UUID           `json:"id"`
	ReservationDate pgtype.Date           `json:"reservation_date"`
	MealTime        MealTimeEnum          `json:"meal_time"`
	Status          ReservationStatusEnum `json:"status"`
	CafeteriaName   string                `json:"cafeteria_name"`
}

// Batch variant of CheckActiveReservation. Accepts parallel arrays of dates and
// meal times and returns any existing active rows for (student_id, date, meal).
func (q *Queries) CheckActiveReservationsForSlots(ctx context.Context, arg CheckActiveReservationsForSlotsParams) ([]CheckActiveReservationsForSlotsRow, error) {
	rows, err := q.db.Query(ctx, checkActiveReservationsForSlots, arg.StudentID, arg.Dates, arg.MealTimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckActiveReservationsForSlotsRow{}
	for rows.Next() {
		var i CheckActiveReservationsForSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationDate,
			&i.MealTime,
			&i.Status,
			&i.CafeteriaName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupExpiredReservations = `-- name: CleanupExpiredReservations :exec
WITH cleanup_batch AS (
    SELECT id FROM meal.reservations
    WHERE status = 'expired' AND expires_at < NOW() - INTERVAL '7 days'
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
DELETE FROM meal.reservations
WHERE id IN (SELECT id FROM cleanup_batch)
`

func (q *Queries) CleanupExpiredReservations(ctx context.Context, limit int32) error {
	_, err := q.db.Exec(ctx, cleanupExpiredReservations, limit)
	return err
}

const countStudentReservationsFiltered = `-- name: CountStudentReservationsFiltered :one
SELECT COUNT(*) as total
FROM meal.reservations r
WHERE r.student_id = $1
  AND ($2::date IS NULL OR r.reservation_date >= $2)
  AND ($3::date IS NULL OR r.reservation_date <= $3)
  AND ($4::meal.reservation_status_enum IS NULL OR r.status = $4)
`

type CountStudentReservationsFilteredParams struct {
	StudentID pgtype.UUID               `json:"student_id"`
	Column2   pgtype.Date               `json:"column_2"`
	Column3   pgtype.Date               `json:"column_3"`
	Status    NullReservationStatusEnum `json:"status"`
}

func (q *Queries) CountStudentReservationsFiltered(ctx context.Context, arg CountStudentReservationsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentReservationsFiltered,
		arg.StudentID,
		arg.Column2,
		arg.Column3,
		arg.Status,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO meal.reservations (batch_id, student_id, cafeteria_id, reservation_date, meal_time, menu_type, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, batch_id, student_id, cafeteria_id, reservation_date, meal_time, menu_type, status, is_used, used_at, expires_at, created_at, updated_at
`

type CreateReservationParams struct {
	BatchID         pgtype.UUID           `json:"batch_id"`
	StudentID       pgtype.UUID           `json:"student_id"`
	CafeteriaID     pgtype.UUID           `json:"cafeteria_id"`
	ReservationDate pgtype.Date           `json:"reservation_date"`
	MealTime        MealTimeEnum          `json:"meal_time"`
	MenuType        MenuTypeEnum          `json:"menu_type"`
	Status          ReservationStatusEnum `json:"status"`
	ExpiresAt       pgtype.Timestamptz    `json:"expires_at"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.BatchID,
		arg.StudentID,
		arg.CafeteriaID,
		arg.ReservationDate,
		arg.MealTime,
		arg.MenuType,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StudentID,
		&i.CafeteriaID,
		&i.ReservationDate,
		&i.MealTime,
		&i.MenuType,
		&i.Status,
		&i.IsUsed,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expirePendingReservations = `-- name: ExpirePendingReservations :exec
WITH expired_batch AS (
    SELECT id FROM meal.reservations
    WHERE status = 'pending' AND expires_at < NOW()
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE meal.reservations
SET status = 'expired', updated_at = NOW()
WHERE id IN (SELECT id FROM expired_batch)
`

func (q *Queries) ExpirePendingReservations(ctx context.Context, limit int32) error {
	_, err := q.db.Exec(ctx, expirePendingReservations, limit)
	return err
}

const findReservationForQR = `-- name: FindReservationForQR :one
SELECT r.id, r.batch_id, r.student_id, r.cafeteria_id, r.reservation_date, r.meal_time, r.menu_type, r.status, r.is_used, r.used_at, r.expires_at, r.created_at, r.updated_at,
       c.name as cafeteria_name, c.location as cafeteria_location
FROM meal.reservations r
JOIN meal.cafeterias c ON r.cafeteria_id = c.id
WHERE r.cafeteria_id = $1
  AND r.reservation_date = $2
  AND r.meal_time = $3
  AND r.student_id = $4
  AND r.status = 'confirmed'
  AND r.is_used = false
LIMIT 1
`

type FindReservationForQRParams struct {
	CafeteriaID     pgtype.UUID  `json:"cafeteria_id"`
	ReservationDate pgtype.Date  `json:"reservation_date"`
	MealTime        MealTimeEnum `json:"meal_time"`
	StudentID       pgtype.UUID  `json:"student_id"`
}

type FindReservationForQRRow struct {
	ID                pgtype.UUID           `json:"id"`
	BatchID           pgtype.UUID           `json:"batch_id"`
	StudentID         pgtype.UUID           `json:"student_id"`
	CafeteriaID       pgtype.UUID           `json:"cafeteria_id"`
	ReservationDate   pgtype.Date           `json:"reservation_date"`
	MealTime          MealTimeEnum          `json:"meal_time"`
	MenuType          MenuTypeEnum          `json:"menu_type"`
	Status            ReservationStatusEnum `json:"status"`
	IsUsed            bool                  `json:"is_used"`
	UsedAt            pgtype.Timestamptz    `json:"used_at"`
	ExpiresAt         pgtype.Timestamptz    `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz    `json:"updated_at"`
	CafeteriaName     string                `json:"cafeteria_name"`
	CafeteriaLocation string                `json:"cafeteria_location"`
}

func (q *Queries) FindReservationForQR(ctx context.Context, arg FindReservationForQRParams) (FindReservationForQRRow, error) {
	row := q.db.QueryRow(ctx, findReservationForQR,
		arg.CafeteriaID,
		arg.ReservationDate,
		arg.MealTime,
		arg.StudentID,
	)
	var i FindReservationForQRRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StudentID,
		&i.CafeteriaID,
		&i.ReservationDate,
		&i.MealTime,
		&i.MenuType,
		&i.Status,
		&i.IsUsed,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CafeteriaName,
		&i.CafeteriaLocation,
	)
	return i, err
}

const getReservationByID = `-- name: GetReservationByID :one
SELECT r.id, r.batch_id, r.student_id, r.cafeteria_id, r.reservation_date, r.meal_time, r.menu_type, r.status, r.is_used, r.used_at, r.expires_at, r.created_at, r.updated_at,
       c.name as cafeteria_name, c.location as cafeteria_location
FROM meal.reservations r
JOIN meal.cafeterias c ON r.cafeteria_id = c.id
WHERE r.id = $1
`

type GetReservationByIDRow struct {
	ID                pgtype.UUID           `json:"id"`
	BatchID           pgtype.UUID           `json:"batch_id"`
	StudentID         pgtype.UUID           `json:"student_id"`
	CafeteriaID       pgtype.UUID           `json:"cafeteria_id"`
	ReservationDate   pgtype.Date           `json:"reservation_date"`
	MealTime          MealTimeEnum          `json:"meal_time"`
	MenuType          MenuTypeEnum          `json:"menu_type"`
	Status            ReservationStatusEnum `json:"status"`
	IsUsed            bool                  `json:"is_used"`
	UsedAt            pgtype.Timestamptz    `json:"used_at"`
	ExpiresAt         pgtype.Timestamptz    `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz    `json:"updated_at"`
	CafeteriaName     string                `json:"cafeteria_name"`
	CafeteriaLocation string                `json:"cafeteria_location"`
}

func (q *Queries) GetReservationByID(ctx context.Context, id pgtype.UUID) (GetReservationByIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationByID, id)
	var i GetReservationByIDRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StudentID,
		&i.CafeteriaID,
		&i.ReservationDate,
		&i.MealTime,
		&i.MenuType,
		&i.Status,
		&i.IsUsed,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CafeteriaName,
		&i.CafeteriaLocation,
	)
	return i, err
}

const getStudentReservations = `-- name: GetStudentReservations :many
SELECT r.id, r.batch_id, r.student_id, r.cafeteria_id, r.reservation_date, r.meal_time, r.menu_type, r.status, r.is_used, r.used_at, r.expires_at, r.created_at, r.updated_at,
       c.name as cafeteria_name, c.location as cafeteria_location
FROM meal.reservations r
JOIN meal.cafeterias c ON r.cafeteria_id = c.id
WHERE r.student_id = $1
ORDER BY r.reservation_date DESC, r.meal_time ASC
`

type GetStudentReservationsRow struct {
	ID                pgtype.UUID           `json:"id"`
	BatchID           pgtype.UUID           `json:"batch_id"`
	StudentID         pgtype.UUID           `json:"student_id"`
	CafeteriaID       pgtype.UUID           `json:"cafeteria_id"`
	ReservationDate   pgtype.Date           `json:"reservation_date"`
	MealTime          MealTimeEnum          `json:"meal_time"`
	MenuType          MenuTypeEnum          `json:"menu_type"`
	Status            ReservationStatusEnum `json:"status"`
	IsUsed            bool                  `json:"is_used"`
	UsedAt            pgtype.Timestamptz    `json:"used_at"`
	ExpiresAt         pgtype.Timestamptz    `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz    `json:"updated_at"`
	CafeteriaName     string                `json:"cafeteria_name"`
	CafeteriaLocation string                `json:"cafeteria_location"`
}

func (q *Queries) GetStudentReservations(ctx context.Context, studentID pgtype.UUID) ([]GetStudentReservationsRow, error) {
	rows, err := q.db.Query(ctx, getStudentReservations, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentReservationsRow{}
	for rows.Next() {
		var i GetStudentReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.StudentID,
			&i.CafeteriaID,
			&i.ReservationDate,
			&i.MealTime,
			&i.MenuType,
			&i.Status,
			&i.IsUsed,
			&i.UsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CafeteriaName,
			&i.CafeteriaLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentReservationsFiltered = `-- name: GetStudentReservationsFiltered :many
SELECT r.id, r.batch_id, r.student_id, r.cafeteria_id, r.reservation_date, r.meal_time, r.menu_type, r.status, r.is_used, r.used_at, r.expires_at, r.created_at, r.updated_at,
       c.name as cafeteria_name, c.location as cafeteria_location
FROM meal.reservations r
JOIN meal.cafeterias c ON r.cafeteria_id = c.id
WHERE r.student_id = $1
  AND ($2::date IS NULL OR r.reservation_date >= $2)
  AND ($3::date IS NULL OR r.reservation_date <= $3)
  AND ($6::meal.reservation_status_enum IS NULL OR r.status = $6)
ORDER BY r.reservation_date DESC, r.meal_time ASC
LIMIT NULLIF($4, 0) OFFSET $5
`

type GetStudentReservationsFilteredParams struct {
	StudentID pgtype.UUID               `json:"student_id"`
	Column2   pgtype.Date               `json:"column_2"`
	Column3   pgtype.Date               `json:"column_3"`
	Column4   interface{}               `json:"column_4"`
	Offset    int32                     `json:"offset"`
	Status    NullReservationStatusEnum `json:"status"`
}

type GetStudentReservationsFilteredRow struct {
	ID                pgtype.UUID           `json:"id"`
	BatchID           pgtype.UUID           `json:"batch_id"`
	StudentID         pgtype.UUID           `json:"student_id"`
	CafeteriaID       pgtype.UUID           `json:"cafeteria_id"`
	ReservationDate   pgtype.Date           `json:"reservation_date"`
	MealTime          MealTimeEnum          `json:"meal_time"`
	MenuType          MenuTypeEnum          `json:"menu_type"`
	Status            ReservationStatusEnum `json:"status"`
	IsUsed            bool                  `json:"is_used"`
	UsedAt            pgtype.Timestamptz    `json:"used_at"`
	ExpiresAt         pgtype.Timestamptz    `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz    `json:"updated_at"`
	CafeteriaName     string                `json:"cafeteria_name"`
	CafeteriaLocation string                `json:"cafeteria_location"`
}

func (q *Queries) GetStudentReservationsFiltered(ctx context.Context, arg GetStudentReservationsFilteredParams) ([]GetStudentReservationsFilteredRow, error) {
	rows, err := q.db.Query(ctx, getStudentReservationsFiltered,
		arg.StudentID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentReservationsFilteredRow{}
	for rows.Next() {
		var i GetStudentReservationsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.StudentID,
			&i.CafeteriaID,
			&i.ReservationDate,
			&i.MealTime,
			&i.MenuType,
			&i.Status,
			&i.IsUsed,
			&i.UsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CafeteriaName,
			&i.CafeteriaLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReservationUsed = `-- name: MarkReservationUsed :one
UPDATE meal.reservations
SET is_used = true, used_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, batch_id, student_id, cafeteria_id, reservation_date, meal_time, menu_type, status, is_used, used_at, expires_at, created_at, updated_at
`

func (q *Queries) MarkReservationUsed(ctx context.Context, id pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, markReservationUsed, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StudentID,
		&i.CafeteriaID,
		&i.ReservationDate,
		&i.MealTime,
		&i.MenuType,
		&i.Status,
		&i.IsUsed,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservationByID = `-- name: UpdateReservationByID :one
UPDATE meal.reservations
SET status = $2, expires_at = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, batch_id, student_id, cafeteria_id, reservation_date, meal_time, menu_type, status, is_used, used_at, expires_at, created_at, updated_at
`

type UpdateReservationByIDParams struct {
	ID        pgtype.UUID           `json:"id"`
	Status    ReservationStatusEnum `json:"status"`
	ExpiresAt pgtype.Timestamptz    `json:"expires_at"`
}

func (q *Queries) UpdateReservationByID(ctx context.Context, arg UpdateReservationByIDParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, updateReservationByID, arg.ID, arg.Status, arg.ExpiresAt)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.StudentID,
		&i.CafeteriaID,
		&i.ReservationDate,
		&i.MealTime,
		&i.MenuType,
		&i.Status,
		&i.IsUsed,
		&i.UsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReservationsByBatchID = `-- name: UpdateReservationsByBatchID :exec
UPDATE meal.reservations
SET status = $2, expires_at = $3, updated_at = NOW()
WHERE batch_id = $1
`

type UpdateReservationsByBatchIDParams struct {
	BatchID   pgtype.UUID           `json:"batch_id"`
	Status    ReservationStatusEnum `json:"status"`
	ExpiresAt pgtype.Timestamptz    `json:"expires_at"`
}

func (q *Queries) UpdateReservationsByBatchID(ctx context.Context, arg UpdateReservationsByBatchIDParams) error {
	_, err := q.db.Exec(ctx, updateReservationsByBatchID, arg.BatchID, arg.Status, arg.ExpiresAt)
	return err
}
