// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students_view.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateStudentCache = `-- name: DeactivateStudentCache :exec
UPDATE meal.students_view
SET is_active = false, synced_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStudentCache(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateStudentCache, id)
	return err
}

const deleteStudentCache = `-- name: DeleteStudentCache :exec
DELETE FROM meal.students_view
WHERE id = $1
`

func (q *Queries) DeleteStudentCache(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStudentCache, id)
	return err
}

const getStudentCacheByID = `-- name: GetStudentCacheByID :one
SELECT id, student_number, first_name, last_name, is_active, synced_at
FROM meal.students_view
WHERE id = $1
`

func (q *Queries) GetStudentCacheByID(ctx context.Context, id pgtype.UUID) (StudentView, error) {
	row := q.db.QueryRow(ctx, getStudentCacheByID, id)
	var i StudentView
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.SyncedAt,
	)
	return i, err
}

const upsertStudentCache = `-- name: UpsertStudentCache :one
INSERT INTO meal.students_view (id, student_number, first_name, last_name, is_active, synced_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE
SET student_number = EXCLUDED.student_number,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    is_active = EXCLUDED.is_active,
    synced_at = NOW()
RETURNING id, student_number, first_name, last_name, is_active, synced_at
`

type UpsertStudentCacheParams struct {
	ID            pgtype.UUID `json:"id"`
	StudentNumber string      `json:"student_number"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	IsActive      bool        `json:"is_active"`
}

func (q *Queries) UpsertStudentCache(ctx context.Context, arg UpsertStudentCacheParams) (StudentView, error) {
	row := q.db.QueryRow(ctx, upsertStudentCache,
		arg.ID,
		arg.StudentNumber,
		arg.FirstName,
		arg.LastName,
		arg.IsActive,
	)
	var i StudentView
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.SyncedAt,
	)
	return i, err
}
