// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEnrollment = `-- name: CheckEnrollment :one
SELECT COUNT(*) as count
FROM enrollments_cache
WHERE student_id = $1 AND course_id = $2 AND semester = $3
`

type CheckEnrollmentParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	Semester  string      `json:"semester"`
}

func (q *Queries) CheckEnrollment(ctx context.Context, arg CheckEnrollmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkEnrollment, arg.StudentID, arg.CourseID, arg.Semester)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnrollmentCache = `-- name: CreateEnrollmentCache :exec
INSERT INTO enrollments_cache (student_id, course_id, semester)
VALUES ($1, $2, $3)
ON CONFLICT (student_id, course_id) DO NOTHING
`

type CreateEnrollmentCacheParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	Semester  string      `json:"semester"`
}

func (q *Queries) CreateEnrollmentCache(ctx context.Context, arg CreateEnrollmentCacheParams) error {
	_, err := q.db.Exec(ctx, createEnrollmentCache, arg.StudentID, arg.CourseID, arg.Semester)
	return err
}

const getEnrolledStudentsByCourse = `-- name: GetEnrolledStudentsByCourse :many
SELECT
    s.id,
    s.student_number,
    s.first_name,
    s.last_name,
    s.email,
    s.department,
    s.is_active
FROM enrollments_cache e
JOIN students_cache s ON e.student_id = s.id
WHERE e.course_id = $1 AND e.semester = $2
`

type GetEnrolledStudentsByCourseParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Semester string      `json:"semester"`
}

type GetEnrolledStudentsByCourseRow struct {
	ID            pgtype.UUID `json:"id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	Email         pgtype.Text `json:"email"`
	Department    pgtype.Text `json:"department"`
	IsActive      pgtype.Bool `json:"is_active"`
}

func (q *Queries) GetEnrolledStudentsByCourse(ctx context.Context, arg GetEnrolledStudentsByCourseParams) ([]GetEnrolledStudentsByCourseRow, error) {
	rows, err := q.db.Query(ctx, getEnrolledStudentsByCourse, arg.CourseID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnrolledStudentsByCourseRow{}
	for rows.Next() {
		var i GetEnrolledStudentsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Department,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentEnrollmentsBySemester = `-- name: GetStudentEnrollmentsBySemester :many
SELECT
    c.id as course_id,
    c.course_code,
    c.course_name,
    c.instructor_fullname,
    c.total_weeks,
    c.semester
FROM enrollments_cache e
JOIN courses_cache c ON e.course_id = c.id
WHERE e.student_id = $1 AND e.semester = $2
`

type GetStudentEnrollmentsBySemesterParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Semester  string      `json:"semester"`
}

type GetStudentEnrollmentsBySemesterRow struct {
	CourseID           pgtype.UUID `json:"course_id"`
	CourseCode         string      `json:"course_code"`
	CourseName         string      `json:"course_name"`
	InstructorFullname pgtype.Text `json:"instructor_fullname"`
	TotalWeeks         pgtype.Int2 `json:"total_weeks"`
	Semester           string      `json:"semester"`
}

func (q *Queries) GetStudentEnrollmentsBySemester(ctx context.Context, arg GetStudentEnrollmentsBySemesterParams) ([]GetStudentEnrollmentsBySemesterRow, error) {
	rows, err := q.db.Query(ctx, getStudentEnrollmentsBySemester, arg.StudentID, arg.Semester)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentEnrollmentsBySemesterRow{}
	for rows.Next() {
		var i GetStudentEnrollmentsBySemesterRow
		if err := rows.Scan(
			&i.CourseID,
			&i.CourseCode,
			&i.CourseName,
			&i.InstructorFullname,
			&i.TotalWeeks,
			&i.Semester,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
