// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxStatusEnum string

const (
	OutboxStatusEnumPending   OutboxStatusEnum = "pending"
	OutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	OutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type SessionTypeEnum string

const (
	SessionTypeEnumTheory SessionTypeEnum = "theory"
	SessionTypeEnumLab    SessionTypeEnum = "lab"
)

func (e *SessionTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionTypeEnum(s)
	case string:
		*e = SessionTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionTypeEnum: %T", src)
	}
	return nil
}

type NullSessionTypeEnum struct {
	SessionTypeEnum SessionTypeEnum `json:"session_type_enum"`
	Valid           bool            `json:"valid"` // Valid is true if SessionTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SessionTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionTypeEnum), nil
}

type AcademicPeriod struct {
	ID          pgtype.UUID        `json:"id"`
	Semester    string             `json:"semester"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceRecord struct {
	ID               pgtype.UUID      `json:"id"`
	SessionID        pgtype.UUID      `json:"session_id"`
	StudentID        pgtype.UUID      `json:"student_id"`
	CourseID         pgtype.UUID      `json:"course_id"`
	Semester         string           `json:"semester"`
	WeekNumber       int16            `json:"week_number"`
	MarkedVia        string           `json:"marked_via"`
	ScannedAt        pgtype.Timestamp `json:"scanned_at"`
	QrTimestamp      pgtype.Int8      `json:"qr_timestamp"`
	ManuallyMarkedBy pgtype.UUID      `json:"manually_marked_by"`
	ManuallyMarkedAt pgtype.Timestamp `json:"manually_marked_at"`
	ManualNote       pgtype.Text      `json:"manual_note"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	SessionType      SessionTypeEnum  `json:"session_type"`
}

type AttendanceSession struct {
	ID                 pgtype.UUID      `json:"id"`
	CourseID           pgtype.UUID      `json:"course_id"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	Semester           string           `json:"semester"`
	WeekNumber         int16            `json:"week_number"`
	SessionDate        pgtype.Date      `json:"session_date"`
	QrSecret           string           `json:"qr_secret"`
	QrRotationInterval pgtype.Int2      `json:"qr_rotation_interval"`
	StartedAt          pgtype.Timestamp `json:"started_at"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	IsActive           pgtype.Bool      `json:"is_active"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	SessionType        SessionTypeEnum  `json:"session_type"`
}

type CoursesCache struct {
	ID                 pgtype.UUID      `json:"id"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	Credits            int16            `json:"credits"`
	Semester           string           `json:"semester"`
	Department         pgtype.Text      `json:"department"`
	InstructorID       pgtype.UUID      `json:"instructor_id"`
	InstructorFullname pgtype.Text      `json:"instructor_fullname"`
	TotalWeeks         pgtype.Int2      `json:"total_weeks"`
	SyncedAt           pgtype.Timestamp `json:"synced_at"`
	HasLab             bool             `json:"has_lab"`
}

type EnrollmentsCache struct {
	ID        pgtype.UUID      `json:"id"`
	StudentID pgtype.UUID      `json:"student_id"`
	CourseID  pgtype.UUID      `json:"course_id"`
	Semester  string           `json:"semester"`
	SyncedAt  pgtype.Timestamp `json:"synced_at"`
}

type OutboxEvent struct {
	ID           pgtype.UUID          `json:"id"`
	EventType    string               `json:"event_type"`
	RoutingKey   string               `json:"routing_key"`
	Payload      []byte               `json:"payload"`
	Status       NullOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2          `json:"retry_count"`
	MaxRetries   pgtype.Int2          `json:"max_retries"`
	CreatedAt    pgtype.Timestamp     `json:"created_at"`
	ProcessedAt  pgtype.Timestamp     `json:"processed_at"`
	ErrorMessage pgtype.Text          `json:"error_message"`
}

type ProcessedEvent struct {
	EventID     pgtype.UUID      `json:"event_id"`
	EventType   string           `json:"event_type"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type StudentsCache struct {
	ID            pgtype.UUID      `json:"id"`
	StudentNumber string           `json:"student_number"`
	FirstName     pgtype.Text      `json:"first_name"`
	LastName      pgtype.Text      `json:"last_name"`
	Email         pgtype.Text      `json:"email"`
	Department    pgtype.Text      `json:"department"`
	IsActive      pgtype.Bool      `json:"is_active"`
	SyncedAt      pgtype.Timestamp `json:"synced_at"`
}
