// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEventProcessed = `-- name: CheckEventProcessed :one
SELECT COUNT(*) as count
FROM processed_events
WHERE event_id = $1
`

func (q *Queries) CheckEventProcessed(ctx context.Context, eventID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, checkEventProcessed, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProcessedEvent = `-- name: CreateProcessedEvent :exec
INSERT INTO processed_events (event_id, event_type)
VALUES ($1, $2)
ON CONFLICT (event_id) DO NOTHING
`

type CreateProcessedEventParams struct {
	EventID   pgtype.UUID `json:"event_id"`
	EventType string      `json:"event_type"`
}

func (q *Queries) CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) error {
	_, err := q.db.Exec(ctx, createProcessedEvent, arg.EventID, arg.EventType)
	return err
}
