// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: students_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateStudentCache = `-- name: DeactivateStudentCache :exec
UPDATE students_cache
SET is_active = FALSE, synced_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStudentCache(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateStudentCache, id)
	return err
}

const getStudentCacheByID = `-- name: GetStudentCacheByID :one
SELECT id, student_number, first_name, last_name, email, department, is_active, synced_at
FROM students_cache
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStudentCacheByID(ctx context.Context, id pgtype.UUID) (StudentsCache, error) {
	row := q.db.QueryRow(ctx, getStudentCacheByID, id)
	var i StudentsCache
	err := row.Scan(
		&i.ID,
		&i.StudentNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Department,
		&i.IsActive,
		&i.SyncedAt,
	)
	return i, err
}

const upsertStudentCache = `-- name: UpsertStudentCache :exec
INSERT INTO students_cache (
    id, student_number, first_name, last_name, email, department, is_active, synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
) ON CONFLICT (id) DO UPDATE SET
    student_number = EXCLUDED.student_number,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    department = EXCLUDED.department,
    is_active = EXCLUDED.is_active,
    synced_at = NOW()
`

type UpsertStudentCacheParams struct {
	ID            pgtype.UUID `json:"id"`
	StudentNumber string      `json:"student_number"`
	FirstName     pgtype.Text `json:"first_name"`
	LastName      pgtype.Text `json:"last_name"`
	Email         pgtype.Text `json:"email"`
	Department    pgtype.Text `json:"department"`
	IsActive      pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpsertStudentCache(ctx context.Context, arg UpsertStudentCacheParams) error {
	_, err := q.db.Exec(ctx, upsertStudentCache,
		arg.ID,
		arg.StudentNumber,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Department,
		arg.IsActive,
	)
	return err
}
