// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID          int32            `json:"id"`
	EventType   string           `json:"event_type"`
	RoutingKey  string           `json:"routing_key"`
	Payload     []byte           `json:"payload"`
	Processed   bool             `json:"processed"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type Staff struct {
	ID             pgtype.UUID      `json:"id"`
	Email          string           `json:"email"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Role           string           `json:"role"`
	Department     pgtype.Text      `json:"department"`
	Phone          pgtype.Text      `json:"phone"`
	OfficeLocation pgtype.Text      `json:"office_location"`
	IsActive       bool             `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}
