// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (event_type, routing_key, payload)
VALUES ($1, $2, $3)
RETURNING id, event_type, routing_key, payload, processed, created_at, processed_at
`

type CreateOutboxEventParams struct {
	EventType  string `json:"event_type"`
	RoutingKey string `json:"routing_key"`
	Payload    []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.RoutingKey, arg.Payload)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RoutingKey,
		&i.Payload,
		&i.Processed,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getUnprocessedEvents = `-- name: GetUnprocessedEvents :many
SELECT id, event_type, routing_key, payload, processed, created_at, processed_at
FROM outbox_events
WHERE processed = false
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetUnprocessedEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getUnprocessedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RoutingKey,
			&i.Payload,
			&i.Processed,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE outbox_events
SET processed = true, processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEventProcessed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, markEventProcessed, id)
	return err
}
