// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStaff = `-- name: CountStaff :one
SELECT COUNT(*) FROM staff WHERE is_active = true
`

func (q *Queries) CountStaff(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaff)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (email, first_name, last_name, role, department, phone, office_location)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, email, first_name, last_name, role, department, phone, office_location, is_active, deleted_at, created_at, updated_at
`

type CreateStaffParams struct {
	Email          string      `json:"email"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	Role           string      `json:"role"`
	Department     pgtype.Text `json:"department"`
	Phone          pgtype.Text `json:"phone"`
	OfficeLocation pgtype.Text `json:"office_location"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.Department,
		arg.Phone,
		arg.OfficeLocation,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Department,
		&i.Phone,
		&i.OfficeLocation,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT id, email, first_name, last_name, role, department, phone, office_location, is_active, deleted_at, created_at, updated_at
FROM staff
WHERE email = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetStaffByEmail(ctx context.Context, email string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByEmail, email)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Department,
		&i.Phone,
		&i.OfficeLocation,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, email, first_name, last_name, role, department, phone, office_location, is_active, deleted_at, created_at, updated_at
FROM staff
WHERE id = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetStaffByID(ctx context.Context, id pgtype.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Department,
		&i.Phone,
		&i.OfficeLocation,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, email, first_name, last_name, role, department, phone, office_location, is_active, deleted_at, created_at, updated_at
FROM staff
WHERE is_active = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStaffParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListStaff(ctx context.Context, arg ListStaffParams) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaff, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.Department,
			&i.Phone,
			&i.OfficeLocation,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteStaff = `-- name: SoftDeleteStaff :exec
UPDATE staff
SET is_active = false, deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteStaff(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStaff, id)
	return err
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staff
SET department = COALESCE($2, department),
    phone = COALESCE($3, phone),
    office_location = COALESCE($4, office_location),
    updated_at = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, email, first_name, last_name, role, department, phone, office_location, is_active, deleted_at, created_at, updated_at
`

type UpdateStaffParams struct {
	ID             pgtype.UUID `json:"id"`
	Department     pgtype.Text `json:"department"`
	Phone          pgtype.Text `json:"phone"`
	OfficeLocation pgtype.Text `json:"office_location"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.ID,
		arg.Department,
		arg.Phone,
		arg.OfficeLocation,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Department,
		&i.Phone,
		&i.OfficeLocation,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
