// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxStatusEnum string

const (
	OutboxStatusEnumPending   OutboxStatusEnum = "pending"
	OutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	OutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type OutboxEvent struct {
	EventType    string               `json:"event_type"`
	RoutingKey   string               `json:"routing_key"`
	Payload      []byte               `json:"payload"`
	CreatedAt    pgtype.Timestamp     `json:"created_at"`
	ProcessedAt  pgtype.Timestamp     `json:"processed_at"`
	Status       NullOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2          `json:"retry_count"`
	MaxRetries   pgtype.Int2          `json:"max_retries"`
	ErrorMessage pgtype.Text          `json:"error_message"`
	ID           pgtype.UUID          `json:"id"`
}

type Staff struct {
	ID             pgtype.UUID      `json:"id"`
	Email          string           `json:"email"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Role           string           `json:"role"`
	Department     pgtype.Text      `json:"department"`
	Phone          pgtype.Text      `json:"phone"`
	OfficeLocation pgtype.Text      `json:"office_location"`
	IsActive       bool             `json:"is_active"`
	DeletedAt      pgtype.Timestamp `json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type TeacherProfile struct {
	ID               pgtype.UUID      `json:"id"`
	StaffID          pgtype.UUID      `json:"staff_id"`
	AcademicTitle    pgtype.Text      `json:"academic_title"`
	Faculty          pgtype.Text      `json:"faculty"`
	ProfileImageUrl  pgtype.Text      `json:"profile_image_url"`
	Education        []byte           `json:"education"`
	Articles         []byte           `json:"articles"`
	Bulletins        []byte           `json:"bulletins"`
	Projects         []byte           `json:"projects"`
	Awards           []byte           `json:"awards"`
	Scholarships     []byte           `json:"scholarships"`
	AdminAssignments []byte           `json:"admin_assignments"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}
