import type { CourseCatalog, AvailableCourse, EnrollmentProgramResponse, Faculty, Department } from '@/lib/types';

// DEU Fakülte ve Bölüm Yapısı
export const mockFaculties: Faculty[] = [
  {
    id: 'fac-buca-egitim',
    name: 'Buca Eğitim Fakültesi',
    code: 'BEF',
    departments: [
      { id: 'dept-bote', name: 'Bilgisayar ve Öğretim Teknolojileri Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'BOTE' },
      { id: 'dept-rpd', name: 'Rehberlik ve Psikolojik Danışmanlık', facultyId: 'fac-buca-egitim', code: 'RPD' },
      { id: 'dept-muzik-ogr', name: 'Müzik Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'MUZ' },
      { id: 'dept-resim-ogr', name: 'Resim-İş Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'RES' },
      { id: 'dept-biyoloji-ogr', name: 'Biyoloji Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'BIYO' },
      { id: 'dept-fen-ogr', name: 'Fen Bilgisi Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'FEN' },
      { id: 'dept-fizik-ogr', name: 'Fizik Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'FIZ' },
      { id: 'dept-ilkmat-ogr', name: 'İlköğretim Matematik Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'IMAT' },
      { id: 'dept-kimya-ogr', name: 'Kimya Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'KIM' },
      { id: 'dept-mat-ogr', name: 'Matematik Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'MAT' },
      { id: 'dept-ozel-egitim', name: 'Özel Eğitim Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'OZE' },
      { id: 'dept-okul-oncesi', name: 'Okul Öncesi Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'OKO' },
      { id: 'dept-sinif-ogr', name: 'Sınıf Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'SNF' },
      { id: 'dept-cografya-ogr', name: 'Coğrafya Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'COG' },
      { id: 'dept-sosyal-ogr', name: 'Sosyal Bilgiler Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'SOS' },
      { id: 'dept-tarih-ogr', name: 'Tarih Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'TAR' },
      { id: 'dept-turk-edebiyat-ogr', name: 'Türk Dili ve Edebiyatı Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'TDE' },
      { id: 'dept-turkce-ogr', name: 'Türkçe Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'TUR' },
      { id: 'dept-almanca-ogr', name: 'Almanca Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'ALM' },
      { id: 'dept-fransizca-ogr', name: 'Fransızca Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'FRA' },
      { id: 'dept-ingilizce-ogr', name: 'İngilizce Öğretmenliği', facultyId: 'fac-buca-egitim', code: 'ING' },
    ],
  },
  {
    id: 'fac-denizcilik',
    name: 'Denizcilik Fakültesi',
    code: 'DNZ',
    departments: [
      { id: 'dept-deniz-ulastirma', name: 'Deniz Ulaştırma İşletme Mühendisliği', facultyId: 'fac-denizcilik', code: 'DUI' },
      { id: 'dept-denizcilik-isl', name: 'Denizcilik İşletmeleri Yönetimi', facultyId: 'fac-denizcilik', code: 'DIY' },
      { id: 'dept-gemi-makineleri', name: 'Gemi Makineleri İşletme Mühendisliği', facultyId: 'fac-denizcilik', code: 'GMI' },
      { id: 'dept-lojistik', name: 'Lojistik Yönetimi', facultyId: 'fac-denizcilik', code: 'LOJ' },
    ],
  },
  {
    id: 'fac-konservatuar',
    name: 'Devlet Konservatuvarı',
    code: 'KNS',
    departments: [
      { id: 'dept-kompozisyon', name: 'Kompozisyon ve Orkestra Şefliği', facultyId: 'fac-konservatuar', code: 'KOM' },
      { id: 'dept-piyano', name: 'Piyano', facultyId: 'fac-konservatuar', code: 'PYN' },
      { id: 'dept-uflemeli', name: 'Üflemeli ve Vurmalı Çalgılar', facultyId: 'fac-konservatuar', code: 'UFC' },
      { id: 'dept-yayli', name: 'Yaylı Çalgılar', facultyId: 'fac-konservatuar', code: 'YAY' },
      { id: 'dept-bale', name: 'Bale', facultyId: 'fac-konservatuar', code: 'BAL' },
      { id: 'dept-opera', name: 'Opera', facultyId: 'fac-konservatuar', code: 'OPR' },
    ],
  },
  {
    id: 'fac-dis',
    name: 'Diş Hekimliği Fakültesi',
    code: 'DIS',
    departments: [
      { id: 'dept-dis-hekimligi', name: 'Diş Hekimliği', facultyId: 'fac-dis', code: 'DSH' },
    ],
  },
  {
    id: 'fac-edebiyat',
    name: 'Edebiyat Fakültesi',
    code: 'EDB',
    departments: [
      { id: 'dept-amerikan', name: 'Amerikan Kültürü ve Edebiyatı', facultyId: 'fac-edebiyat', code: 'AMR' },
      { id: 'dept-arkeoloji', name: 'Arkeoloji', facultyId: 'fac-edebiyat', code: 'ARK' },
      { id: 'dept-dilbilimi', name: 'Dilbilimi', facultyId: 'fac-edebiyat', code: 'DIL' },
      { id: 'dept-felsefe', name: 'Felsefe', facultyId: 'fac-edebiyat', code: 'FLS' },
      { id: 'dept-ing-mutercim', name: 'İngilizce Mütercim ve Tercümanlık', facultyId: 'fac-edebiyat', code: 'IMT' },
      { id: 'dept-karsil-edebiyat', name: 'Karşılaştırmalı Edebiyat', facultyId: 'fac-edebiyat', code: 'KRE' },
      { id: 'dept-muzecilik', name: 'Müzecilik', facultyId: 'fac-edebiyat', code: 'MZC' },
      { id: 'dept-psikoloji', name: 'Psikoloji', facultyId: 'fac-edebiyat', code: 'PSK' },
      { id: 'dept-rus', name: 'Rus Dili ve Edebiyatı', facultyId: 'fac-edebiyat', code: 'RUS' },
      { id: 'dept-sosyoloji', name: 'Sosyoloji', facultyId: 'fac-edebiyat', code: 'SOS' },
      { id: 'dept-tarih', name: 'Tarih', facultyId: 'fac-edebiyat', code: 'TAR' },
      { id: 'dept-turk-dili-edebiyati', name: 'Türk Dili ve Edebiyatı', facultyId: 'fac-edebiyat', code: 'TDE' },
    ],
  },
  {
    id: 'fac-fen',
    name: 'Fen Fakültesi',
    code: 'FEN',
    departments: [
      { id: 'dept-bil', name: 'Bilgisayar Bilimleri', facultyId: 'fac-fen', code: 'BIL', description: 'Bilgisayar Bilimleri Lisans Programı' },
      { id: 'dept-biyoloji', name: 'Biyoloji', facultyId: 'fac-fen', code: 'BYO' },
      { id: 'dept-fizik', name: 'Fizik', facultyId: 'fac-fen', code: 'FIZ', description: 'Fizik Lisans Programı' },
      { id: 'dept-istatistik', name: 'İstatistik', facultyId: 'fac-fen', code: 'IST' },
      { id: 'dept-kimya', name: 'Kimya', facultyId: 'fac-fen', code: 'KIM' },
      { id: 'dept-matematik', name: 'Matematik', facultyId: 'fac-fen', code: 'MAT', description: 'Matematik Lisans Programı' },
    ],
  },
  {
    id: 'fac-fizik-tedavi',
    name: 'Fizik Tedavi ve Rehabilitasyon Fakültesi',
    code: 'FTR',
    departments: [
      { id: 'dept-fizyoterapi', name: 'Fizyoterapi ve Rehabilitasyon', facultyId: 'fac-fizik-tedavi', code: 'FZY' },
    ],
  },
  {
    id: 'fac-guzel-sanatlar',
    name: 'Güzel Sanatlar Fakültesi',
    code: 'GSF',
    departments: [
      { id: 'dept-cizgi-film', name: 'Çizgi Film ve Animasyon', facultyId: 'fac-guzel-sanatlar', code: 'CFA' },
      { id: 'dept-film-tasarim', name: 'Film Tasarımı ve Yönetmenliği', facultyId: 'fac-guzel-sanatlar', code: 'FTY' },
      { id: 'dept-fotograf', name: 'Fotoğraf', facultyId: 'fac-guzel-sanatlar', code: 'FOT' },
      { id: 'dept-geleneksel', name: 'Geleneksel Türk Sanatları', facultyId: 'fac-guzel-sanatlar', code: 'GTS' },
      { id: 'dept-grafik', name: 'Grafik Sanatlar', facultyId: 'fac-guzel-sanatlar', code: 'GRF' },
      { id: 'dept-heykel', name: 'Heykel', facultyId: 'fac-guzel-sanatlar', code: 'HYK' },
      { id: 'dept-kurgu', name: 'Kurgu, Ses ve Görüntü Yönetimi', facultyId: 'fac-guzel-sanatlar', code: 'KSG' },
      { id: 'dept-moda', name: 'Moda Giyim Tasarımı', facultyId: 'fac-guzel-sanatlar', code: 'MGT' },
      { id: 'dept-muzikoloji', name: 'Müzikoloji', facultyId: 'fac-guzel-sanatlar', code: 'MZK' },
      { id: 'dept-resim', name: 'Resim', facultyId: 'fac-guzel-sanatlar', code: 'RSM' },
      { id: 'dept-sahne', name: 'Sahne Sanatları', facultyId: 'fac-guzel-sanatlar', code: 'SHS' },
      { id: 'dept-seramik', name: 'Seramik ve Cam', facultyId: 'fac-guzel-sanatlar', code: 'SRC' },
      { id: 'dept-tekstil-moda', name: 'Tekstil ve Moda Tasarımı', facultyId: 'fac-guzel-sanatlar', code: 'TMT' },
    ],
  },
  {
    id: 'fac-hemsirelik',
    name: 'Hemşirelik Fakültesi',
    code: 'HMS',
    departments: [
      { id: 'dept-hemsirelik', name: 'Hemşirelik', facultyId: 'fac-hemsirelik', code: 'HEM' },
    ],
  },
  {
    id: 'fac-hukuk',
    name: 'Hukuk Fakültesi',
    code: 'HKK',
    departments: [
      { id: 'dept-hukuk', name: 'Hukuk', facultyId: 'fac-hukuk', code: 'HUK' },
    ],
  },
  {
    id: 'fac-iibf',
    name: 'İktisadi ve İdari Bilimler Fakültesi',
    code: 'IIB',
    departments: [
      { id: 'dept-calisma-eko', name: 'Çalışma Ekonomisi ve Endüstri İlişkileri', facultyId: 'fac-iibf', code: 'CEE' },
      { id: 'dept-ekonometri', name: 'Ekonometri', facultyId: 'fac-iibf', code: 'EKO' },
      { id: 'dept-iktisat', name: 'İktisat', facultyId: 'fac-iibf', code: 'IKT' },
      { id: 'dept-isletme', name: 'İşletme', facultyId: 'fac-iibf', code: 'ISL' },
      { id: 'dept-kamu', name: 'Kamu Yönetimi', facultyId: 'fac-iibf', code: 'KAM' },
      { id: 'dept-maliye', name: 'Maliye', facultyId: 'fac-iibf', code: 'MLY' },
      { id: 'dept-ybs', name: 'Yönetim Bilişim Sistemleri', facultyId: 'fac-iibf', code: 'YBS' },
    ],
  },
  {
    id: 'fac-ilahiyat',
    name: 'İlahiyat Fakültesi',
    code: 'ILH',
    departments: [
      { id: 'dept-ilahiyat', name: 'İlahiyat', facultyId: 'fac-ilahiyat', code: 'ILA' },
      { id: 'dept-din-kulturu-ogr', name: 'İlköğretim Din Kültürü ve Ahlak Bilgisi Öğretmenliği', facultyId: 'fac-ilahiyat', code: 'DKO' },
    ],
  },
  {
    id: 'fac-isletme',
    name: 'İşletme Fakültesi',
    code: 'ISF',
    departments: [
      { id: 'dept-isf-iktisat', name: 'İktisat', facultyId: 'fac-isletme', code: 'IKT' },
      { id: 'dept-isf-isletme', name: 'İşletme', facultyId: 'fac-isletme', code: 'ISL' },
      { id: 'dept-siyaset', name: 'Siyaset Bilimi ve Uluslararası İlişkiler', facultyId: 'fac-isletme', code: 'SBU' },
      { id: 'dept-turizm-isl', name: 'Turizm İşletmeciliği', facultyId: 'fac-isletme', code: 'TUR' },
      { id: 'dept-uluslar-iliski', name: 'Uluslararası İlişkiler', facultyId: 'fac-isletme', code: 'UIL' },
      { id: 'dept-uluslar-ticaret', name: 'Uluslararası İşletmecilik ve Ticaret', facultyId: 'fac-isletme', code: 'UIT' },
    ],
  },
  {
    id: 'fac-mimarlik',
    name: 'Mimarlık Fakültesi',
    code: 'MIM',
    departments: [
      { id: 'dept-mimarlik', name: 'Mimarlık', facultyId: 'fac-mimarlik', code: 'MIM' },
      { id: 'dept-sehir-planlama', name: 'Şehir ve Bölge Planlama', facultyId: 'fac-mimarlik', code: 'SBP' },
    ],
  },
  {
    id: 'fac-muhendislik',
    name: 'Mühendislik Fakültesi',
    code: 'MUH',
    departments: [
      { id: 'dept-bilgisayar-muh', name: 'Bilgisayar Mühendisliği', facultyId: 'fac-muhendislik', code: 'BMH', description: 'Bilgisayar Mühendisliği Lisans Programı' },
      { id: 'dept-cevre-muh', name: 'Çevre Mühendisliği', facultyId: 'fac-muhendislik', code: 'CEV' },
      { id: 'dept-elektrik-muh', name: 'Elektrik-Elektronik Mühendisliği', facultyId: 'fac-muhendislik', code: 'ELK', description: 'Elektrik-Elektronik Mühendisliği Lisans Programı' },
      { id: 'dept-elektronik-hab', name: 'Elektronik ve Haberleşme Mühendisliği', facultyId: 'fac-muhendislik', code: 'EHM' },
      { id: 'dept-endustri-muh', name: 'Endüstri Mühendisliği', facultyId: 'fac-muhendislik', code: 'END' },
      { id: 'dept-insaat-muh', name: 'İnşaat Mühendisliği', facultyId: 'fac-muhendislik', code: 'INS' },
      { id: 'dept-jeofizik-muh', name: 'Jeofizik Mühendisliği', facultyId: 'fac-muhendislik', code: 'JFZ' },
      { id: 'dept-jeoloji-muh', name: 'Jeoloji Mühendisliği', facultyId: 'fac-muhendislik', code: 'JEO' },
      { id: 'dept-maden-muh', name: 'Maden Mühendisliği', facultyId: 'fac-muhendislik', code: 'MAD' },
      { id: 'dept-makina-muh', name: 'Makina Mühendisliği', facultyId: 'fac-muhendislik', code: 'MAK', description: 'Makina Mühendisliği Lisans Programı' },
      { id: 'dept-metalurji-muh', name: 'Metalurji ve Malzeme Mühendisliği', facultyId: 'fac-muhendislik', code: 'MET' },
      { id: 'dept-tekstil-muh', name: 'Tekstil Mühendisliği', facultyId: 'fac-muhendislik', code: 'TKS' },
    ],
  },
  {
    id: 'fac-spor',
    name: 'Necat Hepkon Spor Bilimleri Fakültesi',
    code: 'SPR',
    departments: [
      { id: 'dept-antrenorluk', name: 'Antrenörlük Eğitimi', facultyId: 'fac-spor', code: 'ANT' },
      { id: 'dept-beden-ogr', name: 'Beden Eğitimi ve Spor Öğretmenliği', facultyId: 'fac-spor', code: 'BES' },
      { id: 'dept-rekreasyon', name: 'Rekreasyon', facultyId: 'fac-spor', code: 'REK' },
      { id: 'dept-spor-yonetim', name: 'Spor Yöneticiliği', facultyId: 'fac-spor', code: 'SPY' },
    ],
  },
  {
    id: 'fac-tip',
    name: 'Tıp Fakültesi',
    code: 'TIP',
    departments: [
      { id: 'dept-tip', name: 'Tıp', facultyId: 'fac-tip', code: 'TIP' },
    ],
  },
  {
    id: 'fac-turizm',
    name: 'Turizm Fakültesi',
    code: 'TRZ',
    departments: [
      { id: 'dept-gastronomi', name: 'Gastronomi ve Mutfak Sanatları', facultyId: 'fac-turizm', code: 'GMS' },
      { id: 'dept-turizm-isletme', name: 'Turizm İşletmeciliği', facultyId: 'fac-turizm', code: 'TUR' },
    ],
  },
  {
    id: 'fac-veteriner',
    name: 'Veteriner Fakültesi',
    code: 'VET',
    departments: [
      { id: 'dept-veteriner', name: 'Veteriner Hekimliği', facultyId: 'fac-veteriner', code: 'VET' },
    ],
  },
];

// Backward compatibility - flat departments list
export const mockDepartments: Department[] = mockFaculties.flatMap(f => f.departments);

// DEU Bilgisayar Bilimleri Müfredatı - Tam Liste
export const mockCourseCatalog: CourseCatalog[] = [
  // ============ 1. DÖNEM (GÜZ) - ZORUNLU ============
  {
    id: 'bil-1-ata1001',
    course_code: 'ATA 1001',
    name: 'Atatürk İlkeleri ve İnkılap Tarihi I',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    offering_unit: 'Atatürk İlkeleri ve İnkılap Tarihi Enstitüsü',
    class_level: 1,
    semester: 1,
    credits: 2,
    theoretical_hours: 2,
    lab_hours: 0,
    ects: 2,
    course_type: 'mandatory',
    education_level: 'Lisans',
    teaching_type: 'Örgün Öğretim',
    language: 'Türkçe',
    coordinator: {
      title: 'Prof. Dr.',
      name: 'Fevzi Çakmak',
      email: 'fevzi.cakmak@deu.edu.tr',
      phone: '(0232) 301 79 36',
      office: 'Atatürk İlkeleri ve İnkılap Tarihi Enstitüsü, Tınaztepe Yerleşkesi, 35390 Buca-İZMİR',
    },
    purpose: 'İmparatorluktan milli devlete geçişte, Türk toplumunun gelişim aşamalarını öğrencilere kavratmak',
    learning_outcomes_list: [
      'Türk devriminin temelini oluşturan genel kavramları ana hatlarıyla izah edebilme',
      'Osmanlı Devleti\'nin batılılaşma hareketlerinin amaç, yöntem ve sonuçlarını anlatabilme',
      'Osmanlı Devleti\'nin son döneminde yaşanan iç ve dış politikadaki gelişmeleri kavrayabilme',
      'Birinci Dünya Savaşı\'nın Osmanlı Devleti\'ne etkilerini anlayabilme',
      'Milli Mücadele sürecinde yaşanan siyasi, askeri, ekonomik ve toplumsal olayları iredeleyebilme',
    ],
    weekly_topics: [
      { week: 1, topic: 'Kavramlar: Devlet, Monarşi, Oligarşi, Cumhuriyet, Laiklik, Demokrasi, İhtilal, Devrim, Ulus-devlet' },
      { week: 2, topic: 'Batı Modernleşme Tarihi: Feodalizm, Haçlı Seferleri, Coğrafi Keşifler, Rönesans ve Reform Hareketleri, Fransız İhtilali, Sanayi Devrimi' },
      { week: 3, topic: 'Osmanlı-Türk Modernleşmesi (1876 yılı Meşrutiyet\'in İlanına Kadar)' },
      { week: 4, topic: 'Osmanlı-Türk Modernleşmesi (II. Meşrutiyet Dönemi Sonuna Kadar-1918)' },
      { week: 5, topic: '19. Yüzyıldan 20. Yüzyıla uluslararası arenada yaşanan rekabet ve bunun Osmanlı Devleti\'ne yansımaları: Emperyalizm, sömürgecilik, milliyetçilik ve bloklaşma' },
      { week: 6, topic: 'Trablusgarp ve Balkan Savaşları' },
      { week: 7, topic: 'Birinci Dünya Savaşı\'na Gidilen Süreç ve Osmanlı Devleti' },
      { week: 8, topic: 'Birinci Dünya Savaşı\'nda Cepheler' },
      { week: 9, topic: 'Mondros Ateşkes Antlaşması ve işgal süreci' },
      { week: 10, topic: 'Birinci Dünya Savaşı Sonrası Anadolu\'da Mevcut Durum, Yaşanan Gelişmeler ve Kuva-yı Milliye Hareketi' },
      { week: 11, topic: 'Mustafa Kemal Atatürk\'ün Samsun\'a Çıkışı ve Milli Mücadelenin Örgütlenme Süreci: Kongreler' },
      { week: 12, topic: 'Türkiye Büyük Millet Meclisi\'nin Açılması ve Yasama Faaliyetleri' },
      { week: 13, topic: 'Düzenli Ordunun Kurulması ve Askeri Mücedele Safhası: Doğu, Güney ve Batı Cephesinde Yaşanan Askeri Gelişmeler' },
      { week: 14, topic: '30 Ağustos Büyük Taarruz ve Mudanya Ateşkes Antlaşması' },
    ],
    recommended_sources: [
      'Mustafa Kemal Atatürk, Nutuk',
      'Kemal Arı, Başlangıçtan Günümüze Türk Devrim Tarihi',
      'Ahmet Mumcu, Atatürk İlkeleri ve İnkılâp Tarihi-1',
      'Ergun Aybars, Türkiye Cumhuriyeti Tarihi',
      'Türkiye Cumhuriyeti Tarihi-I (Komisyon), Atatürk Araştırma Merkezi Yay.',
      'İlber Ortaylı, İmparatorluğun En Uzun Yüzyılı',
      'Ahmet Mumcu, Tarih Açısından Türk Devriminin Temelleri ve Gelişimi',
      'Şerafettin Turan, Türk Devrim Tarihi',
      'Niyazi Berkes, Türkiye\'de Çağdaşlaşma',
    ],
    prerequisites: [],
    description: 'İmparatorluktan milli devlete geçişte, Türk toplumunun gelişim aşamalarını öğrencilere kavratmak',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-bil1005',
    course_code: 'BİL 1005',
    name: 'Ayrık Matematik ve Mantık',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 6,
    theoretical_hours: 4,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Mantık, kümeler, ilişkiler, fonksiyonlar, sayma yöntemleri, matematiksel tümevarım',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-bil1007',
    course_code: 'BİL 1007',
    name: 'Bilgi Teknolojileri ve Uygulamaları',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 4,
    theoretical_hours: 2,
    ects: 4,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Temel bilgisayar kullanımı, ofis uygulamaları, internet teknolojileri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-bil1011',
    course_code: 'BİL 1011',
    name: 'Bilgisayar Bilimlerine Giriş I',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 6,
    theoretical_hours: 2,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Programlamaya giriş, Python ile temel algoritmalar ve problem çözme',
    learning_outcomes: 'Temel programlama kavramlarını anlama ve uygulama becerisi kazanma',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-bil1013',
    course_code: 'BİL 1013',
    name: 'Teknik İngilizce I',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Bilgisayar bilimleri alanında teknik İngilizce okuma ve yazma becerileri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-fsh0001',
    course_code: 'FSH 0001',
    name: 'İletişim Becerileri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Etkili iletişim, sunum teknikleri, yazılı ve sözlü iletişim becerileri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-fsh0002',
    course_code: 'FSH 0002',
    name: 'Mesleksel Değerler ve Etik',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Mesleki etik, bilişim etiği, sosyal sorumluluk',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-kpd1000',
    course_code: 'KPD 1000',
    name: 'Kariyer Planlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 2,
    theoretical_hours: 1,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Kariyer planlaması, iş arama teknikleri, özgeçmiş hazırlama',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-mat1009',
    course_code: 'MAT 1009',
    name: 'Matematik I',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 6,
    theoretical_hours: 4,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Limit, süreklilik, türev ve uygulamaları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-1-ydi1007',
    course_code: 'YDİ 1007',
    name: 'Yabancı Dil I (İngilizce)',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 1,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Temel İngilizce dilbilgisi ve iletişim becerileri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // ============ 2. DÖNEM (BAHAR) - ZORUNLU ============
  {
    id: 'bil-2-ata1002',
    course_code: 'ATA 1002',
    name: 'Atatürk İlkeleri ve İnkılap Tarihi II',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-1-ata1001', course_code: 'ATA 1001', course_name: 'Atatürk İlkeleri ve İnkılap Tarihi I' }],
    description: 'Türkiye Cumhuriyetinin kuruluşu, Atatürk ilkeleri ve inkılaplar',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-bil1004',
    course_code: 'BİL 1004',
    name: 'Teknik İngilizce II',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 3,
    theoretical_hours: 2,
    ects: 3,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-1-bil1013', course_code: 'BİL 1013', course_name: 'Teknik İngilizce I' }],
    description: 'İleri düzey teknik İngilizce, bilimsel makale okuma ve yazma',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-bil1006',
    course_code: 'BİL 1006',
    name: 'Doğrusal Cebir ve Sayısal Geometri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 6,
    theoretical_hours: 4,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Matrisler, determinantlar, vektör uzayları, lineer dönüşümler',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-bil1012',
    course_code: 'BİL 1012',
    name: 'Bilgisayar Bilimlerine Giriş II',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 7,
    theoretical_hours: 2,
    ects: 7,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-1-bil1011', course_code: 'BİL 1011', course_name: 'Bilgisayar Bilimlerine Giriş I' }],
    description: 'İleri programlama teknikleri, veri yapılarına giriş',
    learning_outcomes: 'Orta düzey programlama becerileri ve algoritma tasarımı',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-bil1014',
    course_code: 'BİL 1014',
    name: 'İstatistiğe Giriş',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 4,
    theoretical_hours: 3,
    ects: 4,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Temel istatistik kavramları, olasılık, dağılımlar, hipotez testleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-mat1010',
    course_code: 'MAT 1010',
    name: 'Matematik II',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 6,
    theoretical_hours: 4,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-1-mat1009', course_code: 'MAT 1009', course_name: 'Matematik I' }],
    description: 'İntegral, seriler, çok değişkenli fonksiyonlar',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-ydi1006',
    course_code: 'YDİ 1006',
    name: 'Yabancı Dil II (İngilizce)',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-1-ydi1007', course_code: 'YDİ 1007', course_name: 'Yabancı Dil I (İngilizce)' }],
    description: 'Orta düzey İngilizce dilbilgisi ve iletişim becerileri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // 2. DÖNEM - SEÇMELİ
  {
    id: 'bil-2-bde1003',
    course_code: 'BDE 1003',
    name: 'Beden Eğitimi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'elective',
    prerequisites: [],
    description: 'Temel spor aktiviteleri ve sağlıklı yaşam',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-gsh1003',
    course_code: 'GSH 1003',
    name: 'Halk Oyunları',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'elective',
    prerequisites: [],
    description: 'Türk halk oyunları ve kültürel miras',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-gsm1003',
    course_code: 'GSM 1003',
    name: 'Müzik',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'elective',
    prerequisites: [],
    description: 'Temel müzik teorisi ve uygulama',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-2-gsr1003',
    course_code: 'GSR 1003',
    name: 'Resim',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 1,
    semester: 2,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'elective',
    prerequisites: [],
    description: 'Temel resim teknikleri ve sanat tarihi',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // ============ 3. DÖNEM (GÜZ) - ZORUNLU ============
  {
    id: 'bil-3-bil2009',
    course_code: 'BİL 2009',
    name: 'Çizge Kuramı',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 3,
    credits: 6,
    theoretical_hours: 4,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-1-bil1005', course_code: 'BİL 1005', course_name: 'Ayrık Matematik ve Mantık' }],
    description: 'Graf teorisi, ağaçlar, Euler ve Hamilton yolları, renklendirme',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-3-bil2011',
    course_code: 'BİL 2011',
    name: 'Algoritmalar ve Veri Yapıları',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 3,
    credits: 6,
    theoretical_hours: 2,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-2-bil1012', course_code: 'BİL 1012', course_name: 'Bilgisayar Bilimlerine Giriş II' }],
    description: 'Temel veri yapıları (dizi, bağlı liste, yığın, kuyruk, ağaç, graf), sıralama ve arama algoritmaları',
    learning_outcomes: 'Veri yapılarını analiz etme ve uygulama becerisi',
    syllabus: 'Hafta 1-2: Diziler ve Bağlı Listeler, Hafta 3-4: Yığın ve Kuyruk, Hafta 5-7: Ağaçlar, Hafta 8-10: Graf Algoritmaları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-3-bil2013',
    course_code: 'BİL 2013',
    name: 'Sayısal Çözümleme',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 3,
    credits: 6,
    theoretical_hours: 2,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-2-mat1010', course_code: 'MAT 1010', course_name: 'Matematik II' }],
    description: 'Nümerik yöntemler, hata analizi, interpolasyon, sayısal integrasyon',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-3-bil2015',
    course_code: 'BİL 2015',
    name: 'Nesneye Yönelik Analiz ve Tasarım',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 3,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-2-bil1012', course_code: 'BİL 1012', course_name: 'Bilgisayar Bilimlerine Giriş II' }],
    description: 'UML, tasarım kalıpları, yazılım mimarisi',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-3-bil2017',
    course_code: 'BİL 2017',
    name: 'Sayısal Tasarım',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 3,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Dijital mantık, kombinasyonel ve ardışık devreler, VHDL',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-3-tdl1001',
    course_code: 'TDL 1001',
    name: 'Türk Dili I',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 3,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Türk dili tarihi, dilbilgisi kuralları, yazılı anlatım',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // ============ 4. DÖNEM (BAHAR) - ZORUNLU ============
  {
    id: 'bil-4-bil2004',
    course_code: 'BİL 2004',
    name: 'Veritabanı Yönetimi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 4,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-3-bil2011', course_code: 'BİL 2011', course_name: 'Algoritmalar ve Veri Yapıları' }],
    description: 'İlişkisel veritabanı tasarımı, SQL, normalizasyon, transaction yönetimi',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-4-bil2008',
    course_code: 'BİL 2008',
    name: 'İşletim Sistemleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 4,
    credits: 4,
    theoretical_hours: 3,
    ects: 4,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-3-bil2011', course_code: 'BİL 2011', course_name: 'Algoritmalar ve Veri Yapıları' }],
    description: 'Süreç yönetimi, bellek yönetimi, dosya sistemleri, eşzamanlılık',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-4-bil2012',
    course_code: 'BİL 2012',
    name: 'Nesneye Yönelik Programlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 4,
    credits: 7,
    theoretical_hours: 2,
    ects: 7,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-3-bil2015', course_code: 'BİL 2015', course_name: 'Nesneye Yönelik Analiz ve Tasarım' }],
    description: 'Java/C++ ile OOP, kalıtım, polimorfizm, soyutlama, kapsülleme',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-4-bil2014',
    course_code: 'BİL 2014',
    name: 'Çok Değişkenli Veri Analizi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 4,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-2-bil1014', course_code: 'BİL 1014', course_name: 'İstatistiğe Giriş' }],
    description: 'Çok değişkenli istatistik, regresyon analizi, kümeleme',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-4-bil2016',
    course_code: 'BİL 2016',
    name: 'Matematiksel Programlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 4,
    credits: 7,
    theoretical_hours: 2,
    ects: 7,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-2-bil1006', course_code: 'BİL 1006', course_name: 'Doğrusal Cebir ve Sayısal Geometri' }],
    description: 'Lineer programlama, simplex metodu, optimizasyon teknikleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-4-tdl1002',
    course_code: 'TDL 1002',
    name: 'Türk Dili II',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 2,
    semester: 4,
    credits: 2,
    theoretical_hours: 2,
    ects: 2,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-3-tdl1001', course_code: 'TDL 1001', course_name: 'Türk Dili I' }],
    description: 'Sözlü anlatım, kompozisyon, rapor yazma teknikleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // ============ 5. DÖNEM (GÜZ) - ZORUNLU ============
  {
    id: 'bil-5-bil3009',
    course_code: 'BİL 3009',
    name: 'Bulanık Mantık ve Bulanık Kümeler',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 6,
    theoretical_hours: 3,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Bulanık küme teorisi, bulanık mantık, bulanık çıkarım sistemleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3013',
    course_code: 'BİL 3013',
    name: 'Veri Madenciliğine Giriş',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 6,
    theoretical_hours: 2,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-4-bil2004', course_code: 'BİL 2004', course_name: 'Veritabanı Yönetimi' }],
    description: 'Veri ön işleme, sınıflandırma, kümeleme, birliktelik kuralları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3015',
    course_code: 'BİL 3015',
    name: 'Algoritmaların Tasarımı ve Analizi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 6,
    theoretical_hours: 2,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-3-bil2011', course_code: 'BİL 2011', course_name: 'Algoritmalar ve Veri Yapıları' }],
    description: 'Algoritma karmaşıklığı, böl-yönet, dinamik programlama, açgözlü algoritmalar',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // 5. DÖNEM - SEÇMELİ (12 AKTS)
  {
    id: 'bil-5-bil3101',
    course_code: 'BİL 3101',
    name: 'Bilgisayar Grafiği',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: '2D/3D grafik, OpenGL, rendering teknikleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3103',
    course_code: 'BİL 3103',
    name: 'Sayısal Sinyal İşleme',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Dijital sinyal işleme, Fourier dönüşümü, filtreler',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3111',
    course_code: 'BİL 3111',
    name: 'Yazılım Projesi Yönetimi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Proje planlama, risk yönetimi, Agile/Scrum metodolojileri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3113',
    course_code: 'BİL 3113',
    name: 'Görsel Programlama Dilleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'C#, Windows Forms, WPF, GUI tasarımı',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3121',
    course_code: 'BİL 3121',
    name: 'Coğrafi Bilgi Sistemleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'GIS temelleri, mekansal veri analizi, harita uygulamaları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3123',
    course_code: 'BİL 3123',
    name: 'Karar Destek Sistemleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'DSS mimarisi, karar modelleri, iş zekası',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3125',
    course_code: 'BİL 3125',
    name: 'Yöneylem Araştırması',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Optimizasyon, kuyruk teorisi, simülasyon',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3127',
    course_code: 'BİL 3127',
    name: 'Mobil Programlama I',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Android uygulama geliştirme, Kotlin/Java',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-bil3129',
    course_code: 'BİL 3129',
    name: 'Programlama Dilleri Konseptleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Programlama paradigmaları, dil tasarımı, derleyiciler',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-5-fiz3117',
    course_code: 'FİZ 3117',
    name: 'Bilgisayar Bilimleri için Fizik I',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 5,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Mekanik, elektrik, manyetizma temelleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // ============ 6. DÖNEM (BAHAR) - ZORUNLU ============
  {
    id: 'bil-6-bil3006',
    course_code: 'BİL 3006',
    name: 'Kombinatoryal Optimizasyon',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 7,
    theoretical_hours: 4,
    ects: 7,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-5-bil3015', course_code: 'BİL 3015', course_name: 'Algoritmaların Tasarımı ve Analizi' }],
    description: 'Kombinatoryal problemler, yaklaşım algoritmaları, sezgisel yöntemler',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3010',
    course_code: 'BİL 3010',
    name: 'Bilgisayar Organizasyonu',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 7,
    theoretical_hours: 3,
    ects: 7,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-3-bil2017', course_code: 'BİL 2017', course_name: 'Sayısal Tasarım' }],
    description: 'CPU mimarisi, bellek hiyerarşisi, giriş/çıkış sistemleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3012',
    course_code: 'BİL 3012',
    name: 'Bilgisayar Ağları',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 6,
    theoretical_hours: 3,
    ects: 6,
    course_type: 'mandatory',
    prerequisites: [{ id: 'bil-4-bil2008', course_code: 'BİL 2008', course_name: 'İşletim Sistemleri' }],
    description: 'TCP/IP, OSI modeli, ağ protokolleri, routing, soket programlama',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // 6. DÖNEM - SEÇMELİ (10 AKTS)
  {
    id: 'bil-6-bil3102',
    course_code: 'BİL 3102',
    name: 'Metin ve Web Madenciliğine Giriş',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Metin işleme, NLP temelleri, web scraping',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3104',
    course_code: 'BİL 3104',
    name: 'Sayısal Görüntü İşleme',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Görüntü işleme teknikleri, filtreleme, kenar algılama',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3108',
    course_code: 'BİL 3108',
    name: 'Zaman Serisi Madenciliği',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Zaman serisi analizi, tahmin modelleri, anomali tespiti',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3110',
    course_code: 'BİL 3110',
    name: 'Bilimsel Hesaplama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Bilimsel hesaplama yöntemleri, Python/MATLAB uygulamaları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3112',
    course_code: 'BİL 3112',
    name: 'Makine Öğrenimi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Denetimli ve denetimsiz öğrenme, sinir ağları temelleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3114',
    course_code: 'BİL 3114',
    name: 'Yazılım Mühendisliği İlkeleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Yazılım geliştirme süreçleri, kalite güvencesi, dokümantasyon',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3122',
    course_code: 'BİL 3122',
    name: 'Kısıt Programlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Kısıt tatmin problemleri, CSP çözücüler',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3124',
    course_code: 'BİL 3124',
    name: 'Oyun Teorisi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Oyun teorisi temelleri, Nash dengesi, strateji oyunları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3126',
    course_code: 'BİL 3126',
    name: 'Bilgisayar Cebiri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Sembolik hesaplama, cebirsel algoritmalar',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-bil3130',
    course_code: 'BİL 3130',
    name: 'Bulanık Karar Sistemleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [{ id: 'bil-5-bil3009', course_code: 'BİL 3009', course_name: 'Bulanık Mantık ve Bulanık Kümeler' }],
    description: 'Bulanık karar verme, çok kriterli karar analizi',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-6-fiz3118',
    course_code: 'FİZ 3118',
    name: 'Bilgisayar Bilimleri için Fizik II',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 3,
    semester: 6,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [{ id: 'bil-5-fiz3117', course_code: 'FİZ 3117', course_name: 'Bilgisayar Bilimleri için Fizik I' }],
    description: 'Modern fizik, kuantum mekaniği temelleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // ============ 7. DÖNEM (GÜZ) - ZORUNLU ============
  {
    id: 'bil-7-bil4009',
    course_code: 'BİL 4009',
    name: 'Bitirme Projesi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 8,
    theoretical_hours: 2,
    ects: 8,
    course_type: 'mandatory',
    prerequisites: [],
    description: 'Bireysel veya grup halinde yazılım projesi geliştirme',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4091',
    course_code: 'BİL 4091',
    name: 'Staj',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 8,
    theoretical_hours: 0,
    ects: 8,
    course_type: 'mandatory',
    prerequisites: [],
    description: '32 iş günü endüstriyel staj',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // 7. DÖNEM - SEÇMELİ (14 AKTS)
  {
    id: 'bil-7-bil4103',
    course_code: 'BİL 4103',
    name: 'Biyoenformatik',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Biyolojik veri analizi, sekans hizalama, filogeni',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4105',
    course_code: 'BİL 4105',
    name: 'Sistem Analizi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Sistem analizi ve tasarımı, gereksinim mühendisliği',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4107',
    course_code: 'BİL 4107',
    name: 'Bilgisayar Oyunları',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Oyun geliştirme, Unity/Unreal Engine, oyun fiziği',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4111',
    course_code: 'BİL 4111',
    name: 'Yazılım Tasarımı',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'İleri tasarım kalıpları, mimari stiller, SOLID prensipleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4115',
    course_code: 'BİL 4115',
    name: 'Yazılım Sınama ve Doğrulama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Test teknikleri, otomatik test, kod kalitesi',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4117',
    course_code: 'BİL 4117',
    name: 'Nesnelerin İnterneti Temelleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'IoT mimarisi, sensörler, protokoller, bulut entegrasyonu',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4119',
    course_code: 'BİL 4119',
    name: 'Web Programlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Modern web teknolojileri, React, Node.js, REST API',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4121',
    course_code: 'BİL 4121',
    name: 'Benzetim Teknikleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Simülasyon modelleme, Monte Carlo yöntemleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4123',
    course_code: 'BİL 4123',
    name: 'Esnek Hesaplama Teknikleri',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Genetik algoritmalar, yapay sinir ağları, bulanık sistemler',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4125',
    course_code: 'BİL 4125',
    name: 'Yazılımlarda Hata Ayıklama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Debugging teknikleri, profiling, performans optimizasyonu',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-bil4127',
    course_code: 'BİL 4127',
    name: 'Paralel Hesaplama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Paralel programlama, CUDA, OpenMP, MPI',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-7-ist4203',
    course_code: 'İST 4203',
    name: 'İstatistiksel Yöntemler',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 7,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'İleri istatistik yöntemleri, çok değişkenli analiz',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },

  // ============ 8. DÖNEM (BAHAR) - SEÇMELİ (30 AKTS) ============
  {
    id: 'bil-8-bil4102',
    course_code: 'BİL 4102',
    name: 'Dağıtık Algoritmalar',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Dağıtık sistemler, konsensüs algoritmaları, tutarlılık modelleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4104',
    course_code: 'BİL 4104',
    name: 'Uzman Sistemler',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Kural tabanlı sistemler, bilgi mühendisliği, çıkarım motorları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4106',
    course_code: 'BİL 4106',
    name: 'Veri Güvenliği',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Kriptografi, güvenlik protokolleri, siber güvenlik temelleri',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4108',
    course_code: 'BİL 4108',
    name: 'Fizik',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Bilgisayar bilimleri için ileri fizik konuları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4112',
    course_code: 'BİL 4112',
    name: 'Yapay Zeka',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'AI temelleri, arama algoritmaları, planlama, öğrenme',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4114',
    course_code: 'BİL 4114',
    name: 'Hesaplama Kuramına Giriş',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Otomatlar, formal diller, Turing makineleri, hesaplanabilirlik',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4120',
    course_code: 'BİL 4120',
    name: 'Gömülü Sistem Programlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Mikrodenetleyiciler, ARM, gerçek zamanlı sistemler',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4122',
    course_code: 'BİL 4122',
    name: 'Tamsayılı Programlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Tamsayılı lineer programlama, dal-sınır algoritması',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4124',
    course_code: 'BİL 4124',
    name: 'Mobil Programlama II',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [{ id: 'bil-5-bil3127', course_code: 'BİL 3127', course_name: 'Mobil Programlama I' }],
    description: 'iOS geliştirme, Swift, cross-platform (Flutter/React Native)',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-bil4126',
    course_code: 'BİL 4126',
    name: 'Servis Tabanlı Programlama',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 2,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Mikroservisler, SOA, REST, gRPC, mesaj kuyrukları',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
  {
    id: 'bil-8-ist4202',
    course_code: 'İST 4202',
    name: 'Aktüerya ve Risk Yönetimi',
    faculty: 'Fen Fakültesi',
    department: 'Bilgisayar Bilimleri',
    class_level: 4,
    semester: 8,
    credits: 5,
    theoretical_hours: 3,
    ects: 5,
    course_type: 'elective',
    prerequisites: [],
    description: 'Risk modelleme, sigorta matematiği, finansal risk analizi',
    status: 'active',
    created_at: '2020-01-15T10:00:00Z',
    updated_at: '2025-01-08T10:00:00Z',
  },
];

// Mock Available Courses (from enrollment-service)
export const mockAvailableCourses: AvailableCourse[] = [
  {
    id: '550e8400-e29b-41d4-a716-446655440301',
    course_code: 'BİL 2011-1',
    course_name: 'Algoritmalar ve Veri Yapıları',
    credits: 6,
    schedule_sessions: [
      { day: 1, slot: 1 },
      { day: 1, slot: 2 },
      { day: 3, slot: 3 },
      { day: 3, slot: 4 },
    ],
    max_capacity: 60,
    current_enrollment: 45,
    available_seats: 15,
    instructor: 'Prof. Dr. Ahmet Yılmaz',
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440302',
    course_code: 'BİL 2004-1',
    course_name: 'Veritabanı Yönetimi',
    credits: 5,
    schedule_sessions: [
      { day: 2, slot: 1 },
      { day: 2, slot: 2 },
      { day: 4, slot: 5 },
      { day: 4, slot: 6 },
    ],
    max_capacity: 60,
    current_enrollment: 48,
    available_seats: 12,
    instructor: 'Doç. Dr. Mehmet Kaya',
  },
];

// Mock Enrollment Programs (from enrollment-service)
export const mockEnrollmentPrograms: EnrollmentProgramResponse[] = [
  {
    id: '550e8400-e29b-41d4-a716-446655440401',
    student_id: '550e8400-e29b-41d4-a716-446655440005',
    semester: '2025-fall',
    status: 'approved',
    courses: [
      {
        id: '550e8400-e29b-41d4-a716-446655440301',
        course_code: 'BİL 2011-1',
        course_name: 'Algoritmalar ve Veri Yapıları',
        credits: 6,
      },
    ],
    created_at: '2025-08-15T10:00:00Z',
  },
];
