// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO staff.outbox_events (event_type, routing_key, payload)
VALUES ($1, $2, $3)
RETURNING id, event_type, routing_key, payload, status, retry_count, max_retries, created_at, processed_at, error_message
`

type CreateOutboxEventParams struct {
	EventType  string `json:"event_type"`
	RoutingKey string `json:"routing_key"`
	Payload    []byte `json:"payload"`
}

type CreateOutboxEventRow struct {
	ID           pgtype.UUID      `json:"id"`
	EventType    string           `json:"event_type"`
	RoutingKey   string           `json:"routing_key"`
	Payload      []byte           `json:"payload"`
	Status       OutboxStatusEnum `json:"status"`
	RetryCount   int16            `json:"retry_count"`
	MaxRetries   int16            `json:"max_retries"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ProcessedAt  pgtype.Timestamp `json:"processed_at"`
	ErrorMessage pgtype.Text      `json:"error_message"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CreateOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.RoutingKey, arg.Payload)
	var i CreateOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RoutingKey,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getFailedOutboxEvents = `-- name: GetFailedOutboxEvents :many
SELECT id, event_type, routing_key, payload, status, retry_count, max_retries, created_at, processed_at, error_message
FROM staff.outbox_events
WHERE status = 'failed' AND retry_count < max_retries
ORDER BY created_at ASC
LIMIT $1
`

type GetFailedOutboxEventsRow struct {
	ID           pgtype.UUID      `json:"id"`
	EventType    string           `json:"event_type"`
	RoutingKey   string           `json:"routing_key"`
	Payload      []byte           `json:"payload"`
	Status       OutboxStatusEnum `json:"status"`
	RetryCount   int16            `json:"retry_count"`
	MaxRetries   int16            `json:"max_retries"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ProcessedAt  pgtype.Timestamp `json:"processed_at"`
	ErrorMessage pgtype.Text      `json:"error_message"`
}

func (q *Queries) GetFailedOutboxEvents(ctx context.Context, limit int32) ([]GetFailedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getFailedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFailedOutboxEventsRow{}
	for rows.Next() {
		var i GetFailedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RoutingKey,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
SELECT id, event_type, routing_key, payload, status, retry_count, max_retries, created_at, processed_at, error_message
FROM staff.outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

type GetPendingOutboxEventsRow struct {
	ID           pgtype.UUID      `json:"id"`
	EventType    string           `json:"event_type"`
	RoutingKey   string           `json:"routing_key"`
	Payload      []byte           `json:"payload"`
	Status       OutboxStatusEnum `json:"status"`
	RetryCount   int16            `json:"retry_count"`
	MaxRetries   int16            `json:"max_retries"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ProcessedAt  pgtype.Timestamp `json:"processed_at"`
	ErrorMessage pgtype.Text      `json:"error_message"`
}

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]GetPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingOutboxEventsRow{}
	for rows.Next() {
		var i GetPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RoutingKey,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE staff.outbox_events
SET status = 'failed', retry_count = retry_count + 1, error_message = $2
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE staff.outbox_events
SET status = 'processed', processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}

const resetFailedOutboxEvent = `-- name: ResetFailedOutboxEvent :exec
UPDATE staff.outbox_events
SET status = 'pending', error_message = NULL
WHERE id = $1
`

func (q *Queries) ResetFailedOutboxEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedOutboxEvent, id)
	return err
}
