// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teacher_profiles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTeacherProfiles = `-- name: CountTeacherProfiles :one
SELECT COUNT(*) FROM staff.teacher_profiles tp
JOIN staff.staff s ON tp.staff_id = s.id
WHERE s.is_active = true
`

func (q *Queries) CountTeacherProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeacherProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeacherProfile = `-- name: CreateTeacherProfile :one
INSERT INTO staff.teacher_profiles (staff_id, academic_title, faculty, profile_image_url)
VALUES ($1, $2, $3, $4)
RETURNING id, staff_id, academic_title, faculty, profile_image_url,
          education, articles, bulletins, projects, awards,
          scholarships, admin_assignments, created_at, updated_at
`

type CreateTeacherProfileParams struct {
	StaffID         pgtype.UUID `json:"staff_id"`
	AcademicTitle   pgtype.Text `json:"academic_title"`
	Faculty         pgtype.Text `json:"faculty"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
}

func (q *Queries) CreateTeacherProfile(ctx context.Context, arg CreateTeacherProfileParams) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, createTeacherProfile,
		arg.StaffID,
		arg.AcademicTitle,
		arg.Faculty,
		arg.ProfileImageUrl,
	)
	var i TeacherProfile
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.AcademicTitle,
		&i.Faculty,
		&i.ProfileImageUrl,
		&i.Education,
		&i.Articles,
		&i.Bulletins,
		&i.Projects,
		&i.Awards,
		&i.Scholarships,
		&i.AdminAssignments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeacherProfileByStaffID = `-- name: DeleteTeacherProfileByStaffID :exec
DELETE FROM staff.teacher_profiles WHERE staff_id = $1
`

func (q *Queries) DeleteTeacherProfileByStaffID(ctx context.Context, staffID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeacherProfileByStaffID, staffID)
	return err
}

const getTeacherProfileByStaffID = `-- name: GetTeacherProfileByStaffID :one
SELECT tp.id, tp.staff_id, tp.academic_title, tp.faculty, tp.profile_image_url,
       tp.education, tp.articles, tp.bulletins, tp.projects, tp.awards,
       tp.scholarships, tp.admin_assignments, tp.created_at, tp.updated_at,
       s.email, s.first_name, s.last_name, s.department, s.phone, s.office_location
FROM staff.teacher_profiles tp
JOIN staff.staff s ON tp.staff_id = s.id
WHERE tp.staff_id = $1 AND s.is_active = true
LIMIT 1
`

type GetTeacherProfileByStaffIDRow struct {
	ID               pgtype.UUID      `json:"id"`
	StaffID          pgtype.UUID      `json:"staff_id"`
	AcademicTitle    pgtype.Text      `json:"academic_title"`
	Faculty          pgtype.Text      `json:"faculty"`
	ProfileImageUrl  pgtype.Text      `json:"profile_image_url"`
	Education        []byte           `json:"education"`
	Articles         []byte           `json:"articles"`
	Bulletins        []byte           `json:"bulletins"`
	Projects         []byte           `json:"projects"`
	Awards           []byte           `json:"awards"`
	Scholarships     []byte           `json:"scholarships"`
	AdminAssignments []byte           `json:"admin_assignments"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	Email            string           `json:"email"`
	FirstName        string           `json:"first_name"`
	LastName         string           `json:"last_name"`
	Department       pgtype.Text      `json:"department"`
	Phone            pgtype.Text      `json:"phone"`
	OfficeLocation   pgtype.Text      `json:"office_location"`
}

func (q *Queries) GetTeacherProfileByStaffID(ctx context.Context, staffID pgtype.UUID) (GetTeacherProfileByStaffIDRow, error) {
	row := q.db.QueryRow(ctx, getTeacherProfileByStaffID, staffID)
	var i GetTeacherProfileByStaffIDRow
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.AcademicTitle,
		&i.Faculty,
		&i.ProfileImageUrl,
		&i.Education,
		&i.Articles,
		&i.Bulletins,
		&i.Projects,
		&i.Awards,
		&i.Scholarships,
		&i.AdminAssignments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Department,
		&i.Phone,
		&i.OfficeLocation,
	)
	return i, err
}

const listTeacherProfiles = `-- name: ListTeacherProfiles :many
SELECT tp.id, tp.staff_id, tp.academic_title, tp.faculty, tp.profile_image_url,
       tp.education, tp.articles, tp.bulletins, tp.projects, tp.awards,
       tp.scholarships, tp.admin_assignments, tp.created_at, tp.updated_at,
       s.email, s.first_name, s.last_name, s.department, s.phone, s.office_location
FROM staff.teacher_profiles tp
JOIN staff.staff s ON tp.staff_id = s.id
WHERE s.is_active = true
ORDER BY s.last_name, s.first_name
LIMIT $1 OFFSET $2
`

type ListTeacherProfilesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTeacherProfilesRow struct {
	ID               pgtype.UUID      `json:"id"`
	StaffID          pgtype.UUID      `json:"staff_id"`
	AcademicTitle    pgtype.Text      `json:"academic_title"`
	Faculty          pgtype.Text      `json:"faculty"`
	ProfileImageUrl  pgtype.Text      `json:"profile_image_url"`
	Education        []byte           `json:"education"`
	Articles         []byte           `json:"articles"`
	Bulletins        []byte           `json:"bulletins"`
	Projects         []byte           `json:"projects"`
	Awards           []byte           `json:"awards"`
	Scholarships     []byte           `json:"scholarships"`
	AdminAssignments []byte           `json:"admin_assignments"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
	Email            string           `json:"email"`
	FirstName        string           `json:"first_name"`
	LastName         string           `json:"last_name"`
	Department       pgtype.Text      `json:"department"`
	Phone            pgtype.Text      `json:"phone"`
	OfficeLocation   pgtype.Text      `json:"office_location"`
}

func (q *Queries) ListTeacherProfiles(ctx context.Context, arg ListTeacherProfilesParams) ([]ListTeacherProfilesRow, error) {
	rows, err := q.db.Query(ctx, listTeacherProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeacherProfilesRow{}
	for rows.Next() {
		var i ListTeacherProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.AcademicTitle,
			&i.Faculty,
			&i.ProfileImageUrl,
			&i.Education,
			&i.Articles,
			&i.Bulletins,
			&i.Projects,
			&i.Awards,
			&i.Scholarships,
			&i.AdminAssignments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Department,
			&i.Phone,
			&i.OfficeLocation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeacherProfile = `-- name: UpdateTeacherProfile :one
UPDATE staff.teacher_profiles
SET academic_title = COALESCE($2, academic_title),
    faculty = COALESCE($3, faculty),
    profile_image_url = COALESCE($4, profile_image_url),
    education = COALESCE($5, education),
    articles = COALESCE($6, articles),
    bulletins = COALESCE($7, bulletins),
    projects = COALESCE($8, projects),
    awards = COALESCE($9, awards),
    scholarships = COALESCE($10, scholarships),
    admin_assignments = COALESCE($11, admin_assignments),
    updated_at = NOW()
WHERE staff_id = $1
RETURNING id, staff_id, academic_title, faculty, profile_image_url,
          education, articles, bulletins, projects, awards,
          scholarships, admin_assignments, created_at, updated_at
`

type UpdateTeacherProfileParams struct {
	StaffID          pgtype.UUID `json:"staff_id"`
	AcademicTitle    pgtype.Text `json:"academic_title"`
	Faculty          pgtype.Text `json:"faculty"`
	ProfileImageUrl  pgtype.Text `json:"profile_image_url"`
	Education        []byte      `json:"education"`
	Articles         []byte      `json:"articles"`
	Bulletins        []byte      `json:"bulletins"`
	Projects         []byte      `json:"projects"`
	Awards           []byte      `json:"awards"`
	Scholarships     []byte      `json:"scholarships"`
	AdminAssignments []byte      `json:"admin_assignments"`
}

func (q *Queries) UpdateTeacherProfile(ctx context.Context, arg UpdateTeacherProfileParams) (TeacherProfile, error) {
	row := q.db.QueryRow(ctx, updateTeacherProfile,
		arg.StaffID,
		arg.AcademicTitle,
		arg.Faculty,
		arg.ProfileImageUrl,
		arg.Education,
		arg.Articles,
		arg.Bulletins,
		arg.Projects,
		arg.Awards,
		arg.Scholarships,
		arg.AdminAssignments,
	)
	var i TeacherProfile
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.AcademicTitle,
		&i.Faculty,
		&i.ProfileImageUrl,
		&i.Education,
		&i.Articles,
		&i.Bulletins,
		&i.Projects,
		&i.Awards,
		&i.Scholarships,
		&i.AdminAssignments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
