// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessment_scores.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLockedScoresBySlugAndCourse = `-- name: CountLockedScoresBySlugAndCourse :one
SELECT COUNT(DISTINCT sa.registration_id)
FROM grades.student_assessment_scores sa
JOIN grades.student_course_registrations r ON sa.registration_id = r.id
WHERE r.course_id = $1 AND sa.slug = $2 AND sa.is_locked = TRUE
`

type CountLockedScoresBySlugAndCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) CountLockedScoresBySlugAndCourse(ctx context.Context, arg CountLockedScoresBySlugAndCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLockedScoresBySlugAndCourse, arg.CourseID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScoresBySlugAndCourse = `-- name: CountScoresBySlugAndCourse :one
SELECT COUNT(DISTINCT sa.registration_id)
FROM grades.student_assessment_scores sa
JOIN grades.student_course_registrations r ON sa.registration_id = r.id
WHERE r.course_id = $1 AND sa.slug = $2
`

type CountScoresBySlugAndCourseParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Slug     string    `json:"slug"`
}

func (q *Queries) CountScoresBySlugAndCourse(ctx context.Context, arg CountScoresBySlugAndCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScoresBySlugAndCourse, arg.CourseID, arg.Slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteScoresByCourse = `-- name: DeleteScoresByCourse :exec
DELETE FROM grades.student_assessment_scores
WHERE registration_id IN (
    SELECT id FROM grades.student_course_registrations WHERE course_id = $1
)
`

func (q *Queries) DeleteScoresByCourse(ctx context.Context, courseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScoresByCourse, courseID)
	return err
}

const getLockedRegistrationsBySlug = `-- name: GetLockedRegistrationsBySlug :many
SELECT registration_id
FROM grades.student_assessment_scores
WHERE slug = $1
  AND registration_id = ANY($2::uuid[])
  AND is_locked = TRUE
`

type GetLockedRegistrationsBySlugParams struct {
	Slug    string      `json:"slug"`
	Column2 []uuid.UUID `json:"column_2"`
}

// Returns the subset of the given registration IDs whose score at the given
// slug is already locked. Used by bulk upsert to skip locked entries without
// per-row roundtrips.
func (q *Queries) GetLockedRegistrationsBySlug(ctx context.Context, arg GetLockedRegistrationsBySlugParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getLockedRegistrationsBySlug, arg.Slug, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var registration_id uuid.UUID
		if err := rows.Scan(&registration_id); err != nil {
			return nil, err
		}
		items = append(items, registration_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScoreByRegistrationAndSlug = `-- name: GetScoreByRegistrationAndSlug :one
SELECT id, registration_id, slug, score, is_absent, graded_by, graded_at, is_locked FROM grades.student_assessment_scores
WHERE registration_id = $1 AND slug = $2
`

type GetScoreByRegistrationAndSlugParams struct {
	RegistrationID uuid.UUID `json:"registration_id"`
	Slug           string    `json:"slug"`
}

func (q *Queries) GetScoreByRegistrationAndSlug(ctx context.Context, arg GetScoreByRegistrationAndSlugParams) (GradesStudentAssessmentScore, error) {
	row := q.db.QueryRow(ctx, getScoreByRegistrationAndSlug, arg.RegistrationID, arg.Slug)
	var i GradesStudentAssessmentScore
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Slug,
		&i.Score,
		&i.IsAbsent,
		&i.GradedBy,
		&i.GradedAt,
		&i.IsLocked,
	)
	return i, err
}

const getScoresByRegistration = `-- name: GetScoresByRegistration :many
SELECT id, registration_id, slug, score, is_absent, graded_by, graded_at, is_locked FROM grades.student_assessment_scores
WHERE registration_id = $1
ORDER BY graded_at
`

func (q *Queries) GetScoresByRegistration(ctx context.Context, registrationID uuid.UUID) ([]GradesStudentAssessmentScore, error) {
	rows, err := q.db.Query(ctx, getScoresByRegistration, registrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GradesStudentAssessmentScore{}
	for rows.Next() {
		var i GradesStudentAssessmentScore
		if err := rows.Scan(
			&i.ID,
			&i.RegistrationID,
			&i.Slug,
			&i.Score,
			&i.IsAbsent,
			&i.GradedBy,
			&i.GradedAt,
			&i.IsLocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isScoreLocked = `-- name: IsScoreLocked :one
SELECT COALESCE(is_locked, FALSE) as is_locked
FROM grades.student_assessment_scores
WHERE registration_id = $1 AND slug = $2
`

type IsScoreLockedParams struct {
	RegistrationID uuid.UUID `json:"registration_id"`
	Slug           string    `json:"slug"`
}

func (q *Queries) IsScoreLocked(ctx context.Context, arg IsScoreLockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isScoreLocked, arg.RegistrationID, arg.Slug)
	var is_locked bool
	err := row.Scan(&is_locked)
	return is_locked, err
}

const lockScore = `-- name: LockScore :exec
UPDATE grades.student_assessment_scores
SET is_locked = TRUE
WHERE registration_id = $1 AND slug = $2
`

type LockScoreParams struct {
	RegistrationID uuid.UUID `json:"registration_id"`
	Slug           string    `json:"slug"`
}

func (q *Queries) LockScore(ctx context.Context, arg LockScoreParams) error {
	_, err := q.db.Exec(ctx, lockScore, arg.RegistrationID, arg.Slug)
	return err
}

const lockScoresByCourseAndSlug = `-- name: LockScoresByCourseAndSlug :exec
UPDATE grades.student_assessment_scores sa
SET is_locked = TRUE
FROM grades.student_course_registrations r
WHERE sa.registration_id = r.id
  AND r.course_id = $1
  AND sa.slug = $2
`

type LockScoresByCourseAndSlugParams struct {
	CourseID uuid.UUID `json:"course_id"`
	Slug     string    `json:"slug"`
}

// Bulk-lock every score for a given (course, slug). Used by an instructor to
// finalize an assessment once all students have drafts entered.
func (q *Queries) LockScoresByCourseAndSlug(ctx context.Context, arg LockScoresByCourseAndSlugParams) error {
	_, err := q.db.Exec(ctx, lockScoresByCourseAndSlug, arg.CourseID, arg.Slug)
	return err
}

const unlockScore = `-- name: UnlockScore :exec
UPDATE grades.student_assessment_scores
SET is_locked = FALSE
WHERE registration_id = $1 AND slug = $2
`

type UnlockScoreParams struct {
	RegistrationID uuid.UUID `json:"registration_id"`
	Slug           string    `json:"slug"`
}

func (q *Queries) UnlockScore(ctx context.Context, arg UnlockScoreParams) error {
	_, err := q.db.Exec(ctx, unlockScore, arg.RegistrationID, arg.Slug)
	return err
}

const upsertAssessmentScore = `-- name: UpsertAssessmentScore :one
INSERT INTO grades.student_assessment_scores (
    registration_id, slug, score, is_absent, graded_by, graded_at, is_locked
) VALUES (
    $1, $2, $3, $4, $5, NOW(), FALSE
)
ON CONFLICT (registration_id, slug) DO UPDATE SET
    score = EXCLUDED.score,
    is_absent = EXCLUDED.is_absent,
    graded_by = EXCLUDED.graded_by,
    graded_at = NOW()
WHERE grades.student_assessment_scores.is_locked = FALSE
RETURNING id, registration_id, slug, score, is_absent, graded_by, graded_at, is_locked
`

type UpsertAssessmentScoreParams struct {
	RegistrationID uuid.UUID      `json:"registration_id"`
	Slug           string         `json:"slug"`
	Score          pgtype.Numeric `json:"score"`
	IsAbsent       pgtype.Bool    `json:"is_absent"`
	GradedBy       uuid.UUID      `json:"graded_by"`
}

// Scores are inserted as editable drafts (is_locked=FALSE). An instructor
// later calls LockScoresByCourseAndSlug to finalize a whole assessment.
// Already-locked rows cannot be overwritten (admin must unlock first).
func (q *Queries) UpsertAssessmentScore(ctx context.Context, arg UpsertAssessmentScoreParams) (GradesStudentAssessmentScore, error) {
	row := q.db.QueryRow(ctx, upsertAssessmentScore,
		arg.RegistrationID,
		arg.Slug,
		arg.Score,
		arg.IsAbsent,
		arg.GradedBy,
	)
	var i GradesStudentAssessmentScore
	err := row.Scan(
		&i.ID,
		&i.RegistrationID,
		&i.Slug,
		&i.Score,
		&i.IsAbsent,
		&i.GradedBy,
		&i.GradedAt,
		&i.IsLocked,
	)
	return i, err
}
