// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GradesGradePointEnum string

const (
	GradesGradePointEnum400 GradesGradePointEnum = "4.00"
	GradesGradePointEnum375 GradesGradePointEnum = "3.75"
	GradesGradePointEnum350 GradesGradePointEnum = "3.50"
	GradesGradePointEnum325 GradesGradePointEnum = "3.25"
	GradesGradePointEnum300 GradesGradePointEnum = "3.00"
	GradesGradePointEnum275 GradesGradePointEnum = "2.75"
	GradesGradePointEnum250 GradesGradePointEnum = "2.50"
	GradesGradePointEnum225 GradesGradePointEnum = "2.25"
	GradesGradePointEnum200 GradesGradePointEnum = "2.00"
	GradesGradePointEnum175 GradesGradePointEnum = "1.75"
	GradesGradePointEnum150 GradesGradePointEnum = "1.50"
	GradesGradePointEnum125 GradesGradePointEnum = "1.25"
	GradesGradePointEnum100 GradesGradePointEnum = "1.00"
	GradesGradePointEnum050 GradesGradePointEnum = "0.50"
	GradesGradePointEnum000 GradesGradePointEnum = "0.00"
)

func (e *GradesGradePointEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GradesGradePointEnum(s)
	case string:
		*e = GradesGradePointEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GradesGradePointEnum: %T", src)
	}
	return nil
}

type NullGradesGradePointEnum struct {
	GradesGradePointEnum GradesGradePointEnum `json:"grades_grade_point_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if GradesGradePointEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGradesGradePointEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GradesGradePointEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GradesGradePointEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGradesGradePointEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GradesGradePointEnum), nil
}

type GradesGradingTypeEnum string

const (
	GradesGradingTypeEnumAbsolute GradesGradingTypeEnum = "absolute"
	GradesGradingTypeEnumRelative GradesGradingTypeEnum = "relative"
)

func (e *GradesGradingTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GradesGradingTypeEnum(s)
	case string:
		*e = GradesGradingTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GradesGradingTypeEnum: %T", src)
	}
	return nil
}

type NullGradesGradingTypeEnum struct {
	GradesGradingTypeEnum GradesGradingTypeEnum `json:"grades_grading_type_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if GradesGradingTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGradesGradingTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GradesGradingTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GradesGradingTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGradesGradingTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GradesGradingTypeEnum), nil
}

type GradesOutboxStatusEnum string

const (
	GradesOutboxStatusEnumPending   GradesOutboxStatusEnum = "pending"
	GradesOutboxStatusEnumProcessed GradesOutboxStatusEnum = "processed"
	GradesOutboxStatusEnumFailed    GradesOutboxStatusEnum = "failed"
)

func (e *GradesOutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GradesOutboxStatusEnum(s)
	case string:
		*e = GradesOutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GradesOutboxStatusEnum: %T", src)
	}
	return nil
}

type NullGradesOutboxStatusEnum struct {
	GradesOutboxStatusEnum GradesOutboxStatusEnum `json:"grades_outbox_status_enum"`
	Valid                  bool                   `json:"valid"` // Valid is true if GradesOutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGradesOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GradesOutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GradesOutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGradesOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GradesOutboxStatusEnum), nil
}

type GradesCoursesView struct {
	ID                 uuid.UUID        `json:"id"`
	CourseCode         string           `json:"course_code"`
	CourseName         string           `json:"course_name"`
	Credits            int16            `json:"credits"`
	Semester           string           `json:"semester"`
	Department         pgtype.Text      `json:"department"`
	InstructorID       uuid.UUID        `json:"instructor_id"`
	InstructorFullname pgtype.Text      `json:"instructor_fullname"`
	AssessmentSchema   []byte           `json:"assessment_schema"`
	SyncedAt           pgtype.Timestamp `json:"synced_at"`
}

type GradesOutboxEvent struct {
	ID           uuid.UUID                  `json:"id"`
	EventType    string                     `json:"event_type"`
	RoutingKey   string                     `json:"routing_key"`
	Payload      []byte                     `json:"payload"`
	Status       NullGradesOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2                `json:"retry_count"`
	MaxRetries   pgtype.Int2                `json:"max_retries"`
	CreatedAt    pgtype.Timestamp           `json:"created_at"`
	ProcessedAt  pgtype.Timestamp           `json:"processed_at"`
	ErrorMessage pgtype.Text                `json:"error_message"`
}

type GradesPrerequisiteCoursesView struct {
	CourseCode string           `json:"course_code"`
	CourseID   uuid.UUID        `json:"course_id"`
	SyncedAt   pgtype.Timestamp `json:"synced_at"`
}

type GradesStudentAssessmentScore struct {
	ID             uuid.UUID        `json:"id"`
	RegistrationID uuid.UUID        `json:"registration_id"`
	Slug           string           `json:"slug"`
	Score          pgtype.Numeric   `json:"score"`
	IsAbsent       pgtype.Bool      `json:"is_absent"`
	GradedBy       uuid.UUID        `json:"graded_by"`
	GradedAt       pgtype.Timestamp `json:"graded_at"`
	IsLocked       pgtype.Bool      `json:"is_locked"`
}

type GradesStudentCompletedCourse struct {
	ID                 uuid.UUID             `json:"id"`
	StudentID          uuid.UUID             `json:"student_id"`
	StudentNumber      string                `json:"student_number"`
	StudentFirstName   string                `json:"student_first_name"`
	StudentLastName    string                `json:"student_last_name"`
	StudentDepartment  pgtype.Text           `json:"student_department"`
	CourseID           uuid.UUID             `json:"course_id"`
	CourseCode         string                `json:"course_code"`
	CourseName         string                `json:"course_name"`
	Credits            int16                 `json:"credits"`
	Semester           string                `json:"semester"`
	InstructorID       uuid.UUID             `json:"instructor_id"`
	InstructorName     string                `json:"instructor_name"`
	AssessmentScores   []byte                `json:"assessment_scores"`
	WeightedAverage    pgtype.Numeric        `json:"weighted_average"`
	GradePoint         GradesGradePointEnum  `json:"grade_point"`
	GradingType        GradesGradingTypeEnum `json:"grading_type"`
	GradingConfig      []byte                `json:"grading_config"`
	ClassStatistics    []byte                `json:"class_statistics"`
	IsAttendanceFailed pgtype.Bool           `json:"is_attendance_failed"`
	FinalizedAt        pgtype.Timestamp      `json:"finalized_at"`
	FinalizedBy        uuid.UUID             `json:"finalized_by"`
}

type GradesStudentCourseRegistration struct {
	ID                 uuid.UUID        `json:"id"`
	StudentID          uuid.UUID        `json:"student_id"`
	CourseID           uuid.UUID        `json:"course_id"`
	Semester           string           `json:"semester"`
	IsAttendanceFailed pgtype.Bool      `json:"is_attendance_failed"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type GradesStudentsView struct {
	ID            uuid.UUID        `json:"id"`
	StudentNumber string           `json:"student_number"`
	FirstName     pgtype.Text      `json:"first_name"`
	LastName      pgtype.Text      `json:"last_name"`
	Email         pgtype.Text      `json:"email"`
	Department    pgtype.Text      `json:"department"`
	ClassLevel    pgtype.Int2      `json:"class_level"`
	IsActive      pgtype.Bool      `json:"is_active"`
	SyncedAt      pgtype.Timestamp `json:"synced_at"`
}
