// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prerequisite_courses_view.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const isPrerequisiteCourse = `-- name: IsPrerequisiteCourse :one
SELECT EXISTS(
    SELECT 1 FROM grades.prerequisite_courses_view
    WHERE course_code = $1
) as is_prerequisite
`

func (q *Queries) IsPrerequisiteCourse(ctx context.Context, courseCode string) (bool, error) {
	row := q.db.QueryRow(ctx, isPrerequisiteCourse, courseCode)
	var is_prerequisite bool
	err := row.Scan(&is_prerequisite)
	return is_prerequisite, err
}

const upsertPrerequisiteCourse = `-- name: UpsertPrerequisiteCourse :exec
INSERT INTO grades.prerequisite_courses_view (course_code, course_id, synced_at)
VALUES ($1, $2, NOW())
ON CONFLICT (course_code, course_id) DO UPDATE SET synced_at = NOW()
`

type UpsertPrerequisiteCourseParams struct {
	CourseCode string    `json:"course_code"`
	CourseID   uuid.UUID `json:"course_id"`
}

func (q *Queries) UpsertPrerequisiteCourse(ctx context.Context, arg UpsertPrerequisiteCourseParams) error {
	_, err := q.db.Exec(ctx, upsertPrerequisiteCourse, arg.CourseCode, arg.CourseID)
	return err
}
