// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment_program_courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollmentProgramCourse = `-- name: CreateEnrollmentProgramCourse :one
INSERT INTO enrollment.enrollment_program_courses (
    program_id, course_id, course_code, course_name, credits, created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
RETURNING id, program_id, course_id, course_code, course_name, credits, created_at
`

type CreateEnrollmentProgramCourseParams struct {
	ProgramID  pgtype.UUID `json:"program_id"`
	CourseID   pgtype.UUID `json:"course_id"`
	CourseCode string      `json:"course_code"`
	CourseName string      `json:"course_name"`
	Credits    int16       `json:"credits"`
}

func (q *Queries) CreateEnrollmentProgramCourse(ctx context.Context, arg CreateEnrollmentProgramCourseParams) (EnrollmentProgramCourse, error) {
	row := q.db.QueryRow(ctx, createEnrollmentProgramCourse,
		arg.ProgramID,
		arg.CourseID,
		arg.CourseCode,
		arg.CourseName,
		arg.Credits,
	)
	var i EnrollmentProgramCourse
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.CourseID,
		&i.CourseCode,
		&i.CourseName,
		&i.Credits,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProgramCourses = `-- name: DeleteProgramCourses :exec
DELETE FROM enrollment.enrollment_program_courses
WHERE program_id = $1
`

func (q *Queries) DeleteProgramCourses(ctx context.Context, programID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProgramCourses, programID)
	return err
}

const getCoursesByProgramID = `-- name: GetCoursesByProgramID :many
SELECT id, program_id, course_id, course_code, course_name, credits, created_at
FROM enrollment.enrollment_program_courses
WHERE program_id = $1
ORDER BY course_code
`

func (q *Queries) GetCoursesByProgramID(ctx context.Context, programID pgtype.UUID) ([]EnrollmentProgramCourse, error) {
	rows, err := q.db.Query(ctx, getCoursesByProgramID, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentProgramCourse{}
	for rows.Next() {
		var i EnrollmentProgramCourse
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.CourseID,
			&i.CourseCode,
			&i.CourseName,
			&i.Credits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
