// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment_rejection_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRejectionsByStudentAndSemester = `-- name: CountRejectionsByStudentAndSemester :one
SELECT COUNT(*) as total_rejections
FROM enrollment.enrollment_rejection_logs
WHERE student_id = $1 AND semester = $2
`

type CountRejectionsByStudentAndSemesterParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Semester  string      `json:"semester"`
}

func (q *Queries) CountRejectionsByStudentAndSemester(ctx context.Context, arg CountRejectionsByStudentAndSemesterParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRejectionsByStudentAndSemester, arg.StudentID, arg.Semester)
	var total_rejections int64
	err := row.Scan(&total_rejections)
	return total_rejections, err
}

const createRejectionLog = `-- name: CreateRejectionLog :one
INSERT INTO enrollment.enrollment_rejection_logs (
    original_program_id, student_id, advisor_id, advisor_fullname,
    semester, rejection_reason, rejected_courses, rejected_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
RETURNING id, original_program_id, student_id, advisor_id, advisor_fullname,
          semester, rejection_reason, rejected_courses, rejected_at
`

type CreateRejectionLogParams struct {
	OriginalProgramID pgtype.UUID `json:"original_program_id"`
	StudentID         pgtype.UUID `json:"student_id"`
	AdvisorID         pgtype.UUID `json:"advisor_id"`
	AdvisorFullname   string      `json:"advisor_fullname"`
	Semester          string      `json:"semester"`
	RejectionReason   string      `json:"rejection_reason"`
	RejectedCourses   []byte      `json:"rejected_courses"`
}

func (q *Queries) CreateRejectionLog(ctx context.Context, arg CreateRejectionLogParams) (EnrollmentRejectionLog, error) {
	row := q.db.QueryRow(ctx, createRejectionLog,
		arg.OriginalProgramID,
		arg.StudentID,
		arg.AdvisorID,
		arg.AdvisorFullname,
		arg.Semester,
		arg.RejectionReason,
		arg.RejectedCourses,
	)
	var i EnrollmentRejectionLog
	err := row.Scan(
		&i.ID,
		&i.OriginalProgramID,
		&i.StudentID,
		&i.AdvisorID,
		&i.AdvisorFullname,
		&i.Semester,
		&i.RejectionReason,
		&i.RejectedCourses,
		&i.RejectedAt,
	)
	return i, err
}

const getLatestRejectionByStudentAndSemester = `-- name: GetLatestRejectionByStudentAndSemester :one
SELECT id, original_program_id, student_id, advisor_id, advisor_fullname,
       semester, rejection_reason, rejected_courses, rejected_at
FROM enrollment.enrollment_rejection_logs
WHERE student_id = $1 AND semester = $2
ORDER BY rejected_at DESC
LIMIT 1
`

type GetLatestRejectionByStudentAndSemesterParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Semester  string      `json:"semester"`
}

func (q *Queries) GetLatestRejectionByStudentAndSemester(ctx context.Context, arg GetLatestRejectionByStudentAndSemesterParams) (EnrollmentRejectionLog, error) {
	row := q.db.QueryRow(ctx, getLatestRejectionByStudentAndSemester, arg.StudentID, arg.Semester)
	var i EnrollmentRejectionLog
	err := row.Scan(
		&i.ID,
		&i.OriginalProgramID,
		&i.StudentID,
		&i.AdvisorID,
		&i.AdvisorFullname,
		&i.Semester,
		&i.RejectionReason,
		&i.RejectedCourses,
		&i.RejectedAt,
	)
	return i, err
}

const getRejectionsByStudentAndSemester = `-- name: GetRejectionsByStudentAndSemester :many
SELECT id, original_program_id, student_id, advisor_id, advisor_fullname,
       semester, rejection_reason, rejected_courses, rejected_at
FROM enrollment.enrollment_rejection_logs
WHERE student_id = $1
  AND ($2::VARCHAR IS NULL OR $2 = '' OR semester = $2)
ORDER BY rejected_at DESC
`

type GetRejectionsByStudentAndSemesterParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Column2   string      `json:"column_2"`
}

func (q *Queries) GetRejectionsByStudentAndSemester(ctx context.Context, arg GetRejectionsByStudentAndSemesterParams) ([]EnrollmentRejectionLog, error) {
	rows, err := q.db.Query(ctx, getRejectionsByStudentAndSemester, arg.StudentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnrollmentRejectionLog{}
	for rows.Next() {
		var i EnrollmentRejectionLog
		if err := rows.Scan(
			&i.ID,
			&i.OriginalProgramID,
			&i.StudentID,
			&i.AdvisorID,
			&i.AdvisorFullname,
			&i.Semester,
			&i.RejectionReason,
			&i.RejectedCourses,
			&i.RejectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
