// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EnrollmentStatusEnum string

const (
	EnrollmentEnrollmentStatusEnumPending  EnrollmentStatusEnum = "pending"
	EnrollmentEnrollmentStatusEnumApproved EnrollmentStatusEnum = "approved"
)

func (e *EnrollmentStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnrollmentStatusEnum(s)
	case string:
		*e = EnrollmentStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for EnrollmentStatusEnum: %T", src)
	}
	return nil
}

type NullEnrollmentStatusEnum struct {
	EnrollmentStatusEnum EnrollmentStatusEnum `json:"enrollment_enrollment_status_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if EnrollmentStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnrollmentStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.EnrollmentStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnrollmentStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnrollmentStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnrollmentStatusEnum), nil
}

type OutboxStatusEnum string

const (
	EnrollmentOutboxStatusEnumPending   OutboxStatusEnum = "pending"
	EnrollmentOutboxStatusEnumProcessed OutboxStatusEnum = "processed"
	EnrollmentOutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"enrollment_outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type EnrollmentProgram struct {
	ID        pgtype.UUID              `json:"id"`
	StudentID pgtype.UUID              `json:"student_id"`
	Semester  string                   `json:"semester"`
	Status    NullEnrollmentStatusEnum `json:"status"`
	CreatedAt pgtype.Timestamp         `json:"created_at"`
}

type EnrollmentProgramCourse struct {
	ID         pgtype.UUID      `json:"id"`
	ProgramID  pgtype.UUID      `json:"program_id"`
	CourseID   pgtype.UUID      `json:"course_id"`
	CourseCode string           `json:"course_code"`
	CourseName string           `json:"course_name"`
	Credits    int16            `json:"credits"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type EnrollmentRejectionLog struct {
	ID                pgtype.UUID      `json:"id"`
	OriginalProgramID pgtype.UUID      `json:"original_program_id"`
	StudentID         pgtype.UUID      `json:"student_id"`
	AdvisorID         pgtype.UUID      `json:"advisor_id"`
	AdvisorFullname   string           `json:"advisor_fullname"`
	Semester          string           `json:"semester"`
	RejectionReason   string           `json:"rejection_reason"`
	RejectedCourses   []byte           `json:"rejected_courses"`
	RejectedAt        pgtype.Timestamp `json:"rejected_at"`
}

type OutboxEvent struct {
	ID           pgtype.UUID          `json:"id"`
	EventType    string               `json:"event_type"`
	RoutingKey   string               `json:"routing_key"`
	Payload      []byte               `json:"payload"`
	Status       NullOutboxStatusEnum `json:"status"`
	RetryCount   pgtype.Int2          `json:"retry_count"`
	MaxRetries   pgtype.Int2          `json:"max_retries"`
	ErrorMessage pgtype.Text          `json:"error_message"`
	CreatedAt    pgtype.Timestamp     `json:"created_at"`
	ProcessedAt  pgtype.Timestamp     `json:"processed_at"`
}

type ProcessedEvent struct {
	EventID     pgtype.UUID      `json:"event_id"`
	EventType   string           `json:"event_type"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}
