// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student_passed_prerequisites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasPassedPrerequisite = `-- name: HasPassedPrerequisite :one
SELECT EXISTS(
    SELECT 1 FROM enrollment.student_passed_prerequisites
    WHERE student_id = $1 AND course_code = $2
) as passed
`

type HasPassedPrerequisiteParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	CourseCode string      `json:"course_code"`
}

func (q *Queries) HasPassedPrerequisite(ctx context.Context, arg HasPassedPrerequisiteParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPassedPrerequisite, arg.StudentID, arg.CourseCode)
	var passed bool
	err := row.Scan(&passed)
	return passed, err
}

const upsertPassedPrerequisite = `-- name: UpsertPassedPrerequisite :exec
INSERT INTO enrollment.student_passed_prerequisites (student_id, course_id, course_code, semester, grade_point, synced_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (student_id, course_code) DO UPDATE SET
    course_id = EXCLUDED.course_id,
    semester = EXCLUDED.semester,
    grade_point = EXCLUDED.grade_point,
    synced_at = NOW()
`

type UpsertPassedPrerequisiteParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	CourseID   pgtype.UUID `json:"course_id"`
	CourseCode string      `json:"course_code"`
	Semester   string      `json:"semester"`
	GradePoint string      `json:"grade_point"`
}

func (q *Queries) UpsertPassedPrerequisite(ctx context.Context, arg UpsertPassedPrerequisiteParams) error {
	_, err := q.db.Exec(ctx, upsertPassedPrerequisite,
		arg.StudentID,
		arg.CourseID,
		arg.CourseCode,
		arg.Semester,
		arg.GradePoint,
	)
	return err
}
