// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeImportJob = `-- name: CompleteImportJob :exec
UPDATE student.import_jobs
SET status = 'completed', completed_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteImportJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeImportJob, id)
	return err
}

const countImportJobsByUser = `-- name: CountImportJobsByUser :one
SELECT COUNT(*) FROM student.import_jobs WHERE created_by = $1
`

func (q *Queries) CountImportJobsByUser(ctx context.Context, createdBy pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countImportJobsByUser, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImportJob = `-- name: CreateImportJob :one
INSERT INTO student.import_jobs (file_name, total_records, created_by)
VALUES ($1, $2, $3)
RETURNING id, file_name, total_records, processed_records, successful_records,
          failed_records, status, errors, created_by, started_at, completed_at, created_at
`

type CreateImportJobParams struct {
	FileName     string      `json:"file_name"`
	TotalRecords int32       `json:"total_records"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error) {
	row := q.db.QueryRow(ctx, createImportJob, arg.FileName, arg.TotalRecords, arg.CreatedBy)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.SuccessfulRecords,
		&i.FailedRecords,
		&i.Status,
		&i.Errors,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const failImportJob = `-- name: FailImportJob :exec
UPDATE student.import_jobs
SET status = 'failed', completed_at = NOW()
WHERE id = $1
`

func (q *Queries) FailImportJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failImportJob, id)
	return err
}

const getImportJobByID = `-- name: GetImportJobByID :one
SELECT id, file_name, total_records, processed_records, successful_records,
       failed_records, status, errors, created_by, started_at, completed_at, created_at
FROM student.import_jobs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetImportJobByID(ctx context.Context, id pgtype.UUID) (ImportJob, error) {
	row := q.db.QueryRow(ctx, getImportJobByID, id)
	var i ImportJob
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.SuccessfulRecords,
		&i.FailedRecords,
		&i.Status,
		&i.Errors,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listImportJobsByUser = `-- name: ListImportJobsByUser :many
SELECT id, file_name, total_records, processed_records, successful_records,
       failed_records, status, errors, created_by, started_at, completed_at, created_at
FROM student.import_jobs
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListImportJobsByUserParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListImportJobsByUser(ctx context.Context, arg ListImportJobsByUserParams) ([]ImportJob, error) {
	rows, err := q.db.Query(ctx, listImportJobsByUser, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportJob{}
	for rows.Next() {
		var i ImportJob
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.TotalRecords,
			&i.ProcessedRecords,
			&i.SuccessfulRecords,
			&i.FailedRecords,
			&i.Status,
			&i.Errors,
			&i.CreatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startImportJob = `-- name: StartImportJob :exec
UPDATE student.import_jobs
SET status = 'processing', started_at = NOW()
WHERE id = $1
`

func (q *Queries) StartImportJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startImportJob, id)
	return err
}

const updateImportJobProgress = `-- name: UpdateImportJobProgress :exec
UPDATE student.import_jobs
SET processed_records = $2,
    successful_records = $3,
    failed_records = $4,
    errors = $5
WHERE id = $1
`

type UpdateImportJobProgressParams struct {
	ID                pgtype.UUID `json:"id"`
	ProcessedRecords  int32       `json:"processed_records"`
	SuccessfulRecords int32       `json:"successful_records"`
	FailedRecords     int32       `json:"failed_records"`
	Errors            []byte      `json:"errors"`
}

func (q *Queries) UpdateImportJobProgress(ctx context.Context, arg UpdateImportJobProgressParams) error {
	_, err := q.db.Exec(ctx, updateImportJobProgress,
		arg.ID,
		arg.ProcessedRecords,
		arg.SuccessfulRecords,
		arg.FailedRecords,
		arg.Errors,
	)
	return err
}
