// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: closed_days.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClosedDay = `-- name: CreateClosedDay :one
INSERT INTO closed_days (date, reason, semester)
VALUES ($1, $2, $3)
RETURNING id, date, reason, created_at, semester
`

type CreateClosedDayParams struct {
	Date     pgtype.Date `json:"date"`
	Reason   string      `json:"reason"`
	Semester pgtype.Text `json:"semester"`
}

func (q *Queries) CreateClosedDay(ctx context.Context, arg CreateClosedDayParams) (ClosedDay, error) {
	row := q.db.QueryRow(ctx, createClosedDay, arg.Date, arg.Reason, arg.Semester)
	var i ClosedDay
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Reason,
		&i.CreatedAt,
		&i.Semester,
	)
	return i, err
}

const deleteClosedDay = `-- name: DeleteClosedDay :exec
DELETE FROM closed_days WHERE id = $1
`

func (q *Queries) DeleteClosedDay(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClosedDay, id)
	return err
}

const deleteClosedDaysBySemester = `-- name: DeleteClosedDaysBySemester :exec
DELETE FROM closed_days WHERE semester = $1
`

func (q *Queries) DeleteClosedDaysBySemester(ctx context.Context, semester pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteClosedDaysBySemester, semester)
	return err
}

const getClosedDaysByDateRange = `-- name: GetClosedDaysByDateRange :many
SELECT id, date, reason, created_at, semester FROM closed_days
WHERE date >= $1 AND date <= $2
ORDER BY date ASC
`

type GetClosedDaysByDateRangeParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) GetClosedDaysByDateRange(ctx context.Context, arg GetClosedDaysByDateRangeParams) ([]ClosedDay, error) {
	rows, err := q.db.Query(ctx, getClosedDaysByDateRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClosedDay{}
	for rows.Next() {
		var i ClosedDay
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Reason,
			&i.CreatedAt,
			&i.Semester,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isDateClosed = `-- name: IsDateClosed :one
SELECT EXISTS(
    SELECT 1 FROM closed_days WHERE date = $1
) AS is_closed
`

func (q *Queries) IsDateClosed(ctx context.Context, date pgtype.Date) (bool, error) {
	row := q.db.QueryRow(ctx, isDateClosed, date)
	var is_closed bool
	err := row.Scan(&is_closed)
	return is_closed, err
}

const listClosedDays = `-- name: ListClosedDays :many
SELECT id, date, reason, created_at, semester FROM closed_days
WHERE ($1::date IS NULL OR date >= $1)
  AND ($2::date IS NULL OR date <= $2)
ORDER BY date ASC
`

type ListClosedDaysParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
}

func (q *Queries) ListClosedDays(ctx context.Context, arg ListClosedDaysParams) ([]ClosedDay, error) {
	rows, err := q.db.Query(ctx, listClosedDays, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClosedDay{}
	for rows.Next() {
		var i ClosedDay
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Reason,
			&i.CreatedAt,
			&i.Semester,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
