// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MealTimeEnum string

const (
	MealTimeEnumLunch  MealTimeEnum = "lunch"
	MealTimeEnumDinner MealTimeEnum = "dinner"
)

func (e *MealTimeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MealTimeEnum(s)
	case string:
		*e = MealTimeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MealTimeEnum: %T", src)
	}
	return nil
}

type NullMealTimeEnum struct {
	MealTimeEnum MealTimeEnum `json:"meal_time_enum"`
	Valid        bool         `json:"valid"` // Valid is true if MealTimeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMealTimeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MealTimeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MealTimeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMealTimeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MealTimeEnum), nil
}

type MenuTypeEnum string

const (
	MenuTypeEnumNormal MenuTypeEnum = "normal"
	MenuTypeEnumVegan  MenuTypeEnum = "vegan"
)

func (e *MenuTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MenuTypeEnum(s)
	case string:
		*e = MenuTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MenuTypeEnum: %T", src)
	}
	return nil
}

type NullMenuTypeEnum struct {
	MenuTypeEnum MenuTypeEnum `json:"menu_type_enum"`
	Valid        bool         `json:"valid"` // Valid is true if MenuTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMenuTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MenuTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MenuTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMenuTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MenuTypeEnum), nil
}

type OutboxStatusEnum string

const (
	OutboxStatusEnumPending   OutboxStatusEnum = "pending"
	OutboxStatusEnumPublished OutboxStatusEnum = "published"
	OutboxStatusEnumFailed    OutboxStatusEnum = "failed"
)

func (e *OutboxStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatusEnum(s)
	case string:
		*e = OutboxStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatusEnum: %T", src)
	}
	return nil
}

type NullOutboxStatusEnum struct {
	OutboxStatusEnum OutboxStatusEnum `json:"outbox_status_enum"`
	Valid            bool             `json:"valid"` // Valid is true if OutboxStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatusEnum), nil
}

type ReservationStatusEnum string

const (
	ReservationStatusEnumPending   ReservationStatusEnum = "pending"
	ReservationStatusEnumConfirmed ReservationStatusEnum = "confirmed"
	ReservationStatusEnumCancelled ReservationStatusEnum = "cancelled"
	ReservationStatusEnumExpired   ReservationStatusEnum = "expired"
)

func (e *ReservationStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReservationStatusEnum(s)
	case string:
		*e = ReservationStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ReservationStatusEnum: %T", src)
	}
	return nil
}

type NullReservationStatusEnum struct {
	ReservationStatusEnum ReservationStatusEnum `json:"reservation_status_enum"`
	Valid                 bool                  `json:"valid"` // Valid is true if ReservationStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReservationStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ReservationStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReservationStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReservationStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReservationStatusEnum), nil
}

type Cafeteria struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Location     string             `json:"location"`
	HasVeganMenu bool               `json:"has_vegan_menu"`
	ServesDinner bool               `json:"serves_dinner"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ClosedDay struct {
	ID        pgtype.UUID        `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Semester  pgtype.Text        `json:"semester"`
}

type MonthlyMenu struct {
	ID        pgtype.UUID        `json:"id"`
	Year      int16              `json:"year"`
	Month     int16              `json:"month"`
	MenuData  []byte             `json:"menu_data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        OutboxStatusEnum   `json:"status"`
	RetryCount    int16              `json:"retry_count"`
	MaxRetries    int16              `json:"max_retries"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type ProcessedEvent struct {
	EventID     pgtype.UUID        `json:"event_id"`
	EventType   string             `json:"event_type"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Reservation struct {
	ID              pgtype.UUID           `json:"id"`
	BatchID         pgtype.UUID           `json:"batch_id"`
	StudentID       pgtype.UUID           `json:"student_id"`
	CafeteriaID     pgtype.UUID           `json:"cafeteria_id"`
	ReservationDate pgtype.Date           `json:"reservation_date"`
	MealTime        MealTimeEnum          `json:"meal_time"`
	MenuType        MenuTypeEnum          `json:"menu_type"`
	Status          ReservationStatusEnum `json:"status"`
	IsUsed          bool                  `json:"is_used"`
	UsedAt          pgtype.Timestamptz    `json:"used_at"`
	ExpiresAt       pgtype.Timestamptz    `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz    `json:"updated_at"`
}

type StudentsCache struct {
	ID            pgtype.UUID        `json:"id"`
	StudentNumber string             `json:"student_number"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	IsActive      bool               `json:"is_active"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
}
