// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessedEvent struct {
	EventID     string           `json:"event_id"`
	EventType   string           `json:"event_type"`
	ProcessedAt pgtype.Timestamp `json:"processed_at"`
}

type Session struct {
	ID              pgtype.UUID      `json:"id"`
	UserID          pgtype.UUID      `json:"user_id"`
	RefreshTokenJti string           `json:"refresh_token_jti"`
	DeviceInfo      *string          `json:"device_info"`
	IpAddress       *string          `json:"ip_address"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
	LastUsedAt      pgtype.Timestamp `json:"last_used_at"`
}

type User struct {
	ID                  pgtype.UUID      `json:"id"`
	Email               string           `json:"email"`
	PasswordHash        string           `json:"password_hash"`
	Role                string           `json:"role"`
	Department          *string          `json:"department"`
	IsActive            *bool            `json:"is_active"`
	TokenVersion        *int32           `json:"token_version"`
	ForcePasswordChange *bool            `json:"force_password_change"`
	FailedLoginAttempts *int32           `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamp `json:"locked_until"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
}
